### ISSUE TITLE
Missing declaration file `redis` throw error when compiling with TypeScript with strict type checking

### ISSUE THREAD

**Issue by TotomInc** [colyseus/colyseus#162]
```
Could not find a declaration file for module 'redis'.
'/Users/totominc/Desktop/Git/battlr/node_modules/redis/index.js' implicitly has an 'any' type.
Try `npm install @types/redis` if it exists or add a new declaration (.d.ts) file containing `declare module 'redis';`
```

The only things I have done so far:

```typescript
import * as Colyseus from 'colyseus';

export const server = new Colyseus.Server();
```

It can also be due to my `tsconfig.json` which have the `strict` property. This can be fixed by adding a vendor declaration file in Colyseus for redis (`declare module 'redis';`).

It's a bit annoying to manually add this dependency to fix an error which is from the framework.

**Comment by endel** [comment]
Thanks for reporting @TotomInc, I'll see what's necessary to be compatible with `"strict"` mode.

**Comment by seiyria** [comment]
You should try using (`@types/redis`](https://www.npmjs.com/package/@types/redis) and see if that works. Colyseus already has this as a dev dependency, and if you want to use it, you should add it as one, as well.

**Comment by TotomInc** [comment]
Installing `@types/redis` works, but since this should be listed as a dev-dep, you could maybe add a declaration file where you only declare the redis module. Make sure you also point to the declaration file in the `package.json`. It should work and avoid an error to the user.

**Comment by seiyria** [comment]
I think adding a dummy file would defeat the purpose of using types. Since redis is optional it should be up to the end user to install the corresponding types package. 

That said, I think the solution is to add a note to the install section of the docs.

**Comment by gioragutt** [comment]
@TotomInc so why not just list it as a `devDependency`? Just adding it to `package.json` sounds like the correct behaviour...

**Comment by endel** [comment]
I've added `@types/redis` as a `dependency` on Colyseus. It's ~100kb in the server just for typings but at least we don't have unexpected errors on the consumer side anymore
