### ISSUE TITLE
An entirely cosmetic issue

### ISSUE THREAD

**Issue by IanBellomy** [colyseus/colyseus#173]
<img width="434" alt="screen shot 2018-08-09 at 8 18 17 pm" src="https://user-images.githubusercontent.com/17239616/43932328-6575e7e6-9c11-11e8-9a38-fe2a802b9055.png">

**Comment by oyed** [comment]
I believe they want the curve added to the Colyseus logo - I do agree it looks nicer

**Comment by IanBellomy** [comment]
@oyed Bingo!

**Comment by IanBellomy** [comment]
Sorry to cause such a commotion! I was excited to find the project and then I then I was excited by the negative space in the top of the mark and then I noticed the bottom left point and was like SO CLOSE! 

The issue is that the bottom curve comes to a point. Sometimes we call this 'foot-balling' or a 'making a football' (because an American football is pointy on the sides). An ellipse in perspective on a cylinder like this will/should curve continuously until it's tangent to the wall of the cylinder, i.e. not pointy. I thought it might just be a compression artifact, but the top concave curve looked like it could be correct.

**Comment by oyed** [comment]
@IanBellomy If you want to send me the relevant files, I'll make a PR to get this changed :)

**Comment by endel** [comment]
Hey @IanBellomy @oyed, I've just made theAdobe Illustrator file available here: https://drive.google.com/open?id=0B0GnMJfxPfhJS2czd19KRm04T1U

**Comment by IanBellomy** [comment]
[https://drive.google.com/open?id=1XPR2KYnfErBd5xuR4RON7TZ86CkUTWzD](https://drive.google.com/open?id=1XPR2KYnfErBd5xuR4RON7TZ86CkUTWzD)

(Didn't have the font so the text might not look right on preview but should be fine on machines with Optimus.)

**Comment by oyed** [comment]
Hey @IanBellomy - I don't have illustrator so I can't help with getting the font added to the graphic. Is there any chance you could export to PSD and either me and/or @endel could add the font and create a PR to change the logo? Thanks!

Also @endel - what is the font used in the logo?

**Comment by IanBellomy** [comment]
Hi @oyed. Here are two .eps versions that should open in your editor of choice, one with the font embedded and one with the letter forms outlined. 
https://drive.google.com/drive/folders/13JKg-DDwyY1OzQnr-mpVvJhn6142WrTa?usp=sharing

Sorry for the hassle on a small thing.

**Comment by oyed** [comment]
Been a bit busy recently, but I'll get this added in ASAP and close the issue.

**Comment by IanBellomy** [comment]
@oyed Hah, I'm sure there are are more pressing things.
