### ISSUE TITLE
Proposal: Database Tutorial

### ISSUE THREAD

**Issue by lw1990** [colyseus/colyseus#177]
I think it's good that colyseus doesn't try to do too much like implement its own database system, but persistence/leaderboard/account sign in type stuff is really useful for multiplayer games and to make this framework even more beginner friendly, a game example hooked up to a third party database (such as Mongoose) with a tutorial on how it was done would be really helpful and make this framework more accessible for actually creating a full multiplayer game!

For example this colyseus tic tac toe game: https://github.com/endel/tic-tac-toe
If there was an account sign up/sign in and recorded how many times you won/lost/drew and to whom, I think that would be a great eye opener to someone wondering how it all ties together.

**Comment by Wenish** [comment]
just do it 💃

**Comment by oyed** [comment]
An extension of what @Wenish said - feel free to make this yourself.
Just be sure to use the following:

- The fact that `onLeave` and `onDispose` can be asynchronous
- For scaling, each room instance should be stateless
- Possible use of JWT Tokens combined with `onAuth`, allowing you to combine an externally created Auth API (Also great for scalability; separating Auth to a separate project/entity)

Feel free to ask any questions that might help :)

**Comment by oyed** [comment]
@Alexnortung It was more a generic statement than directed at the example of tic tac toe. The idea of "state" in Colyseus is different to what I was talking about - state in Colyseus is namespaced to the room it was created in, so that is perfectly fine.

**Comment by oyed** [comment]
To expand on my reply; having things like the board stored in the Room state is perfectly fine and preferred. But how do you handle things like authentication? The Tic Tac Toe room instance is on a different process, or even a different physical server. As such, data that should be accessible elsewhere should be stored elsewhere (And as such, not storing "state" locally). A common solution to the authentication issue is to use stateless authentication (Like JWT Tokens) and fetch data from an external source (Like writing an API that runs separately, which can also use its own form of scaling, such as load balancing).

**Comment by TakesTheBiscuit** [comment]
Hi @Wenish etc

I'm about to embark upon this adventure myself from a total trial and error point of view;

- [ ] Normal game lobby
- [ ] When last player disconnects stash game state/room state to a database
- [ ] When a known player comes back ('auth' / 'login') retrieve room state from database
- [ ] Use retrieved state to recreate the game in the saved state, enter known player(s) back into game

I think from a demo point of view i might start with a simple demo, something like:
- Max 8 players in a room
- Players can type words into a textarea (one per player)
- State of each textarea held in colyseus engine/memory
- When last player disconnects store all `n` text area's to storage
- Clean up the session/end the game on colyseus
- If a known (? need to check how i'll do this, maybe JWT) player comes back retrieve state from database/store and load it back into a new game lobby on colyseus
- Allow players to connect - they should see what they typed last time

**Comment by TakesTheBiscuit** [comment]
Given that this issue has been open since August - would it be ok if i carry this out? i can send something over as a PR to the examples repo or post it back to this one @endel

**Comment by endel** [comment]
Absolutely @TakesTheBiscuit, feel free to send PR for this! ❤️

**Comment by camus-code** [comment]
@lw1990 @TakesTheBiscuit  did you ever make any progress on this?
