### ISSUE TITLE
Possible improvement to scaling

### ISSUE THREAD

**Issue by oyed** [colyseus/colyseus#179]
Hey all,

So the company I work for works on a [Kubernetes](https://kubernetes.io/)-based system for deployment and scaling.

Might be worth looking in to this type of system, and possibly adding the ability to move matchmaking to its own individual process to allow for automated scaling?

I don't know enough regarding Kubernetes to comment on this, but I'll do some research and talk to the team about what is required to make this work with larger-scale scaling techniques.

**Comment by seiyria** [comment]
Possibly related, and shared in gitter today: https://github.com/GoogleCloudPlatform/open-match

**Comment by endel** [comment]
Discussion moved to https://github.com/colyseus/colyseus/issues/370 🙈
