### ISSUE TITLE
MatchMaker issues with Redis

### ISSUE THREAD

**Issue by arjunrajskoolbo** [colyseus/colyseus#183]
I was trying out the Redis presence stuff. It worked alright in my first test, but now I'm running into issues after I restarted my local colyseus servers. 

My room code and client code are pretty much the same as the chat example.
For RedisPresence args - host, port and password are all I'm using. My testing method was to run 2 local servers running on different ports, and 2 clients connecting to each of these servers.

I'm facing these issues -
1) I sometimes get the following debug message after restarting a server -
`
remote room (fxuGYLKSL1) timed out, requesting "hasReachedMaxClients"
    at Timeout.setTimeout (C:\Users\Skoolbo\Documents\skoolboracingserver\node_modules\colyseus\lib\MatchMaker.js:157:32)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
`

2) I would repeatedly get the debug message 'MatchMaking couldn't process message: 100' on both servers, and an undefined message would then get sent to the connected client.
3) The local servers don't seem to connect/sync with each other after the first attempt.

I was able to get these issues by force terminating (ctrl+c on windows) my local colyseus server processes. My first run went fine though, it's only after force closing both servers that issues 2) and 3) first started, and 1) came up on one of my servers after a few restarts as I was trying to figure out why issue 3) was happening.

To try to rectify the issue, I also tried to delete the keys used by the server. My room's name was called "test", these are the keys that were created by colyseus - "a_test","test","test:c", but what's odd is that "test:c" is the only key that wouldn't be deleted after closing down both servers. Deleting it when the servers were closed didn't help in any way.

Colyseus v0.9.16
OS - Windows 10
Node v8.11.1

**Comment by oyed** [comment]
Possibly related to #171 given Match Maker isn't waiting for disposed rooms.

**Comment by endel** [comment]
Hey guys, I've managed to reproduce this error when on the [RemoteClient unit test](https://github.com/gamestdio/colyseus/blob/master/test/RemoteClientTest.ts) and had to refactor the process of registering rooms to be async, to clean up possible stale cached data after an ungraceful shutdown. Let me know if you still find this issue on version [`0.9.18`](https://github.com/gamestdio/colyseus/releases/tag/0.9.18).

**Comment by oyed** [comment]
I'm going to assume this is no longer an issue since `0.9.18` - feel free to reopen otherwise.
