### ISSUE TITLE
Add API for getting all available rooms by more than just name

### ISSUE THREAD

**Issue by gioragutt** [colyseus/colyseus#193]
F.e:

Get all rooms by regex: `getAllAvailableRooms("lobby_*")

this is what I currently need, and I think about implementing it locally, to some extent, but it would require changing the unity API as well.

**Comment by endel** [comment]
You have been heard @gioragutt! ❤️  Creating rooms and getting all available rooms is now a thing. See the migration guide for `0.11` here: https://docs.colyseus.io/migrating/0.11/
