### ISSUE TITLE
RedisPresence not working

### ISSUE THREAD

**Issue by LightningK0ala** [colyseus/colyseus#196]
## Context
I've just been experimenting with RedisPresence. I have a basic account at RedisLab, the host, port and password are correctly configured when setting up the Colyseus Server.

I then build my server and run it with pm2 in cluster mode (7 instances).

I am making a simple 1v1 game where a room is created by a player, then another user joins it using the ID.

The issue I'm having is that my second user is only intermittently able to join the room. I believe this is happening because RedisPresence isn't working as expected. When it does work it's because it's hitting the instance on the cluster that actually holds the room.

Are there any known issues with this? I was planning to use Zeit now for deployment and hence the need for RedisPresence, otherwise I might go for a single server + Memshared solution.

## Your Environment

* Colyseus Version: ^0.9.15
* Node.js Version: 8.11.2
* Operating System and version: maxOS High Sierra 10.13.3

**Comment by endel** [comment]
Hi @LightningK0ala, do you see any error during this process? Does @seiyria's tip helped you on this?

>  you might need to set the timer to 0 (or set it higher, it defaults to like 300?)
>
>         const gameServer = new Server({
>          presence,
>          server,
>          pingTimeout: 0
>        });

**Comment by LightningK0ala** [comment]
Hi @endel,

No error seen. Haven't tried @seiyria's tip (been busy with other parts of the stack).
Hopefully I'll get to try it soon and will report back.

**Comment by LightningK0ala** [comment]
Just FYI, setting the pingTimeout to 0 doesn't work.
My game server has a rest endpoint setup to let clients query for roomIds (based on an alias).
It calls MatchMaker's `getAllRooms` but it's throwing this error:
```
Failed to getAllRooms remote room (-ij7qjoccs) timed out, requesting "getAvailableData"
```

**Comment by LightningK0ala** [comment]
Good news, it seems to be working after increasing `COLYSEUS_PRESENCE_SHORT_TIMEOUT`, which conveniently can be set as an environment variable.
Seems like the issue was in fact Redis timing out.
Thanks @seiyria + @endel.

**Comment by endel** [comment]
That's great to hear @LightningK0ala. Out of curiosity, are you using an external service for Redis (RedisLabs, AWS ElastiCache, etc)? Or is the Redis instance installed in the same machine?

**Comment by LightningK0ala** [comment]
External (RedisLabs). Also on a high latency connection atm 😅
