### ISSUE TITLE
multi performance issue

### ISSUE THREAD

**Issue by gabrieltong** [colyseus/colyseus#204]
I want to make a card game, which has lobby, room, and I want to have lobby chat , room chat and game msg.

I want to mix them , a big room for all things .

and there's another options, separate room for each thing.

I don't know which is better, and if I make use the second way, is there any performance issue ?

**Comment by oyed** [comment]
Separating logic in to separate rooms is definitely going to help with both performance and scalability. E.g. having a `Room` for the `Lobby` (If you only want 1 of these Rooms to exist, you can do so, same for Lobby Chat), Room Chat and the Game Logic itself should be in a single `Room` which can then be scaled accordingly.

**Comment by oyed** [comment]
Closing this now - if you have any more questions, feel free to join the [Discord](https://discord.gg/RY8rRS7)
