### ISSUE TITLE
trying to send event to non-existing remote client

### ISSUE THREAD

**Issue by endel** [colyseus/colyseus#205]
Reported by @pantaovay on [Gitter](https://gitter.im/gamestdio/colyseus) channel.

> colyseus:errors trying to send event ("147,13,170,57,95,105,68,49,53,109,68,77,55,129,162,105,100,181,67,111,109,109,111,110,82,111,111,109,80,108,97,121,101,114,82,101,97,100,121") to non-existing remote client (null) +867ms
 
There is a client on Room that has no sessionId

![Screenshot](https://files.gitter.im/gamestdio/colyseus/Auyy/image.png)

It happens in multi-process mode with memshared

**Comment by debianw** [comment]
Hi @endel, I was able to reproduce this issue with my example: https://github.com/debianw/colyseus-hacking

Steps:

1. Connect client 1 using Browser
2. Connect client 2 using Browser 2
3. Connect client 3 using Mobile
4. Set airplane mode to the mobile and un set airplane ( Client will ask for rejoin and all went ok, client was reconnected with success )
5. Client 3 sends a message, then the following error shows in the server:

![Screen Shot 2019-03-17 at 11 32 10 AM](https://user-images.githubusercontent.com/1002407/54495310-5a684800-48a8-11e9-9101-772179c2e038.png)

**Comment by endel** [comment]
Hi @debianw, thanks for sharing. 

I've deprecated `MemsharedPresence` this week, in favor of using proxies to forward connections directly to the process a room is living in. This is not battle tested yet though: https://github.com/colyseus/proxy
