### ISSUE TITLE
State sync missing fields in extended classes

### ISSUE THREAD

**Issue by etherny** [colyseus/colyseus#215]
## Steps to Reproduce (for bugs)
1. Extends a class in the state

## Context
I m using colyseus in unity context.
All work really fine except this for now.
I m using state sync, in the state i have an
```
    private players: EntityMap<Player> = {};
```
Player extends another class with only and id as field.

When i add a player in the EntityMap i do not receive the extended id field.

To avoid this, i removed the extend and all works fine.

## Your Environment

* Colyseus Version: 0.9.15
* Node.js Version: v10.15.0
* Operating System and version: Windows

**Comment by endel** [comment]
Hi @etherny, can you provide some source code of your example? Using `extends` shouldn't be a problem

**Comment by endel** [comment]
Closing as this issue lacks some context. I recommend using the new serializer now. Feel free to re-open if you'd like to!
