### ISSUE TITLE
allow complex objects on `onJoin()`

### ISSUE THREAD

**Issue by endel** [colyseus/colyseus#216]
as reported by @gnunua on Discord:

> on `onInit` I have got all  merged values specified on `Server#register()` with the options provided the client on `client.join()`. However, on onJoin I have receiving stringified data. if I pass object from client side. here is the sample `someObj: '[object Object]`.  Any ideas ? Thanks in advance.

>  My sending object is complex and nested.  look like something this 
```
 parentObj: {
    child: {
        foo: 1,
    },
    child2: {
        foo: 2
    }
} 
```

> I was thinking you just pass the same data form `onInit` to `onJoin`.

This should be easily done by caching the options for that player locally in the room, and removing it if the reserved seat for that player expires

**Comment by gnunua** [comment]
👍

**Comment by endel** [comment]
Another scenario brought by @Tobi4s1337, which is related to this:

When joining a room with a high number as an option, the query string parser tries to evaluate it as number, and it gets rounded:

```javascript
room.join("room_name", { high_number: "76561198933528857" })
```

During `onAuth`, the number arrives as `76561198933528860` (and not a string) because of the ["smart" query string parsing](https://github.com/colyseus/colyseus/blob/0f606f566996ef7956306ce9a758a6b5805a85ee/src/Utils.ts#L82-L101).

To fix this, all join options should be cached in the room handler upon seat reservation instead of being passed along as query string.

**Comment by endel** [comment]
This works on `0.11` 🎉 🎉 🎉
