### ISSUE TITLE
Support for more C++ client-side integrations

### ISSUE THREAD

**Issue by endel** [colyseus/colyseus#217]
Now that we have the [Cocos2d-x client](https://github.com/colyseus/colyseus-cocos2d-x), it would be nice to make it work on the majority of C++ targets. The current C++ implementation is tied to cocos2d-x networking and callback system.

**Related issues:**
- Godot Engine request (https://github.com/colyseus/colyseus/issues/195)
- Unreal Engine request (https://github.com/colyseus/colyseus/issues/16)
- SDL request (https://github.com/colyseus/colyseus-cocos2d-x/issues/1)

If you have experience with these environments, your help would be really welcome! 🙏

**Comment by endel** [comment]
Possible WebSocket libraries to replace with:
- https://github.com/zaphoyd/websocketpp
- https://github.com/dhbaird/easywsclient

Insights for a generic callback system: 
- https://embeddedartistry.com/blog/2017/1/26/c11-improving-your-callback-game
- https://gist.github.com/4poc/3155832

**Comment by HeadClot** [comment]
Just a bit of advice with the UE4 side of things. Make it a plugin. It will be so much more maintainable than a collection of files. That said - I look forward to the UE4 integration :)

**Comment by endel** [comment]
Hi @HeadClot, I haven't started researching how UE4 works so far, I think we should follow how this WebSocket plugin is structured, right? https://github.com/feixuwu/UEWebsocket/tree/master/Plugins/WebSocket

**Comment by HeadClot** [comment]
@endel - I would look at how the socket cluster plugin on the UE4 marketplace is structured. 
Here is the source code -> https://github.com/ziicreater/socketcluster-client-ue4
Here is the marketplace link -> https://www.unrealengine.com/marketplace/en-US/slug/socketcluster-client

**Comment by thebspin** [comment]
Is there any info/progress on a Godot implementation? I cannot maintain but i can help from time to time.

**Comment by HeadClot** [comment]
@endel Might be worth looking into Godot support on the C# Side. The devs have been working hard on Mono C# Support. It also got web socket support as of 3.1 Might make your life easier. :)

**Comment by HeadClot** [comment]
Hey @endel I got talking to inQonsole About the UE4 SocketClusterClient here is what he said in terms of compatibility with Node.js, Colyseus and the UE4 Socket Cluster Client.

> Socketcluster is written in node.js yes that works, the client is written in C the other end (server end) doesn't really matter for the client-side in what language or what you are using, but keep in mind that socketcluster uses it's own ping and pong and handshake protocol, in the raw form the UE4 client is just pure socket so it can work with anything but you might have to edit the source code, if you are not using Socketcluster Server, I can't guarantee that it will work out of the box.

**Comment by hugosteixeira** [comment]
Any update on the godot client support?

**Comment by rcoppy** [comment]
Hey @hugosteixeira,

A little while ago I was asking around the Colyseus discord about this topic and at the time folks were echoing @HeadClot, suggesting taking the Unity C# client as a start and porting it (still in C#) over to godot, just swapping out incompatible API calls.

I have /no/ idea how complex such an undertaking would be, but I'm trying to carve out some time in the coming weeks to poke around source code to try and see. Will keep you posted 🙂

**Comment by benhjames** [comment]
Just FYI (so this isn't closed!) I'm currently working on a C++ Colyseus plugin for Unreal Engine, based on the amazing work already with the cocos-2d integration! I hope it will be ready in the next couple weeks 🙂

**Comment by HeadClot** [comment]
> Just FYI (so this isn't closed!) I'm currently working on a C++ Colyseus plugin for Unreal Engine, based on the amazing work already with the cocos-2d integration! I hope it will be ready in the next couple weeks 🙂

Awesome! Will it have blueprint support out of curiosity?

**Comment by benhjames** [comment]
> Awesome! Will it have blueprint support out of curiosity?

I'm not sure it will initially (we don't need it for our use case as we're building another plugin on top of it!) but it would be a welcome add from the community! 👍

**Comment by endel** [comment]
Sounds very exciting, can't wait to check it out @benhjames! 🤯

**Comment by benhjames** [comment]
I'm pleased to say there's an initial working version of Colyseus for Unreal here!

https://github.com/charisma-ai/colyseus-ue4

Whilst it doesn't yet have Blueprint support, you can always do something like we've done with our Charisma plugin and wrap the `colyseus-ue4` module with your own module that exposes Blueprints:

https://github.com/charisma-ai/charisma-sdk-ue4/blob/colyseus/Source/CharismaModule/Private/Charisma.cpp

One step closer to running Colyseus everywhere! 🎉

**Comment by HeadClot** [comment]
> I'm pleased to say there's an initial working version of Colyseus for Unreal here!
> 
> https://github.com/charisma-ai/colyseus-ue4
> 
> Whilst it doesn't yet have Blueprint support, you can always do something like we've done with our Charisma plugin and wrap the `colyseus-ue4` module with your own module that exposes Blueprints:
> 
> https://github.com/charisma-ai/charisma-sdk-ue4/blob/colyseus/Source/CharismaModule/Private/Charisma.cpp
> 
> One step closer to running Colyseus everywhere! 🎉

This is great!

**Comment by endel** [comment]
Exciting! Thanks a lot for sharing this @benhjames! 🎉 

AFAIK the schema decoder from existing C++/Cocos2d-x is still from `@colyseus/schema@^0.5.x`. We had some breaking changes for schema `@colyseus/schema@^1.0.0` mostly to stabilize onAdd/onChange/onRemove callbacks and adding the concept of `refId`'s.

**Comment by paulocoutinhox** [comment]
Axmol version: https://github.com/paulocoutinhox/axmol-multiplayer

**Comment by paulocoutinhox** [comment]
Please update C++ code to latest.
