### ISSUE TITLE
Feature proposal: broadcast after patch

### ISSUE THREAD

**Issue by endel** [colyseus/colyseus#218]
Hey everyone & @colyseus/gladiators 

I have a use-case where a `broadcast` message needs to arrive AFTER the state has been patched in the client-side. I'm thinking how the API for this should look like.

As `broadcast` currently allows passing options along with it (as `options.except`: https://github.com/colyseus/colyseus/issues/136), I'm thinking on enabling this now:

```
this.broadcast(data, { delayed: true });
```

A "delayed" broadcast means it will be sent only after the patch has been sent. I'm afraid this is not intuitive enough. 

To be more intuitive, we could use `afterPatch`, but it looks weird:

```
this.broadcast(data, { afterPatch: true });
```

What are your thoughts? Thanks!

**Comment by seiyria** [comment]
I think if you're not going to offer analogs like `beforePatch`, then it doesn't make sense to use `afterPatch`. I would be explicit: `delayUntilFirstPatch` or `delayUntilAfterFirstPatch` or the like.

**Comment by endel** [comment]
I wanted to keep it short & simple. I can't think of a use-case to broadcast to `beforePatch` - any `broadcast` calls are most certainly going to happen before the patch anyway because it happens immediately

**Comment by endel** [comment]
a few more ideas 🙈 gosh, naming things is hard
- `broadcast(data, { nextPatch: true })`
- `broadcast(data, { afterNextPatch: true })`

**Comment by endel** [comment]
I went for `afterNextPatch` 🙈  we can always change naming in the next releases, I'm going to release `0.10.0` soon when the new serialization comes out!

**Comment by developgiiker** [comment]
why this feature is needed? and no any comment in the latest release....
i have to follow the git log after a long road to here, but i still don't know why add this feature, it look like wired in the code

**Comment by Elyx0** [comment]
@developgiiker I don't know the exact use but the same way you have `setImmediate` and `setTimeout(fn,0)` and `process.nextTick()` in js. It doesn't shock me to want a way to take some action only after a patch to be sure all players are at least synced to the patch state. I think it's always practical to have access to the lifecycle management

**Comment by endel** [comment]
This feature has been introduced because the state patches are synched during an interval (e.g. 50ms). Messages on the other hand are sent immediately by default. 

By using the `afterNextPatch` option, you'd ensure the latest state change you've made in the server-side will be present in the client-side whenever the message you broadcasted reaches the client. Does that make sense?

Cheers

**Comment by developgiiker** [comment]
Thanks for the explain. I got the point.
