### ISSUE TITLE
Pass feedback when returning false from requestJoin / Custom error message

### ISSUE THREAD

**Issue by klase** [colyseus/colyseus#226]
Is there a recommended way to pass feedback to the client when returning false from requestJoin on the server? I have multiple scenarios where it will return false and I'd like to notify the user the reason why it failed to join ("Active client with same id already exists", "Room is private" etc).

**Comment by endel** [comment]
This is now possible on `0.11` by throwing an Error during `onAuth` or `onJoin` 🎉 
See the migration guide for 0.11 here: https://docs.colyseus.io/migrating/0.11/
