### ISSUE TITLE
colyseus test-kit

### ISSUE THREAD

**Issue by amir-arad** [colyseus/colyseus#229]
I wonder if there are any tools, thoughts, examples or best-practices regarding testing colyseus games.

## Context
I'm evaluating Colyseus for a complicated game I want to build. I would really like it to be covered by tests.

## Your Environment
* Colyseus Version: latest

**Comment by endel** [comment]
@amir-arad that's a great question. At first, I think it makes sense to only test the room state and related entities, not the room itself. 

You should be able to instantiate a room manually in the test cases though, and call its methods manually, like  `onInit()`, `onJoin`, `onMessage()`, etc.

I'd appreciate your inputs on this as well!

**Comment by Wenish** [comment]
i think. most tests about colyseus itself are in the end 2 end tests, since its focusing on networking.

most unit test will be about the custom game logic on the server.

**Comment by amir-arad** [comment]
@endel it makes total sense. 
I personally try to avoid unit testing when I can, and keep the tests as close to the product as possible, so I'm looking for something that gives me the e-2-e flow. 
what I would like to be able to write is something like:
```ts
beforeEach(setup(Room))
it(async ()=>{
const client1 = connectTo(room1);
const client2 = connectTo(room1);
client1.doStuff();
while(! await isExpectedState(client2)){
room1.tick();
}
})
```
I guess i was looking for a fake colyseus container that can smulate the lifecycle of rooms, with local clients attached to it without the need for any network or the like (keeping it all in the same memory space with the same state tree instances). so the game tests can load and run quickly, and get the same behavior that a real e2e setup will give, incl. future complicated configurations like state sync filtering. having the possibility to run it in the browser can help a lot (the ability to test from UI to UI).

**Comment by amir-arad** [comment]
having said that, I don't expect it to exist just because i thought it might help me ;)

 anyways there seem to also be a serious lack of pixi.js test capabilities, so im not gonna get what i was looking for anyways. need to adjust :/

**Comment by endel** [comment]
As of today, the `npm init colyseus-app` templates include `@colyseus/testing` + `mocha` to facilitate testing a Colyseus application 🎉 

```typescript
  it("connecting into a room", async () => {
    // `room` is the server-side Room instance reference.
    const room = await colyseus.createRoom<MyRoomState>("my_room", {});

    // `client1` is the client-side `Room` instance reference (same as JavaScript SDK)
    const client1 = await colyseus.connectTo(room);

    // make your assertions
    assert.strictEqual(client1.sessionId, room.clients[0].sessionId);

    // wait for state sync
    await room.waitForNextPatch();

    // make assertion based on the state
    assert.deepStrictEqual({ mySynchronizedProperty: "Hello world" }, client1.state.toJSON());
  });
```

The testing utility comes with an HTTP client for testing custom routes, and the Colyseus SDK for establishing real client-server connections in the test suite.

**Documentation: https://docs.colyseus.io/colyseus/tools/unit-testing/**

Feedback is very welcome!
