### ISSUE TITLE
Feature Request: Rewrite the behavior of Room.setState similar to React

### ISSUE THREAD

**Issue by ChristianIvicevic** [colyseus/colyseus#235]
Currently the state handling in the server API is implemented in a (subjectively) unintuitive way. In the `onInit` of a particular room you'd call something like `Room.setState(new RoomSchema());` once and updating the state via the `Room.setSimulationInterval` handler with some repetitive lines such as the following (arbitrary) sample:
```typescript
this.state.enemyPositionX = Math.cos(this.clock.currentTime / 1000 * Math.PI / 2) * 3;
this.state.enemyPositionY = Math.sin(this.clock.currentTime / 1000 * Math.PI / 2) * 3;
```
In React there exists a `setState` method on each stateful component that allows merging state variables using one of two variants such as this:
```typescript
const enemyPositionX = /* ... */;
const enemyPositionY = /* ... */;
// Variant 1 typing: setState(newStateVariables: Partial<StateType>)
this.setState({ enemyPositionX, enemyPositionY });
// Variant 2 typing: setState((previousState: StateType) => Partial<StateType>)
this.setState((previousState) => ({ enemyPositionX: previousState.enemyPositionX + 1 }));
// Variant 2 with destructuring
this.setState(({ enemyPositionX }) => ({ enemyPositionX: enemyPositionX + 1 }));
```
As you can see it is definitely possible to write a robust API to prevent repeating verbose `this.state.foo` assignments and which allows many useful shenannigans like functions and destructuring. Even though this is a breaking change in the behavior of `Room.setState` I suggest looking into this implementation since the `Room.setState` method is currently only supposed to be called during initialization and not for updating the state across the simulation which is counterintuitive.

When taking this route it'd be much safer to define the `state` as `readonly` for the following reasons:

1. It would enforce reading via `this.state` and writing via `this.setState`.
2. Currently it's possible to manipualte some variables of `this.state` that are part of the `Schema` class and not custom variables which is most likely super unintended. Enforcing the use of `setState` will prevent overwriting the variables of the `Schema` base class.

**Comment by endel** [comment]
Hey @ChristianIvicevic, I agree that this should be improved, setting the state in a functional way sounds good especially for slow-paced games such as board games.

I think it's worth mentioning @Wenish's suggestion about creating an API similar to `vuex` for actions and mutations. He described the API briefly [here](https://github.com/Wenish/colyseusx/blob/8c238f2905583497426299079dbd6d80315e9d0d/src/room.ts#L18-L22), definitions [here](https://github.com/Wenish/colyseusx/blob/8c238f2905583497426299079dbd6d80315e9d0d/src/store/modules/counter.ts) (functionality isn't implemented)

I have mixed feelings about the functional part, though. The state is not immutable in Colyseus. 

> Currently it's possible to manipualte some variables of this.state that are part of the Schema class and not custom variables which is most likely super unintended.

That's definitely not intended! Thanks for letting me know!

**Comment by ChristianIvicevic** [comment]
> I have mixed feelings about the functional part, though. The state is not immutable in Colyseus.

This is basically something you have to form an opinion on yourself with regards to moving forward. Personally I like having immutable data as much as possible enforcing some standards and guidelines on how to perform certain actions. Besides various pros and cons the simplest pro that comes to mind is the following: having the state immutable (when attempting to directly access it) enforces developers to use some kind of `setState` method to update the state. This will provide the possibility to hook into every single update at a precise location instead of checking whether the state has been altered "somewhere".

As with many design decisions, this is something that will be opinionated and I can only chime into the discussion to share my experience with other use cases and scenarios such as the example with the `setState` behavior that can been seen in React.

**Comment by ChristianIvicevic** [comment]
> I think it's worth mentioning @Wenish's suggestion about creating an API similar to `vuex` for actions and mutations. He described the API briefly [here](https://github.com/Wenish/colyseusx/blob/8c238f2905583497426299079dbd6d80315e9d0d/src/room.ts#L18-L22), definitions [here](https://github.com/Wenish/colyseusx/blob/8c238f2905583497426299079dbd6d80315e9d0d/src/store/modules/counter.ts) (functionality isn't implemented)

This pretty much looks like Redux, but nearly every state management system at its core works the same. Nevertheless I'd like to leave a snippet from React for inspirational purposes which describes how state can be managed there with simple reducers as you can see here:

```typescript
const initialState = {count: 0};

function reducer(state, action) {
  switch (action.type) {
    case 'increment':
      return {count: state.count + 1};
    case 'decrement':
      return {count: state.count - 1};
    default:
      throw new Error();
  }
}

function Counter({initialState}) {
  const [state, dispatch] = useReducer(reducer, initialState);
  return (
    <>
      Count: {state.count}
      <button onClick={() => dispatch({type: 'increment'})}>+</button>
      <button onClick={() => dispatch({type: 'decrement'})}>-</button>
    </>
  );
}
```
More details about hooks (possibly for more inspiration) can be accessed via the [documentation](https://reactjs.org/docs/hooks-reference.html#usereducer).

**Comment by endel** [comment]
Closing as it seems out of scope at the moment
