### ISSUE TITLE
Bug: deltaTime in the SimulationCallback handler for Room.setSimulationInterval seems to be eroneously optional

### ISSUE THREAD

**Issue by ChristianIvicevic** [colyseus/colyseus#236]
Currently the `SimulationCallback` handler is declared as follows:
```typescript
export declare type SimulationCallback = (deltaTime?: number) => void;
```
Looking into the code of `@gamestdio/clock` there was no indication that the `deltaTime` is ever undefined. As of right now my handler I have set up via `Room.setSimulationInterval(this.onUpdate);` contains some boilerplate which looks like this:
```typescript
private readonly onUpdate = (deltaTime?: number) => {
    const dt = deltaTime !== undefined ? deltaTime : 0;

    // ...
};
```
I do assume it's unintended that the `SimulationCallback` handler has the `deltaTime` parameter optional which should be fixed.

**Comment by endel** [comment]
Thanks @ChristianIvicevic, just fixed this. This was really annoying when using `"strict": true` on `tsconfig.json`

**Comment by ChristianIvicevic** [comment]
And writing some shennanigans like `const dt = deltaTime || 0;` will cause the linter to fail as well if you have it too strict with boolean checks. The linter can be really annoying to work with sometimes :)
