### ISSUE TITLE
Update "ws" package to 7.0.0

### ISSUE THREAD

**Issue by amir-arad** [colyseus/colyseus#239]
## Steps to Reproduce
1. open server with constant state changes 
2. start load test (i used default bot with no actions)
3. kill load test with ctrl+C

## Your Environment
* Colyseus Version: 10.0.7
* Node.js Version: 10.15.3
* Operating System and version: windows 10

it is triggered from the room constructor task timeout:
```
send (project\node_modules\ws\lib\websocket.js:335)
15 (project\node_modules\colyseus\lib\Protocol.js:110)
applyPatches (project\node_modules\colyseus\lib\serializer\SchemaSerializer.js:31)
broadcastPatch (project\node_modules\colyseus\lib\Room.js:206)
_patchInterval.setInterval (project\node_modules\colyseus\lib\Room.js:93)
ontimeout (timers.js:436)
tryOnTimeout (timers.js:300)
listOnTimeout (timers.js:263)
processTimers (timers.js:223)
[ Timeout ] (Unknown Source:undefined)
init (inspector_async_hook.js:27)
emitInitNative (async_hooks.js:137)
emitInitScript (async_hooks.js:336)
initAsyncResource (timers.js:50)
Timeout (timers.js:82)
setInterval (timers.js:503)
setPatchRate (project\node_modules\colyseus\lib\Room.js:92)
Room (project\node_modules\colyseus\lib\Room.js:54)
```

**Comment by amir-arad** [comment]
after debugging, it seems like a behavior in `ws` 6 where the client would update its `readyState` when sending.
in 7.0.0 they changed that behavior see websockets/ws#1515
please update?

**Comment by endel** [comment]
I didn't know there was a version `7.0.0` available already, going to update soon, thanks for the heads up!
