### ISSUE TITLE
Is there a plan to support flutter ?

### ISSUE THREAD

**Issue by gabrieltong** [colyseus/colyseus#240]
I know colyseus is for game not app, but I really want to know if there is a plan to support flutter.

**Comment by endel** [comment]
Hi @gabrieltong, there are no plans to support Flutter. You are always welcome to make your own client. The dependencies you need to have a Colyseus client are:

- WebSocket client
- MsgPack encoder / decoder
- [@colyseus/schema](https://github.com/colyseus/schema) decoder
- The client code itself gluing it all together, you can take any of the official clients as a reference to implement your own

**Comment by gabrieltong** [comment]
@endel thanks man!
