### ISSUE TITLE
Add option to make schema type nullable

### ISSUE THREAD

**Issue by Mykybo** [colyseus/colyseus#243]
Unless I am missing something, this is not possible with the new schema. Would be great if we could mark attribute as nullable. 

Currently when you set null to state prop you get error like this: `Error: a 'number' was expected, but 'null'null was provided in Cell#value`

**Comment by endel** [comment]
Hi @Mykybo, the problem here is what should `null` be on C#, or C++? I believe not allowing them would be best to have the same decoder implementation across environments.

I'll suggest you use `0` or `-1` instead of `null` in that case.

**Comment by Mykybo** [comment]
> the problem here is what should null be on C#, or C++
I didn't think of that... well, C# has Nullable types and in C++ you could return null pointer I guess? Using -1 is what I ended up with but it's really not ideal when using js only.
