### ISSUE TITLE
Flutter (Dart) Client Support

### ISSUE THREAD

**Issue by johnveloper** [colyseus/colyseus#248]
[Flutter](https://flutter.dev) is a cross-platform mobile app framework, and it is actually fast enough to render even complex 2D games in constant 60 fps. I checked it myself and it positively surprised me, see this flutter game - [Spaceblast](https://github.com/spritewidget/spaceblast). to build apk and install on device, just connect your device and run `flutter build apk` then `flutter install` from root directory of the game.

I would love to see a Colyseus client for it. I can help building it but I don't even know where to start. What do you think?

**Comment by endel** [comment]
Hi @johnveloper, the clients are pretty simple besides the state deserialization. 

A new client would need basically a WebSocket connection and implement the Colyseus messaging protocol. The most challenging part is the (new) Schema decoder. The decoder has been implemented in many languages (C#, Haxe, TypeScript, Lua, C++) so you could take a look at them.

The Fossil Delta decoder part in the clients can be ignored, as it will be deprecated soon.

**Comment by johnveloper** [comment]
Hi @endel. The decoder has been implemented in Lua, does it mean you support Corona SDK games?

**Comment by endel** [comment]
Hi @johnveloper, the WebSocket implementation I'm using for LUA is very specific to the Defold Engine. Plus there are some small dependencies highly tied to Defold. It may not be too hard to have a CoronaSDK-compatible version running. If you need any help porting I can guide you through. Cheers!

**Comment by johnveloper** [comment]
I would love to implement it in Corona. It's much better than Flutter. Actually don't waste your time on Flutter... And yes, I need your help, I don't even know where to start :|

**Comment by boygiandi** [comment]
In need this, too. Colyseus for Dart

**Comment by kiaxseventh** [comment]
I have already used Colyseus in my last project (Unity engine)
colyseus is very lovely

but now my new project is on Flutter Framwork and now i needed colyseus again

dear @endel 
please provide a program or guide to produce colyseus flutter client

**Comment by soile1991** [comment]
I have also used Colyseus in Unity and it's very useful. The project I work now is on Flutter so Colyseus for Dart would be perfect.

**Comment by endel** [comment]
Please support me on Patreon so I can afford to maintain another client 😂 😅

**Comment by NebiSarigul** [comment]
I need this too. ❤

**Comment by Marty** [comment]
Flutter is taking off and I think colyseus would benefit from supporting it.
