### ISSUE TITLE
Custom room id cannot use to join room

### ISSUE THREAD

**Issue by ccfiel** [colyseus/colyseus#250]
I have a class Table which generate my own custom room id
```
export class Table extends Room {
  async onInit (options: any) {
    let code = generateRoomCode(5);
    this.roomId = code;
  }

  requestJoin (options: any, isNew: boolean) {
    return (options.create)
        ? (options.create && isNew)
        : this.clients.length > 0;
  }

  onJoin (client: Client, options: any) {}
  onMessage (client: Client, message: any) {}
  onLeave (client: Client, consented: boolean) {}
  onDispose() {}
}
```

when I used ```let room = client.join("95714");``` 
in the client side using the custom room id an error occurred 
```colyseus.js: server error: no available handler for "95714"```

but when I remove the onInit() code and use the existing room id generated. client.join using room id works.
Is this a bug? or I miss something?

**Comment by endel** [comment]
@ccfiel custom room ids are currently limited to 9-char-long strings: https://github.com/colyseus/colyseus/blob/7f2f9f24ec84b346cb1c085ea33cf89db625901c/src/index.ts#L26

**Comment by ccfiel** [comment]
@endel so what you mean when I generate my custom room id it should be 9 character long?

**Comment by endel** [comment]
hi @ccfiel, exactly, that's the current limitation of room ids

**Comment by ccfiel** [comment]
@endel thanks!

**Comment by VictorAny** [comment]
Is there a reason this is the case? I persist/pull room ids from a database and this limitation is honestly troubling since we need to add random strings to our room ids to get them to be 9 characters long. Also means theres an upper bound on the total possible number of rooms that could ever be created (9 billion)

**Comment by endel** [comment]
Hi @VictorAny, this should not be a strict limitation anymore - if you override the room id's, you should be able to use whatever you like for them. You just need to make sure they are unique
