### ISSUE TITLE
Cannot generate haxe Schema

### ISSUE THREAD

**Issue by ccfiel** [colyseus/colyseus#251]
I tried to generate schema using
```
schema-codegen schemas/PusoyPlayer.ts --output  /home/chris/Projects/pusoy-server/ --hx
```
and 
```
schema-codegen schemas/PusoyPlayer.ts --output  /home/chris/Projects/pusoy-server/ --haxe
```
but  error occured
```
You must provide a valid generator as argument, such as: --csharp, --haxe or --cpp
```

but when I tried other platform like ts, js, java and csharp it works
only haxe do not work.

Any idea why?

**Comment by endel** [comment]
hi @ccfiel, sorry, `hx` has been renamed to `haxe` recently but some renaming was still missing. The latest version of `@colyseus/schema` (0.4.44) now fixes this.

**Comment by ccfiel** [comment]
@endel how can update my schema-codegen to use version 0.4.44?

**Comment by endel** [comment]
@ccfiel you can remove your `package-lock.json` file and run npm install again 🙏

**Comment by ccfiel** [comment]
@endel thanks! for reference need to delete package-lock.json and delete node_modules to take effect :)
