### ISSUE TITLE
TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by GDdark** [colyseus/colyseus#252]
Always happen!!

![image](https://user-images.githubusercontent.com/15982894/63183017-920d3300-c086-11e9-94bc-89d68393b1d8.png)

* Colyseus Version: 0.10.9
* Node.js Version: v10.15.1
* Operating System and version: Linux

**Comment by endel** [comment]
That's strange indeed, seems like the `sessionId` was not defined for the client, I've never experienced this issue myself

**Comment by endel** [comment]
Hey @GDdark, can you try upgrading to version `0.11` and see if this still happens for you? https://docs.colyseus.io/migrating/0.11/

**Comment by GDdark** [comment]
Okay，I would try！thanks

**Comment by GDdark** [comment]
The error is not happening again when I upgrade the version!!
This issue is done.  Thank you!
