### ISSUE TITLE
Matchmaking -> Locked the room

### ISSUE THREAD

**Issue by Yinmany** [colyseus/colyseus#256]
Hey~
current:
Matchmaking -> Locked the room
Is that right?

**Comment by endel** [comment]
What is the question?

**Comment by Yinmany** [comment]
After starting the game, I want to lock the room so that no players can match into the room.

**Comment by Yinmany** [comment]
After I lock the room, players will still match in

**Comment by endel** [comment]
I see, thanks for letting me know @Yinmany, explicit locks have just been fixed on `0.11.3`

I haven't updated the test-suite on version 0.11, gotta do that soon to ensure features aren't broken. Cheers!
