### ISSUE TITLE
Matchmaking is broken in v0.11.x if you set `options.server` but not `options.express`

### ISSUE THREAD

**Issue by rnd256** [colyseus/colyseus#258]
I've been using Colyseus with Koa (https://github.com/koajs/koa), and it looks like that's not possible anymore in Colyseus v0.11.x. Matchmaking is broken in v0.11.x if you set `options.server` but not `options.express` when constructing or attaching the `Server`.

```typescript
const app = new Koa();
// configure app

const server = new Server();
// define room

const httpServer = app.listen(PORT);
gameServer.attach({
  server: httpServer,
});
```

If it's expected behaviour that this no longer works, then I think the `Server` constructor and `attach()` methods should throw an error if that configuration of `ServerOptions` is provided.

Additionally, if you pass empty options to the `Server` constructor, then later pass both `options.server` and `options.express` to `attach()`, the express routes never get set up (they are only called in the `Server` constructor).

```typescript
const app = express();
// configure app

const server = new Server();
const httpServer = app.listen(PORT);
gameServer.attach({
  server: httpServer,
  express: app,
});
```

https://github.com/colyseus/colyseus/blob/f3fd41205c13873efda612d177af60e6e3345445/src/Server.ts#L64

**Comment by endel** [comment]
Hi @rnd256, thanks for reporting. Have you managed to use it along with Koa?

> Additionally, if you pass empty options to the Server constructor, then later pass both options.server and options.express to attach(), the express routes never get set up (they are only called in the Server constructor).

I'm going to fix this soon!

I've searched quite a lot, and haven't found a way to bind routes to plain `http` module, without relying on a specific framework (express / koa). Do you have an idea if that's possible? It wasn't on my plans to allow passing `express`, `koa`, etc as options to bind the routes correctly, but if that's the only way, it's what I'm going to do for now... 😨 

- The matchmaking routes for express are defined here: https://github.com/colyseus/colyseus/blob/master/src/Server.ts#L120-L142
- Matchmaking routes without express are defined here (if you don't provide a `server`): https://github.com/colyseus/colyseus/blob/master/src/Server.ts#L152-L209

**Comment by rnd256** [comment]
Hi @endel, thanks for the fast response! In the end, I wasn't able to get v0.11 working with Koa.

I searched as well and didn't find a method of binding routes without relying on a specific server framework. To avoid having to write a special case for every different server framework, you could write custom logic for the most popular one(s) (express for sure, and maybe Koa), then allow users to cover any other frameworks by passing in their own methods, to be called by Colyseus.

**Comment by endel** [comment]
I see, I just checked that socket.io does a trick with plain `http` server to allow this: https://github.com/socketio/engine.io/blob/ad844f4b32a15f475f227a2b0277d6df2d063541/lib/server.js#L453-L473

I'm going to do the same

**Comment by rnd256** [comment]
Actually, for covering the long-tail of frameworks, instead of passing a method to be called by Colyseus, it's probably better if Colyseus exposes a method(s) that calls to `this.processMatchmakeRequest`/`this.matchMaker.query`, and returns the json response or error, to let the user create routes for them as needed.

**Comment by rnd256** [comment]
Oh, the socket.io trick works!

**Comment by endel** [comment]
can you try version `0.11.5` out @rnd256?

here's a usage example with Koa: https://github.com/colyseus/colyseus/blob/master/usage/ServerKoa.ts

cheers!
