### ISSUE TITLE
room state or patch data may not be successfully sent to client

### ISSUE THREAD

**Issue by RonnyHou** [colyseus/colyseus#261]
Your issue may already be reported!
Please search on the [issue tracker](../) before creating one.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Colyseus Version:
* Node.js Version:
* Operating System and version:
* Link to your project:

**Comment by RonnyHou** [comment]
Sometimes I could not get the room state when connected to server. I suspect that room state transmission is not ok. As patch data is only sent when state has changed, will it be possible that, in this case, client will lost synchronization with server?

**Comment by endel** [comment]
Hi @RonnyHou, can you share some code on what you're trying to achieve? Maybe your callbacks for getting state updates are misplaced somehow? Cheers

**Comment by damian-pastorini** [comment]
hi @RonnyHou , just to be clear:
`As patch data is only sent when state has changed` > this is the way it works, the data is only sent if it changes, client would never lost sync unless you manually change it in the client instead instead in the server.

**Comment by RonnyHou** [comment]
hi @endel , I'am using 0.10.9, codes below:

room.onStateChange.addOnce(state => {
    state.onChange = changes => {
       //do my stuff
    }
    state.players.onAdd = (player, key) =>{
       //show players
    }
})

**Comment by RonnyHou** [comment]
hi @damian-pastorini , I know is reasonable that patch data is only sent when changed. But what if a patch data is not successfully sent to some of the clients ? Should there be a retransimisson mechanism ?

**Comment by damian-pastorini** [comment]
hi @RonnyHou , I think you could be running into the async case where the player changes are arriving the client before the player is actually added, to confirm this you can just put add a validation inside the onChange to check if the player exists.

**Comment by RonnyHou** [comment]
thx @damian-pastorini , but I got neither player changes nor player added. Anyway I'll try to confirm what really goes wrong. Since this happens occasionally, it takes time for a result.

**Comment by endel** [comment]
hey @RonnyHou, colyseus uses WebSockets, the delivery of packets is ensured by the protocol. if packets are lost they're going to be re-sent to ensure clients receive them in order.

maybe you need to do something like this:

```javascript
```

**Comment by RonnyHou** [comment]
not a problem of colyseus
