### ISSUE TITLE
Scalability problems

### ISSUE THREAD

**Issue by amit-gshe** [colyseus/colyseus#271]
I have encontered two issues when I use this awesome project.

1. When attached an existing http server, its port information is undefined. There is no chance to initialize this property.
2. When gracefullyShutdown, await is needed to unregister node. Now the process was killed before the node has been unregistered.

**Comment by endel** [comment]
Hi @amit-gshe, thanks for reporting! I've made some changes to the `.attach()` and how the `registerNode()` / `unregisterNode()` are called to detect the current port.

It's published on `colyseus@0.11.15`. Let me know if that works for you! Cheers

**Comment by amit-gshe** [comment]
Many thanks! It works now.
