### ISSUE TITLE
Custom roomId does not work in version 11

### ISSUE THREAD

**Issue by MateusMendesSantana** [colyseus/colyseus#273]
## Steps to Reproduce

Setting onCreate event:
```
onCreate(options: any) {
  this.roomId = "5d7f7dbb7fa1810ad880b62c";
}
```
## Context

On matchmaker.ts, roomId is set to room.listing before id change in onCreate:
```
room.listing = this.driver.createInstance({
  name: roomName,
  processId: this.processId,
  roomId: room.roomId,
  ...registeredHandler.getFilterOptions(clientOptions),
});

if (room.onCreate) {
  try {
    await room.onCreate(merge({}, clientOptions, registeredHandler.options));

  } catch (e) {
    debugAndPrintError(e);
    throw new MatchMakeError(e.message, Protocol.ERR_MATCHMAKE_UNHANDLED);
  }
}
```
When running remoteRoomCall try to find room by old id:
```
public async remoteRoomCall<R= any>(
    roomId: string,
    method: string,
    args?: any[],
    rejectionTimeout = REMOTE_ROOM_SHORT_TIMEOUT,
  ): Promise<RemoteRoomResponse<R>> {
    const room = this.localRooms[roomId];

    if (!room) {
.........
```
Generating the following error:
> remote room (q1rhxOo62) timed out, requesting "_reserveSeat with args ["eOd1Lf2uT",{"id":"5d7f7dbb7fa1810ad880b62c","create":true,"token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZDM5ZWZjODFlMzA5M2UxYzRlMDJjMjkiLCJpYXQiOjE1NzAyOTM2NjF9.B8cAJTlH9YMnUcecIOYwjoMvBFYBsPBp7ldMqiyZ_fQ"}]"

## Environment

* Colyseus Version: ^0.11.0-alpha.4
* Node.js Version: v10.15.3
* Operating System and version: win10
* Link to your project: no link

**Comment by endel** [comment]
Thanks for reporting @MateusMendesSantana, this has been fixed on `colyseus@0.11.16`. Cheers!
