### ISSUE TITLE
Discovery from docker issue

### ISSUE THREAD

**Issue by amit-gshe** [colyseus/colyseus#274]
Now the `ip.v4()` get an ip of the container which is assigned by `docker_gwbridge`. this ip can not be accessed by any other container like colyseus proxy. So it's may not be possible to scale in docker swarm cluster.

**Comment by abhang-atish** [comment]
Try running this command from any shell based module `/sbin/ip route|awk '/default/ { print $3 }'`

**Comment by etherny** [comment]
Perhapse you can use docker socket (docker.sock) to listen published labels in the swarm. Like Traefik.
You can add labels to colyseus swarm instances and with a special colyseus proxy with auto registration of nodes base on published docker labels.
When a new node is created it publish it IP and some other container informations, with that you can add new entries in the proxy.

**Comment by amit-gshe** [comment]
One workaround in docker is registering the node to redis with container's hostname `os.hostname()` which is default the container id. The docker handles the dns query to specifc container id and convert it to an internal ip which can be accessed between containers. So the colyseus proxy can access the specific colyseus instance by its hostname(container id default).

But one limitation is that in non-docker environment the hostname could not be accessed by ohter LAN instances.

**Comment by endel** [comment]
This is a quote from Jorn in the Discord channel:

> You can try to create a user defined bridge, it has more features than the default bridge. Or use an overlay network. It used to be done by linking containers with --link but that is deprecated
Further reading: https://docs.docker.com/network/bridge/ and https://docs.docker.com/network/overlay/

> Docker swarm typically uses an overlay network
Kubernetes typically also uses an overlay network (though not strictly required as it has a pluggable networking model)

**Comment by amit-gshe** [comment]
close as it is more a deploy problem and this lib have not much to do.

**Comment by zgz682000** [comment]
@amit-gshe do you any workaround about this issue now? I have got the save problem

**Comment by zx1986** [comment]
I got this issue too ....

**Comment by endel** [comment]
Hi @zx1986, this PR https://github.com/colyseus/colyseus/pull/327 introduced the environment variables `SELF_HOSTNAME` and `SELF_PORT`, which you can use to override the default `ip.v4()`
