### ISSUE TITLE
MySQL Driver

### ISSUE THREAD

**Issue by oyed** [colyseus/colyseus#275]
## Context
Given the newer Matchmaking system, currently using a `local` or `mongoose` (MongoDB) driver, this presents problems when a `local` driver is not applicable to scalable solutions, and the singular MongoDB solution presents more persistent-storage operations management (Especially at larger scales)

Since Redis has a lack of querying support, I propose a MySQL Driver for the Colyseus Gameserver.

I'll start work on this in a week or so - at the present, it won't support transactions (As the MongoDB supports, but is not currently used by Colyseus), however since transactional queries _are_ supported by MySQL, this is still a potential future feature of the driver.

For now, the driver will serve a (for now, personal vendatta) against having to manage 3 different operational database structures for the sake of scalability (Redis for presence, MySQL for persistent storage, MongoDB for Room discovery)

This issue will track my progress.

**Comment by oyed** [comment]
Putting this up-for-grabs for the time being - had too much going on with another product launch
Will come back around to this if no-one picks it up when I'm more available :)

**Comment by developgiiker** [comment]
hi, after half a year, is there any update?

I have already try TypeORM to finish my MySQL driver, but a not graceful thing is that, a lot of database driver is returning promise. So after I new a MysqlDriver, the mysql is connecting, the colyseus will call define Room, and inside that it would call the find() function and make exception.

i think maybe you start the framework by using moongoose, and moongoose's one feature is that you no need to wait for connection and you could call the model binding? is that any solution for this?

**Comment by vitalyrotari** [comment]
hi, I made a SQL driver based on Sequelize ORM, is not tested well, but is seems to work. I will send a pull request a bit latter ;)

**Comment by vitalyrotari** [comment]
Hey, check this out https://github.com/colyseus/colyseus/pull/402

**Comment by endel** [comment]
Hi guys, closing this as matchmaking drivers have been extracted from the core to allow other packages to implement custom drivers. 

`@colyseus/redis-driver` is the current recommendation and is the one going to receive further updates
