### ISSUE TITLE
Bug: metadata.clients is not right

### ISSUE THREAD

**Issue by GDdark** [colyseus/colyseus#279]
When I fetch the metadata from the server.
The room has existed for a long time and there is only one player in the room.
But metadata.clients shows -2.
I think it's a bug.

![image](https://user-images.githubusercontent.com/15982894/67961592-de542200-fc36-11e9-96a7-b232661c8367.png)

Colyseus version is 0.11.20  and using MongoDB

**Comment by endel** [comment]
Thanks for reporting @GDdark, I've also noticed this on a game we have running on production, I'm rewriting the whole test suite right now trying to figure out what's going wrong

**Comment by endel** [comment]
(Have you shared your project in the showcase of the forums or Discord channel? I'm curious what you've been working on! Cheers)

**Comment by GDdark** [comment]
Thanks.
It is a company project and I have no right to open it to the public without permission.
Sorry about that.

Colyseus is a good game framework. 
Hope that it can develop better and better.

**Comment by endel** [comment]
Closing as this doesn't seem to happen anymore!
