### ISSUE TITLE
ArraySchema<number> issue

### ISSUE THREAD

**Issue by udamir** [colyseus/colyseus#281]
I had a schema "A" with ArraySchema<number> "items". Then I push to array "items" values: 1, 2, 3. 
On Client side A.onChange(value, key) triggers on every update and I got the following values in items:
```
A.items: [1]
A.items: [undefined, 2]
A.items: [undefined, 2, 3]
```
[02-state-handler.zip](https://github.com/colyseus/colyseus/files/3811489/02-state-handler.zip)

You can check it on "02-state-handler" example by adding a few line of code:

Add ArraySchema<number> in Player class:
```
    @type(["number"])
    moves = new ArraySchema<number>();
```

In state class add method:
```
    addItem(id, item) {
        this.players[id].moves.push(item);
    }
```
in StateHandlerRoom class call method on every message:
```
    onMessage (client, data) {
        console.log("StateHandlerRoom received message from", client.sessionId, ":", data);
        this.state.movePlayer(client.sessionId, data);
        this.state.addItem(client.sessionId, data.x || data.y );
    }
```

On client-side just add one line in "room.state.players.onChange":
```
console.log(player.moves)
```

**Comment by endel** [comment]
Hi @udamir,

Thanks for reporting. This turned out to be a bug on @colyseus/schema when decoding an arrays. 😨 (https://github.com/colyseus/schema/commit/2f34c0b19390dce33101569675a51b36347336e4)

Please make sure you're using the latest versions locally (remove your `node_modules` + `package-lock.json` and install them again)

For the dist `colyseus.js` file you can use this one which has the latest `@colyseus/schema` embedded on it: https://rawcdn.githack.com/colyseus/colyseus.js/29d901794ab1c7bc85d46d664cfb087a8186354b/dist/colyseus.js

Let me know if that works for you. Cheers!

**Comment by udamir** [comment]
Hi @endel,

thanks for fast fix! Example code now works fine, but my code that worked yesterday now is not working(

I get error on client-side:
```
Uncaught TypeError: b.clone is not a function
    at colyseus.js:1
    at t.e.decode (colyseus.js:1)
    at colyseus.js:1
    at t.e.decode (colyseus.js:1)
    at e.patch (colyseus.js:1)
    at e.patch (colyseus.js:1)
    at e.onMessageCallback (colyseus.js:1)
    at t.value (colyseus.js:1)
(anonymous) @ colyseus.js:1
e.decode @ colyseus.js:1
(anonymous) @ colyseus.js:1
e.decode @ colyseus.js:1
e.patch @ colyseus.js:1
e.patch @ colyseus.js:1
e.onMessageCallback @ colyseus.js:1
value @ colyseus.js:1 
```

I tried with `colyseus.js` from master and from you link 

> For the dist colyseus.js file you can use this one which has the latest @colyseus/schema embedded on it:
https://rawcdn.githack.com/colyseus/colyseus.js/29d901794ab1c7bc85d46d664cfb087a8186354b/dist/colyseus.js

Can you check?

**Comment by endel** [comment]
Sounds bad :( You mind sharing what your existing code looks like? The `@colyseus/schema` test cases are not covering it, since the test-suite is passing on master branch.

Thanks!

**Comment by endel** [comment]
Also, please make sure to upgrade `colyseus` to latest version if you haven't yet!

**Comment by udamir** [comment]
I have sent you my code to your email.

**Comment by udamir** [comment]
Thank you for response, now ArraySchema works correctly! 

But I found one more issue with synchronisation of MapSchema if key is number type. For example, when I update MapSchema item with key 4 (`objects[4]`) on server side, on client side triggers `objects.onChange(obj, key)` with `obj = objects[3]`. 

When I change key to string (`objects["4"]`) everything works correctly.

**Comment by stonekase** [comment]
hi @endel ,

I am also experiencing something similar to the arrayschema. but for me, i try to loop through it and for some reason it appends the same three added empty slots.the arraySchema Length() works correctly on the server side. I have not tested if this is the case with the client,please see below the console print of the issue. if it doesnt patch with the said additions then it is not a deal breaker for me but it is good to point it out.Please note that my arraySchema is of custom type.

##console print of the arraySchema(@type([ Card ]) deck = new ArraySchema<Card>();)
Card :: type: star ,number: 5
Card :: type: cross ,number: 1
Card :: type: cross ,number: 13
Card :: type: cross ,number: 7
Card :: type: triangle ,number: 3
Card :: type: cross ,number: 14
Card :: type: triangle ,number: 1
Card :: type: whot ,number: 20
Card :: type: cross ,number: 5
Card :: type: triangle ,number: 11
Card :: type: triangle ,number: 7
Card :: type: cross ,number: 2
Card :: type: square ,number: 5
Card :: type: star ,number: 7
Card :: type: circle ,number: 3
Card :: type: circle ,number: 7
Card :: type: triangle ,number: 13
Card :: type: square ,number: 10
Card :: type: whot ,number: 20
Card :: type: triangle ,number: 5
Card :: type: triangle ,number: 12
Card :: type: star ,number: 6
Card :: type: square ,number: 1
Card :: type: star ,number: 4
Card :: type: whot ,number: 20
Card :: type: triangle ,number: 10
Card :: type: square ,number: 7
Card :: type: circle ,number: 10
Card :: type: circle ,number: 1
Card :: type: circle ,number: 12
Card :: type: square ,number: 14
Card :: type: circle ,number: 8
Card :: type: triangle ,number: 14
Card :: type: whot ,number: 20
Card :: type: circle ,number: 4
Card :: type: triangle ,number: 8
Card :: type: triangle ,number: 4
Card :: type: triangle ,number: 2
Card :: type: cross ,number: 3
Card :: type: circle ,number: 13
Card :: type: star ,number: 8
Card :: type: star ,number: 1
Card :: type: circle ,number: 11
Card :: type: cross ,number: 10
Card :: type: square ,number: 13
Card :: type: whot ,number: 20
Card :: type: star ,number: 2
Card :: type: square ,number: 2
Card :: type: cross ,number: 11
Card :: type: square ,number: 3
Card :: type: circle ,number: 5
Card :: type: square ,number: 11
Card :: type: circle ,number: 2
Card :: type: circle ,number: 14

**Card :: type: undefined ,number: undefined
Card :: type: undefined ,number: undefined
Card :: type: undefined ,number: undefined
Card :: type: undefined ,number: undefined**
Size of Deck :: 54

##Custom Schema:
export class Card extends Schema{
    @type("number") cardnumber!: number; 
    @type("string") type!: string; 
    @type("number") grade!: number;
    constructor(cardnumber: number,type: string,grade: number){
        super();
        this.cardnumber = cardnumber;
        this.type = type;
        this.grade = grade;
    }
}

**Comment by endel** [comment]
hi @stonekase, can you confirm you're using the latest version of `@colyseus/schema` on both client-side and server-side?  (check `package-lock.json`, it should be version `@colyseus/schema@0.5.5`)

**Comment by stonekase** [comment]
@endel  

 "@colyseus/schema": {
      "version": "0.5.5",
      "resolved": "https://registry.npmjs.org/@colyseus/schema/-/schema-0.5.5.tgz",
      "integrity": "sha512-p2dY9jnzsXPFpOyhd0Sq0zDbPKC30cxIEbZrFirTXzNnxslfvxijn1PzFL94VX9D25ydw4fQZ5QH17f4yKHGnA=="
    },

**Comment by endel** [comment]
I'm going to close this as it seems to be fixed on the latest versions. Feel free to re-open if you still have problems after upgrading (`rm -R node_modules package-lock.json && npm install`)
