### ISSUE TITLE
Able to join private room with JoinOrCreate

### ISSUE THREAD

**Issue by arslan-22** [colyseus/colyseus#282]
I setted the room to private in OnJoin method 
```
onJoin (client: Client, options: any)
{
    this.setPrivate();
}
```

when I call JoinOrCreate I still able to join that room
`await client.JoinOrCreate<State>("Room", options);`

when I call for GetAvailableRooms I get 0 rooms before calling JoinOrCreate
`client.GetAvailableRooms<RoomAvailable>("Room");`

am I doing something wrong? I want to make a room private if some conditions meet and other players can only join if they have roomId using JoinById.

**Comment by endel** [comment]
Hi @arslan-22, can you check again on the version `colyseus@0.11.21`?

I've been rewriting the test suite recently and found this too, it should be fixed now. (forgot to publish with latest changes after re-writing the tests)

**Comment by arslan-22** [comment]
Hi @endel thanks for the fast response, after updating to `colyseus@0.11.21` getting error here

```
const gameServer = new Server({
  server,
  express: app
});
```

TSError: ⨯ Unable to compile TypeScript:
index.ts:28:3 - error TS2345: Argument of type '{ server: Server; express: Express; }' is not assignable to parameter of type 'ServerOptions'.
  Object literal may only specify known properties, and 'express' does not exist in type 'ServerOptions'.

28   express: app
     ~~~~~~~~~~~~

**Comment by endel** [comment]
Oops, thanks for letting me know @arslan-22, the `express` option is going to be removed on next version, I've rolled back this now on `0.11.22` to allow you to still pass it (even though it has no real effect)

I'll update the docs soon to remove the `express` option which is no longer necessary

Please let me know if you find any other issues!

**Comment by arslan-22** [comment]
yup, removed express argument working fine now, private rooms are working too, thanks :)
