### ISSUE TITLE
allowReconnection: provide API to cancel reconnection other than a timeout

### ISSUE THREAD

**Issue by endel** [colyseus/colyseus#288]
I have the use-case where re-connection is going to be disabled by some game rules, so being based only by a timeout is not effective in this case.

e.g. disable reconnection after 2 turns in a turn-based game.

**Something like this:**

```typescript
const reconnectionToken = this.allowReconnection(client);
await reconnectionToken.resolve();

// later during game logic:
reconnectionToken.cancel();
```

**Comment by grant1842** [comment]
Awesome thanks! Much appreciated
