### ISSUE TITLE
SchemaSerializer crash on primitive arrays

### ISSUE THREAD

**Issue by Chnapy** [colyseus/colyseus#291]
Hi :wave: :wave: 

I tried to set a state to my room, then I got this error:
```
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at SchemaSerializer.hasFilter (C:\...\node_modules\colyseus\lib\serializer\SchemaSerializer.js:60:40)
    at SchemaSerializer.hasFilter (C:\...\node_modules\colyseus\lib\serializer\SchemaSerializer.js:76:34)
    at SchemaSerializer.reset (C:\...\node_modules\colyseus\lib\serializer\SchemaSerializer.js:16:40)
    at MyRoom.setState (C:\...\node_modules\colyseus\lib\Room.js:109:26)
    at MyRoom.onCreate (c:\...\src\MyRoom.ts:10:5)
```

My state is structured like that:
```typescript
export class BattleRoomState extends Schema {

    @type(MapInfos)
    mapInfos!: MapInfos;

    @type(['string'])
    characterTypes!: ArraySchema<string>;
    
    @type(['string'])
    spellTypes!: ArraySchema<string>;
    
    @type(BattleSnapshot)
    battleSnapshot!: BattleSnapshot;
}
```
I was careful to always put the correct `@type` and use `ArraySchema` for each array (I don't have maps).

With some investigations I found what I think the cause of the bug, it's in `serializer/SchemaSerializer.js`, on `hasFilter`. The crash occurs when this function is called with an undefined `schema`. I found that this function is called with an undefined value here:
```typescript
else if (Array.isArray(schema[fieldName])) {
                const childSchema = schema[fieldName][0]._schema;
                const childFilters = schema[fieldName][0]._filters;
                hasFilter = this.hasFilter(childSchema, childFilters);
            }
```
In my case the error occurs on my `characterTypes` field. It is a string array, so each child doesn't have any `_schema` field.
There is I think 2 issues in this block of code:
- An ArraySchema cannot be empty, because its first value is taken to check filters, it's a cause of app crash;
- An array child needs to be a Schema, it cannot be a primitive value since it needs to have a `_schema` field;

My environment
- colyseus: 0.11.26
- node: 10.16.2
I generated my project with [create-colyseus-app](https://github.com/colyseus/create-colyseus-app/tree/typescript).

**Comment by endel** [comment]
Thanks for reporting @Chnapy, this has been fixed already in the `0.12.x` branch - and I've just applied it back to the version `0.11.27`. Let me know if you find any other issue! Cheers
