### ISSUE TITLE
Help from 0.10.9 to version 0.11.0

### ISSUE THREAD

**Issue by Maeggi** [colyseus/colyseus#294]
Node: 12.14.0
Colyseus: 0.11.0

Old Code: [PasteBin](https://pastebin.com/qgEdN3YU)
New Code: [PasteBin](https://pastebin.com/PMaW0H8L)

Error: Uncaught (in promise) Error: registeredHandler.klass is not a constructor

Can somebody help me with it?

**Comment by endel** [comment]
Hi @Maeggi, this error is from the server-side. How're you defining rooms? (`gameServer.define()`)

**Comment by Maeggi** [comment]
hi @endel Thank You... I found the Error in my Room file.
