### ISSUE TITLE
How to avoid process exit

### ISSUE THREAD

**Issue by dengzhaofun** [colyseus/colyseus#298]
colyseus will terminate the program as soon as an internal exception occurs? How can I handle the exception by myself to avoid the process exiting because the process also has an http service. The production environment should also try to avoid the exception directly exiting the process

**Comment by endel** [comment]
Hi @dengzhaofun, 

Internally, Colyseus is listening for [`"uncaughtException"`](https://nodejs.org/api/process.html#process_event_uncaughtexception) and gracefully shutting down the process in case it happens.

You can opt-out of the default graceful shutdown by using:

```typescript
import { Server } from "colyseus";

const gameServer = new Server({
    gracefullyShutdown: false,
});
```

You'd need to call `gameServer.gracefullyShutdown()` manually whenever your process goes down though.
