### ISSUE TITLE
@filter The client's onChangeState state data is disordered

### ISSUE THREAD

**Issue by dengzhaofun** [colyseus/colyseus#303]
There are four players in the room, and the player has a hand, and the hand is not visible to others.Adding the @filter modifier will cause the client's state data to be randomly confused.
```
export class GameRoomState<PlayerType extends Player = any> extends Schema {

  @type([Player])
  players = new ArraySchema<PlayerType>();
}
```

```
export class Player extends Schema {
  constructor(user: User, sessionId: string) {
    super()
    this.user = user;
    this.uid = user.id;
    this.sessionId = sessionId;
  }
  @type('string')
  sessionId: string;

  @type('number')
  uid: number;

  @type("number")
  index: number;

  @filter(function(
    this: Player,
    client: Client,
  ) {
    return this.sessionId === client.sessionId;
  })
  @type(["uint16"])
  cards = new ArraySchema<number>();
}
```

The number of players per client will be different, and the array data of players cannot be synchronized correctly

**Comment by endel** [comment]
Hi @dengzhaofun, using `@filter()` on arrays and maps is not supported at the moment. It is planned for a future version, though.

![Screenshot 2020-01-29 at 08 59 17](https://user-images.githubusercontent.com/130494/73357354-f9a4ec80-427a-11ea-83e5-b4ea32e4b330.png)

What I have been doing for a card game is having a structure like this:

```typescript
class Player extends Schema {
  @type([Card])
  cards = new ArraySchema<Card>();
}

//...
class Card extends Schema {
  @filter(function(this: Card, client, value, root) {
    return root.players[client.sessionId].cards.indexOf(this) !== -1;
  })
  @type("number")
  number: number;
}
```

**Comment by dengzhaofun** [comment]
Thanks for your timely feedback.
