### ISSUE TITLE
Room design related doubts

### ISSUE THREAD

**Issue by dengzhaofun** [colyseus/colyseus#307]
Hello, in the case of the node cluster distributed architecture: 
1. Are players in the same room in the same process? 
2. If one of the processes exits abnormally, can matchMaker.gracefullyShutdown () clear this? Process all room related data. 
3. Do players in the same room send or broadcast using redis sub / pub?

**Comment by endel** [comment]
Hi @dengzhaofun, 

Clustering is not supported on Colyseus, it's recommended to use PM2 in 'fork' mode - please give it a read to the Scalability docs: https://docs.colyseus.io/scalability/

I need to make it more clear in the docs, but basically you'd have multiple colyseus processes for holding game rooms, and a proxy to forward clients to the right process.

By using the proxy, players in the same room are all communicating in the same process. Redis is only used for `this.presence` calls, if you have any.

Let me know if you have any other questions
