### ISSUE TITLE
Any colyseus benchmarks? - web framework currently used?

### ISSUE THREAD

**Issue by onelsonic** [colyseus/colyseus#311]
onelsonic 7 days ago

Hi everyone.
Colyseus looks pretty neat.

Can anyone confirm, @endel maybe? what is the current web framework used by colyseus?
Is it express :
https://github.com/expressjs/express
or uWebSockets :
https://github.com/uNetworking/uWebSockets
or something else?

And are there any benchmarks available for colyseus using wrk ?
https://github.com/wg/wrk

This is to evaluate the performances of colyseus.

Here is a list of tested web framework :
https://github.com/the-benchmarker/web-frameworks

Thank you
and have a nice day

**Comment by endel** [comment]
Hi @onelsonic, Colyseus is not a "web framework" - it uses [`ws`](http://npmjs.com/package/ws) for WebSockets, and you can use Express or other web frameworks along with it. 

I have made some benchmarks for my specific needs, but everyone's needs are slightly different. Making a "hello world" benchmark is a disservice for the community, as it leads to inaccurate decisions (holding 8k+ WebSocket connections for a "hello world", and only 150 in a real scenario, for example)

There are a few things that could be benchmarked, though, such as:
- The time it takes to join-or-create game rooms VS number of rooms active
- Number of clients a single room can hold, while not having a game-loop.
- Number of clients a single room can hold, while having a CPU-intensive game-loop in the server
- More...?

**Comment by onelsonic** [comment]
Thank you @endel 👍 . So it is not "HTTP request" based, that even better but hard to benchmark... I see.
We have JS WebSockets along with HTTP requests.
There is the flexibility to use the web frameworks of our choice, perfect.

Have you tested [socket.io](https://www.npmjs.com/package/socket.io) instead of ws or [websocket](https://www.npmjs.com/package/websocket)

Then for the WebSockets part does Colyseus is tight to JS necessarily ?
Or there is a flexibility on the WebSockets side as well?
I found a WebSockets framework benchmark process here 👍 https://github.com/hashrocket/websocket-shootout/blob/master/results/round-02.md

**Comment by ClosetMonkey** [comment]
Benchmarking should be easy as long as you don't dive so far into it that your basically creating an emulator withing the service. All you need to do is make a module that will honestly represent network flows (can use mock data or even random bits), CPU usage can which be anything including long while loops, memory utilization which could be filling and draining buffers of random data, and same with filesystem utilization. Just remember "a game" can represent many different things, so getting too locked of an idea of accurately simulating such a thing will actually lock you into something that will only represent a limited use cases. That's not necessary when all that is truly important is an accurate representation of resource consumption and utilization. Call loops of varying depths at variable intervals, write/read variable random bits from the network at variable intervals, and write/read variable random bits to memory and filesystem at variable intervals. It's being able to define these amounts that will allow honest benchmarks to be tailored to specific cases.

**Comment by ClosetMonkey** [comment]
General purpose benchmarks can use such a system by first monitoring a real life game to see it's actual demands, and tuning the above to accurately copy it's demands. Such a benchmark can then be distributed without having to distribute the actual game, and can also be used for testing purposes etc.

**Comment by ClosetMonkey** [comment]
The inherent desire when we first approach such a thing is to try to put it under a microscope and split every hair until we can fully define what it is and then reproduce our observation as perfectly as possible. That's not needed. All that is needed is accurate and honest representation of what those observations are (resource utilization), not so much the "how", the final product.

**Comment by ClosetMonkey** [comment]
I'm certain that such a module can be used to represent a specific use case by adjusting just 4 or 5 lines withing a configuration script.

**Comment by ClosetMonkey** [comment]
While almost all of the data can be random, it also needs to leverage the existing protocol enough to accurately incorporate the client side. This doesn't need to be done to move an actual object to see by our eyes, and likely shouldn't as that too will limit how the system can be used. While being able to show others a character running through a scene might be appealing, that isn't needed for benching and testing.
