### ISSUE TITLE
Hijacks the HTTP server for /matchmake requests

### ISSUE THREAD

**Issue by MarcusCemes** [colyseus/colyseus#312]
## Context

Attaching Colyseus to an existing HTTP server effectively hijacks the listener functions, replacing them with arrow functions that respond to each request (transparently responding to `/matchmake` requests). This seems like a bit of a dirty hack to keep it simple to use?

https://github.com/colyseus/colyseus/blob/0319284c9ab98bab5177808bb6a4497234732b9c/src/Server.ts#L150

The `/matchmake` route is not documented, and I found it by chance. I imagine it helps take load off of optimized MessagePack schema patches when reverse proxying.

Would it be possible to handle `/matchmake` routes manually as part of the API framework that we choose to use, such as Express (or NestJS in my case)? The problem I bumped into is the `/matchmake` handler waiting for the `end` event to fire on the request, which is usually already fired, as the request is parsed by frameworks.

## Motivation

**Separation of concerns**. Keep Colyseus separate from the main API, which should be fast and could handle sensitive data. I don't like the "hijack requests and move them on if not interested" approach, although the best solution might be a dedicated HTTP server on a different port for Colyseus, which would add more complexity to the firewall/proxy rules...

**Comment by endel** [comment]
Hi @MarcusCemes, thanks for checking out the sources. I've used socket.io as reference for this trick, which they use here: https://github.com/socketio/socket.io/blob/df05b73bb93d7c34c758504001f869cb156703d5/lib/index.js#L322-L347

Theoretically, no request handlers should be compromised by this. If the route starts with "/matchmake", colyseus is going to handle it - otherwise your custom routes from your framework will. You mind providing a minimal reproduction repository which the problem can be observed? Cheers!

**Comment by MarcusCemes** [comment]
That is correct, however, any "/matchmake" handlers would be affected, essentially muted. This should at the least be documented as a reserved path for Colyseus.

I tried to come up with a reproduction of an issue it might cause, for example, if the server closes and a `/matchmake` request comes through, but discovered that calling `.gracefulShutdown()` on Colyseus will also close the original HTTP server, regardless of how it was initialised, essentially meaning "once Colyseus starts, it latches onto the HTTP server and doesn't let go" in a 1-1 relationship. 🤔

Socket.io is old, and uses this method to support HTTP endpoints for non-Websocket polling clients. This was an improvement suggestion to make Colyseus follow a more modular approach for advanced users, at the cost of absolute simplicity, as [ws](https://github.com/websockets/ws/blob/master/doc/ws.md#serverclosecallback) seems to follow.

A two-layer abstraction would be suitable for both types of users, low-level functions to pass WebSocket connections and matchmake requests to for processing without attaching anything to HTTP server instances, and higher-level functions (that makes use of the low-level fncts) that imitate the current behaviour, which would be the recommended approach in the docs.

I guess the best "separation of concerns" is to make Colyseus a disposable game server with a 1-1 relationship with a Node.js process, running critical services in an entirely separate application.

**Comment by Zulfin-Skyward** [comment]
@MarcusCemes  can you tell me how you have managed nestjs server along with colyseus. For now I am using wo diffrent servers for this process but need to merge both

**Comment by MarcusCemes** [comment]
@Zulfin-Skyward I can't remember if I eventually got it working, I originally wanted to keep everything together for the sake of prototyping, but decided that it would be better in the long term to enforce a strict separation of concerns by splitting it into two different applications, a singleton API and scalable game servers. From what it seems though, this is back on the radar in the issue mentioned above.

**Comment by jiabuda** [comment]
@MarcusCemes Hi, i read the source code and find this hijack thing, now I am include the rate-limit npm pack into my project, and from one explicit IP address, could not call /matchmake api more than 2 times in one minute, yet because this hijack , the rate-limit is not working, so is there better way to solve this?

**Comment by MarcusCemes** [comment]
@jiabuda Not sure, I haven't used Colyseus in a while. You could try moving rate-limiting upstream to a reverse proxy, for example.
