### ISSUE TITLE
Suggestion: Return error codes instead of internal phrases for Colyseus client-side errors

### ISSUE THREAD

**Issue by DevMerlin** [colyseus/colyseus#317]
## Context
In dealing with error reporting on the clients, Colyseus returns internal error reporting phrases. This means that the user can't be informed - often, the errors will include internal function names, etc. For instance, Error: "invalid method "matchmake"". These seem to be able to change - meaning they can't be reported with a switch / case / break.

This particular output occurs when a room does not exist, and is reported by 

       await this.client.joinOrCreate('activeRoom', playerData).then(room => {
        this.setupGameRoom(room);
      }).catch(e => {
        // Issue occurs here, with "e".
      });

When trying to report an issue to the user so they know what went wrong, this may not always work best. Numbered error codes that have documented reasons may provide a better solution - such as 001 - No connection, 002 - Room not found, 003 - No authorization, etc. 

This would allow the developer to choose which errors to show and under what context, rather then showing a generic error with no context or writing a larger catch-all that detects the type of phrase. 

## Your Environment

* Colyseus Version: Current
* Node.js Version: 6.13.4
* Operating System and version: Windows 10

**Comment by endel** [comment]
Related, which would be nice to incorporate here too: https://discuss.colyseus.io/topic/329/onauth-return-customdata

**Comment by banool** [comment]
I wonder, what was the fix here in the end?

In the `onCreate` method of my room, throwing a string message does not get returned to the client (`e` is just empty).
