### ISSUE TITLE
When calling matchMaker.create an error log is generated

### ISSUE THREAD

**Issue by dengzhaofun** [colyseus/colyseus#318]
colyseus:errors IPC timed out. method: undefined, args

**Comment by bbirdk2** [comment]
Hi @endel 

My System Info
Visual Studio Code Version 1.45.1
Node.js: 12.8.1
OS: Windows_NT x64 10.0.18363

typescript@3.9.3

**Comment by endel** [comment]
Discussion regarding the new alternative to the `@colyseus/proxy` moved to https://github.com/colyseus/colyseus/issues/370
