### ISSUE TITLE
Issues having numbers as MapSchema index keys

### ISSUE THREAD

**Issue by krazyjakee** [colyseus/colyseus#320]
I searched the issues and nothing seem to come up. Hope this is unique.

When using numbers as index keys on MapSchema, the state seems to start to fall apart after a few manipulations. Everything is reported correctly on the server side and on colyseus monitor, but what the client receives in state change events is whacky.

The workaround now is to **prefix the MapSchema indexes with a letter**. 

Because I absolutely need MapSchema and not ArraySchema, I'd say this was a bug. Either that or the documentation needs to be updated so others know not to use numbers for indexes.

## Steps to Reproduce (for bugs)
You can recreate the issue at this project: https://github.com/krazyjakee/colyseus-bug-test - Just follow the readme. Checkout the `salted-index` branch for the workaround.

## Context
I am storing items in a MapSchema to use keys to maintain a specific order. I can also store references to the MapSchema in subclasses, wheras with ArraySchema I cannot.

## Your Environment
* Colyseus Version: ^0.12.5
* Node.js Version: ^13.7.0
* Operating System and version: Windows
* Link to your project: https://github.com/krazyjakee/colyseus-bug-test

**Comment by endel** [comment]
This has been finally fixed on 0.14! 🎉  https://github.com/colyseus/colyseus/releases/tag/0.14.0
