### ISSUE TITLE
Unreal Engine Support

### ISSUE THREAD

**Issue by kruzus** [colyseus/colyseus#326]
Hello there, can I integrate colyseus with Unreal Engine as its server?

**Comment by endel** [comment]
Not at the moment @kruzus, it is a lot of effort for me to keep track of all current clients, if you'd like to jump in and make one yourself - the [cocos2d-x client](https://github.com/colyseus/colyseus-cocos2d-x) has been written in C++, it can be a good starting point!

**Comment by kruzus** [comment]
Hey @endel thank you responding me, I am still new at this but I'll give it a shot. Sorry to bother you, you can close this if you want. Cheers!
