### ISSUE TITLE
colyseus / monitor module cannot be used normally

### ISSUE THREAD

**Issue by dengzhaofun** [colyseus/colyseus#333]
@colyseus/monitor: room OC_M6idkz is not available anymore.

**Comment by endel** [comment]
Hi @dengzhaofun are you using latest version of colyseus/monitor? I remember this was an issue on a previous version. Latest one works both with colyseus 0.13 and 0.12

**Comment by dengzhaofun** [comment]
@endel 
```
    "colyseus": "^0.13.3",
    "@colyseus/command": "^0.1.5",
    "@colyseus/monitor": "^0.12.2",
    "@colyseus/proxy": "^0.12.1",
```
http://127.0.0.1:4002/colyseus//api/room/call?roomId=IK6bicrbq&method=_forceClientDisconnect&args=%5B%22FahFlzlst%22%5D
@colyseus/monitor: room IK6bicrbq is not available anymore.


Still not working properly, and the latest version should have a type field, but the monitoring tool did not fill in the place.

**Comment by endel** [comment]
Closing as this doesn't seem to be a problem - may be a @colyseus/proxy misconfiguration. Feel free to re-open if you still need help!
