### ISSUE TITLE
Race condition in colyseus MapSchema leads to clients deleting the wrong id

### ISSUE THREAD

**Issue by LukeWood** [colyseus/colyseus#337]
## Steps to Reproduce (for bugs)
https://github.com/LukeWood/Colyseus-Race-Condition-Minimal-Setup
1.  `yarn install`
2.  `yarn run dev`
3.  open one browser tab, this one will work fine.
4.  open another browser tab - this one *MIGHT* fail.
5.  if it doesnt fail just refresh the page

## Context
The code that causes this behavior is located in ArenaRoom.ts in the onjoin handler.

This handle immediately creates new values in the entities map under generated bot ids. For some reason when doing this while a client is initializing sometimes the client will delete the wrong value from the map.

I've fixed this in the project I'm working on by doing: 

```
setTimeout(() => this.manageBotPopulation(), 500)
```

but that's a pretty bad workaround.

This came about when trying to implement bots for https://tp-scramble.io

## Your Environment

* Colyseus Version: ^0.13.0
* Node.js Version: v11.15.0
* Operating System and version: macos (but it also showed up in my server running ubuntu)
* Link to your project: https://tp-scramble.io

**Comment by LukeWood** [comment]
Note:  I forgot to mention but the root cause is when `manageBotPopulation` *DELETES* a value during the playerAdd lifecycle - adding a value at the same time is just fine.

**Comment by endel** [comment]
Thanks for your detailed report as always @LukeWood 

Version 0.14 seems to have fixed this! 🎉  https://github.com/colyseus/colyseus/releases/tag/0.14.0
