### ISSUE TITLE
Throw reasonable error when sending/broadcasting a message without a type

### ISSUE THREAD

**Issue by endel** [colyseus/colyseus#338]
Only `Schema` messages can be sent without a type. (`this.broadcast(message)`)

When trying to broadcast a message that is not from `Schema` type, this error is not meaningful:

```
TypeError: message.encodeAll is not a function or its return value is not iterable
```

**Comment by Elyx0** [comment]
I was going with
```
  [Protocol.ROOM_DATA_SCHEMA]: (message: Schema) => {
    let typeid = (message.constructor as typeof Schema)._typeid;
    if (typeid === undefined) {
      console.warn(
        "\x1b[33m%s\x1b[0m",
        "[colyseus] We were unable to detect the type of the Schema. Starting at colyseus >= 13.0 You must provide a type and message when calling `this.broadcast` or client.send`. Please see: https://docs.colyseus.io/migrating/0.13/"
      );
    }
    return [Protocol.ROOM_DATA_SCHEMA, typeid, ...message.encodeAll()];
  },
```
That yields
![Screen Shot 2020-05-13 at 7 23 18 AM](https://user-images.githubusercontent.com/706218/81807655-77b89680-94ec-11ea-946c-b5e3d9ff52c1.png)

**Comment by endel** [comment]
Thanks for the suggestion @Elyx0 🎉 

![Screenshot 2020-05-14 at 00 13 35](https://user-images.githubusercontent.com/130494/81866512-fa3a6800-9577-11ea-95e2-d88e1d930bd2.png)
