### ISSUE TITLE
Overwrite generateId

### ISSUE THREAD

**Issue by confuser** [colyseus/colyseus#340]
Currently building a game where players join rooms with their friends only. I've currently built this to use the roomId as the key they share in order to join. 

However the current id generation is case sensitive and adds additional characters such as _ and - which in circumstances where they're not able to copy/paste easily (people playing in the same room but on different devices etc) is somewhat problematic from a UX perspective. 

Would it be possible to overwrite the generateId function for room creation? https://github.com/ai/nanoid#custom-alphabet-or-size looks ideal, but would be more flexible if this could support non nanoid alternatives as well.

**Comment by MateusMendesSantana** [comment]
Hi. You can override the room id at the time of creation ;D
```
async onCreate(options: any) {
  this.roomId = nanoid()
}
```
