### ISSUE TITLE
Persist room state between restarts

### ISSUE THREAD

**Issue by confuser** [colyseus/colyseus#341]
Is this possible? Based on discussions on Discord it doesn't seem to be a built in feature of colyseus w/Redis/Mongo. At the moment when the backend is deployed (restarted), all room state is lost and players need to restart their game from scratch.

Or if there's a way to add this functionality ourselves a rough guide covering this use case would be most appreciated. Thanks!

**Comment by MateusMendesSantana** [comment]
Hi. I think that each game has different needs, adding this feature would only increase the complexity of the framework and limit the architecture. For example I used Colyseus Social, but I stopped when my game needed more freedom. Furthermore, saving the state of the room is not so complicated to implement.
```
async onCreate(options: any) {
  this.roomId = options.id;
  const place = await PlaceRepository.findById(options.id).exec();
  if (place) {
    this.setState(new Place(place.toObject()));
  } else {
    this.disconnect();
  }
}

public async onDispose() {
  await this.saveState(true);

  console.log(`${this.roomId} closed and saved`);
}
```
In my c# client:
```
public async Task<Room<T>> JoinByIdOrCreate<T>(string roomName, string roomId)where T : Schema {
    var options = new Dictionary<string, object>();
    options["id"] = roomId;
    options["create"] = true;

    try {
      return await client.JoinById<T>(roomId);
    } catch (Exception error) {
      var matchMakeException = error as MatchMakeException;

      if (matchMakeException != null && matchMakeException.Code == 4212) {
        return await client.Create<T>(roomName, options);
      } else {
        throw error;
      }
    }
  }
```

**Comment by endel** [comment]
Thanks for answering @MateusMendesSantana :) This feature is likely never going to happen on `colyseus` itself, you can totally do this by yourself by storing important data in the database during `onDispose()`, and initializing the state again during `onCreate()`
