### ISSUE TITLE
Matchmaking filter does not work correctly.

### ISSUE THREAD

**Issue by lity** [colyseus/colyseus#342]
server side:
gameServer.define('my_room', MyRoom).filterBy(['ownerId']);

client side:
userId = "user_12345"; // not null and length >0
client.create("my_room", { ownerId: userId });

...

when a client joined a room with ownerId '' or null like this:
room = client.join("my_room", { ownerId: '' });
or
room = client.join("my_room", { ownerId: null });

I expected a exception of "no rooms found with provided criteria", but actually the client joined the room which ownerId is "user_12345".

Colyseus version: 0.13

**Comment by endel** [comment]
This has been fixed on #468
