### ISSUE TITLE
feature request: communication between client and server before client joins a room.

### ISSUE THREAD

**Issue by lity** [colyseus/colyseus#344]
Now if I want to push some messages from server to client, which is a commen requirement, I have to use socket.io or sth else besides using colyseus.

If communication between client and server before client joins a room is supported, it'll be more elegant and convenient.

[socket.io](https://socket.io/)

**Comment by endel** [comment]
Hi @lity, you do need a room to communicate with the server. You may define a room that all your clients connect to for communication without dealing with the state.

**Comment by lity** [comment]
> Hi @lity, you do need a room to communicate with the server. You may define a room that all your clients connect to for communication without dealing with the state.

Thanks, it's a solution indeed.
