### ISSUE TITLE
After client reconnect a few moments later receives a onLeave event - intentional?

### ISSUE THREAD

**Issue by finkton1** [colyseus/colyseus#348]
After the client successfully reconnects back to the room they previously belonged to, a few moments later it appears the specific client receives  a onLeave event that had to do with their own leave.

The leave code is 1006 - which means no close code frame.

Not sure if this is a bug or is dependent on my environment.

I use cordova for android - it seems that it sends to websocket the close code of 1006.

I could get around my issue if I check for a on leave code of 1006 but that does not seem correct approach 

I was reading up on the issue a little bit and stumbled upon this:

> on android, the problem might be with the ping/pong mechanism of the library. android will freeze the application while it's idle, waking it up only from time to time. therefore you can't rely on Timers to ping/pong, and Timer is what this library is using by default. you can do setConnectionLostTimeout(0) and implement your own pinging mechanism using AlarmManager

> run the library in debug mode (set WebSocketImpl.DEBUG to true) to verify that you are getting 1006 because of this

Reference: [https://github.com/TooTallNate/Java-WebSocket/issues/663](url)

Regardless of the error code - was it intentional to send the onLeave event to a reconnected client?

**Comment by endel** [comment]
Hi @finkton1, could this be related to https://github.com/colyseus/colyseus/issues/361? We also couldn't reproduce the problem described here :/

**Comment by zgz682000** [comment]
Hello again, @endel 
I had reproduced this condition as follow steps:
1. server `await this.allowReconnection` in `async onLeave()` for every client, no mater `consented` equals `true` or `false`
2. client leaves room actively 
3. client reconnect this room after a few moment
4. client will rejoin successfully but immediately receive `onLeave` event
5. from my researching, this is because the `then` callback in the last line of following function
```
_forciblyCloseClient(client, closeCode) {
        // stop receiving messages from this client
        client.ref.removeAllListeners('message');
        // prevent "onLeave" from being called twice if player asks to leave
        const closeListeners = client.ref.listeners('close');
        if (closeListeners.length >= 2) {
            client.ref.removeListener('close', closeListeners[1]);
        }
        // only effectively close connection when "onLeave" is fulfilled
        this._onLeave(client, closeCode).then(() => client.leave(Protocol_1.Protocol.WS_CLOSE_NORMAL));
    }
```

**Comment by endel** [comment]
Interesting, thanks for taking the time to inspect this @zgz682000!

> I think in your design, actively leaveing room should not be allow for reconnecting.
> Is it your original intention?

That's correct! I think this is a real bug worth fixing somehow. Need to evaluate what's the best approach here.

---

We currently have one breaking change planned for reconnection (https://github.com/colyseus/colyseus/issues/354) - It may be possible that we need another breaking change to properly fix this current issue as well.

**Comment by zgz682000** [comment]
Thanks for tripple emoj, haha!

It looks that #354 is a awesome change. 

I will also try to provide a probible solution of this bug.

My temporarily workaround is replacing "await this.allowReconnection()" with "this.allowReconnection.then(()=>xxx)" to make onLeave invokation finish before client reconnect

**Comment by lpsandaruwan** [comment]
Hi @zgz682000 
I tried to reproduce this issue as you explained. But couldn't do it. Are you using allowReconnection without concerning `consented`?

**Comment by endel** [comment]
Could you possibly share a small repository where we can observe the issue @zgz682000? Thankss

**Comment by zgz682000** [comment]
> Hi @zgz682000
> I tried to reproduce this issue as you explained. But couldn't do it. Are you using allowReconnection without concerning `consented`?

Yes, I was using allowReconnection when consented equals `true`.

**Comment by zgz682000** [comment]
So I think it's nessecery to write a remarkable warning just like "warning: allowReconnection must be used when xxxx".
And when mistakenly used, throwing an explicit exception.

**Comment by zgz682000** [comment]
> Could you possibly share a small repository where we can observe the issue @zgz682000? Thankss

Here it is!

https://github.com/zgz682000/colyseus-bug-test-348.git

And these are the console outputs on my running

server
![image](https://user-images.githubusercontent.com/9474727/133379411-6243bd2d-59bf-4122-8a0a-86eb686e5cae.png)

client
![image](https://user-images.githubusercontent.com/9474727/133379445-4cf85097-21f0-4df8-99fa-85a7d1dfaa4b.png)
