### ISSUE TITLE
problem synching state when using async onJoin 

### ISSUE THREAD

**Issue by virtumonde** [colyseus/colyseus#350]
I am experiencing the same problem described in https://github.com/colyseus/colyseus/issues/137. Did anything change since 2018 on this topic?

```
Uncaught TypeError: Cannot read property 'length' of undefined
    at Object.fossilDelta.apply (VM301 1.chunk.js:17943)
```

**Comment by endel** [comment]
Are you explicitly using FossilDelta @virtumonde? Or are you not using the state at all?

**Comment by virtumonde** [comment]
@endel I am using state but it is not initialized initially on room initialization. When the first player connects, he doesn't receive any state, and then the error is happening.

I am not using FossilDelta (as far as I know), by default the Schema is used, right?

**Comment by virtumonde** [comment]
@endel The problem just solved itself when I switched the onJoin method to async. Is Schema used by default?

**Comment by endel** [comment]
I see, actually by default we're still using FossilDelta (soon it's going to be "none" https://github.com/colyseus/colyseus/issues/335)

When you call `this.setState()`, the serializer is switched according to the structure you provide. It's important to use `this.setState()` BEFORE the first client joins, so he can receive the correct handshake information. For the schema serializer, the entire "reflected" schema structure is sent during handshake.

Glad it's working for you now. Cheers

**Comment by virtumonde** [comment]
Actually it doesn't have to do anything with async. It was because there was no state at all when the first client connects and I added it before I make my async action (API call).

**Comment by virtumonde** [comment]
@endel Thanks for the quick response!
