### ISSUE TITLE
npm init colyseus-app ./my-colyseus-app command doesn't work

### ISSUE THREAD

**Issue by Chroma72** [colyseus/colyseus#352]
Would really like to try out Colyseus but every time I try to run:
npm init colyseus-app ./my-colyseus-app

I get this:
```
npx: installed 15 in 1.767s
√ Which language you'd like to use? · TypeScript (recommended)
Downloading template...
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn git ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn git',
  path: 'git',
  spawnargs: [
    'clone',
    '--depth=1',
    '--single-branch',
    '--branch',
    'typescript',
    'https://github.com/endel/create-colyseus-app.git',
    './my-colyseus-app'
  ]
}
```

Any ideas? Been trying to solve this for hours and have checked all over Google but haven't found a solution to actually install or even run a barebones simple server example in JS.

**Comment by endel** [comment]
Hi @Chroma72, by reading your error message (`Error: spawn git ENOENT`) it seems you don't have GIT installed. 

Please try installing GIT first: https://git-scm.com/downloads
Also, make sure you have a recent version of Node.js installed locally!

I hope this helps!

**Comment by Chroma72** [comment]
Thanks for the fast response Endel!
It's time to kick ass and chew bubble gum!

Haha very nice.

**Comment by Chroma72** [comment]
So after installing git and running the npm init colyseus-app ./my-colyseus-app command I had to manually install express, colyseus, cors, and @colyseus/monitor...which is probably normal. I'll be out of newb mode soon...
