### ISSUE TITLE
Access Control default settings

### ISSUE THREAD

**Issue by GreenArrow18** [colyseus/colyseus#353]
I am getting a console warning using Microsoft Edge on Windows 10.

SEC7139: [CORS] The origin 'https://website.local' used the maximum Access-Control-Max-Age value of '2592000' as the provided value exceeded this for a cross-origin request to 'https://server.local/matchmake/join/AppName'.

website.local : hosts the web site pages and the games
server.local: where colyseus server is running

Looking at the colyseus server codes, I find this:
```
const headers = {
            const headers = {
                'Access-Control-Allow-Headers': 'Origin, X-Requested-With, Content-Type, Accept',
                'Access-Control-Allow-Methods': 'OPTIONS, POST, GET',
                'Access-Control-Allow-Origin': '*',
                'Access-Control-Max-Age': 2592000,
            };
```

Is there a safer value for Control-Max-Age that will not generate a warning as above? Or is this something I can "fix" in my server settings (I'm using nginx)? It only happens in Edge. Chrome is ok in my tests so far.

Also, is it possible to override 'Access-Control-Allow-Origin' setting? I would like to specify specific domains only to be allowed access to the server.

Thanks.

**Comment by endel** [comment]
HI @GreenArrow18, thanks for reporting. Does this causes problems for you other than printing a warning on Edge? 

Currently it's not possible to customize this value. By looking at the [`cors` package](https://github.com/expressjs/cors/blob/c1867c3a79c08e16b705e4a65e426f7d7459d0b1/lib/index.js#L169), it seems `Access-Control-Max-Age` is not required for CORS requests. We may remove it on the next version if that doesn't cause any problems.

**Comment by GreenArrow18** [comment]
Hi Endel, from my tests, other than the warning this doesn't really seem to pose any real problem so far.

Probably better to make the header settings be changeable from defaults, for those who might need it, as currently this also can't be overriden from within nginx config it seems.

I was initially trying to change CORS settings through ngnix and wondering why my changes are not working, until I realized colyseus is automatically handling this area on its own already :)

Thanks!
