### ISSUE TITLE
Reconnection: use a private "reconnection token" instead of "sessionId"

### ISSUE THREAD

**Issue by endel** [colyseus/colyseus#354]
There is a security vulnerability that could allow any client that has the `sessionId` and `roomId` to "reconnect" and act on other client's behalf in case he got disconnected AND `allowReconnection()` is being used with his `sessionId`.

**Comment by rnd256** [comment]
Does Colyseus expose all `sessionId`s to all clients by default, or is this only an issue if you include `sessionId` in your Schema?

**Comment by endel** [comment]
Hi @rnd256, this is only an issue if you include `sessionId` in your Schema / broadcast to other players somehow.  The API's and documentation currently encourage you to do that, though
