### ISSUE TITLE
Deploy can't connect client to endpoint

### ISSUE THREAD

**Issue by vittis** [colyseus/colyseus#355]
Hey, I'm having issues connecting the client to WS when deploying.

I'm using Node + React and for dev I use `const client = new Client('ws://localhost:2567');` and works fine

Now I created a droplet in Digital Ocean, created a static build of the client and put it on server under build folder and serve like that:
```
app.get('*', function (req, res) {
  res.sendFile(path.join(__dirname, 'build', 'index.html'));
});
```
But when I access it on the browser I get connection failed. I tried localhost and the ip of the droplet but no success, the error on browser console is:

`POST http://localhost/matchmake/joinOrCreate/life_room net::ERR_CONNECTION_REFUSED`

Anyone know what endpoint or setup should I use to make it work? Thanks

**Comment by wrigggy** [comment]
You must ensure that your colyseus server is correctly exposed to the internet. Localhost will not work at all, as the browser will only try to connect to locally hosted servers.

https://docs.colyseus.io/deployment/

**Comment by vittis** [comment]
@wrigggy Thanks for reply.

I did the steps under "Nginx configuration". When I ssh my droplet and runs it the output is `Listening on ws:__localhost:2567` so I think this step is fine.

I'm still unsure in what endpoint show I put in this line below as it's seem to be what's not working

`const client = new Client('ws://localhost:2567');`

**Comment by wrigggy** [comment]
> I'm still unsure in what endpoint should I put in the client in this line below as it's seem to be what's not working
> 
> `const client = new Client('ws://localhost:2567');`

You need to find the external ip address that your droplet is accessible with, and substitute it for localhost.

`const client = new Client('ws://your-droplet-ip-address');`

You should find it somewhere in your digital ocean dashboard.

**Comment by vittis** [comment]
I still get `POST http://167.172.126.142:2567/matchmake/joinOrCreate/life_room net::ERR_CONNECTION_TIMED_OUT`

Error now is connection timed out . 

http://167.172.126.142/

^ That's where my app is if it helps in something, you can see that error in console when you access it.

I must've done something wrong in the nginx setup, I'll look better into it. 

Thanks for the help and directions, it helped!

**Comment by vittis** [comment]
My error was that I was including the port with the IP of the droplet, removed it and it worked. I'll close the issue now. 

Thanks for the help @wrigggy!
