### ISSUE TITLE
Only one setSimulationInterval() is working, bug or feature?

### ISSUE THREAD

**Issue by virtumonde** [colyseus/colyseus#358]
```
  onCreate (options: any) {

    this.setSimulationInterval(() => {
      console.log('foo')
    }, 10 * 1000);

    this.setSimulationInterval(() => {
      console.log('bar')
    }, 5 * 1000);

  }

// only bar is printed
```

Would it be advisable to use this.clock? I need different simulation intervals because I want to execute an expensive function at a longer interval.

## Steps to Reproduce (for bugs)
Run the code above.

## Environment
* Colyseus Version: 0.14.0-alpha.2
* Node.js Version: v14.5.0
* Operating System and version: MacOS 10.14 Mojave

**Comment by endel** [comment]
Hi @virtumonde, sorry the delay to answer here. Indeed you can only have one `setSimulationInterval()`. You can have as many `this.clock.setInterval()` though. Cheers!

**Comment by ScreamZ** [comment]
@endel I'm not sure of wether to use simulationInterval or clock, could you provide use case and why not doc suggestion ?

**Comment by endel** [comment]
Hi @ScreamZ, the "simulation interval" is supposed to be your "game loop", which you should have only one in your application. 

The clock's interval/timeouts on the other hand are meant for specific timing features you'd potentially need, as you can see in the [timing events](https://docs.colyseus.io/server/timing-events/) documentation, you can even pause/resume/cancel interval/timeouts if you need. 

Hope this helps! Cheers
