### ISSUE TITLE
JOIN ERROR {"isTrusted": false, "timeout": false}

### ISSUE THREAD

**Issue by virtumonde** [colyseus/colyseus#360]
What does the following error mean? I am getting this on my local server whereas Heroku is running ok.
```
[Thu Jul 16 2020 22:10:05.825]  LOG      JOIN ERROR {"isTrusted": false, "timeout": false}
```

**Comment by Elyx0** [comment]
It's when the server is cut or unreachable from the client usually for me

**Comment by virtumonde** [comment]
@Elyx0 thank you for pointing out. I do not know the issue but I think it might be related to the fact the I am using the Mapbox library. If you use `10.0.3.2` (In case of Genymotion) or `10.0.2.2` (in case of the native emulator), as a synonym for the localhost, it works.

**Comment by Elyx0** [comment]
That's very colyseus unrelated indeed
