### ISSUE TITLE
OnLeave event not fired after websocket closes

### ISSUE THREAD

**Issue by finkton1** [colyseus/colyseus#361]
Good Day - I am trying to impliment [https://docs.colyseus.io/server/room/#allowreconnection-client-seconds](url)

It use to work, however for the life of me I can't seem to get the server to know the client dropped websocket connection and has some seconds to rejoin consistently. It is very flaky. 

Sometimes it will fire the onLeave event in 20-30 seconds, sometimes 5+ minutes.

Not sure if a 3rd party library is the culprit or what - I throughoughly went through my nginx configs and everything looks to be correct for using PM2 with reverse proxy and SSL. Ping-Pong(heartbeat) should not be a problem?

Any help is much appreciated.

**Comment by Elyx0** [comment]
Hi fink, did you progress any investigation on this?

**Comment by finkton1** [comment]
> Hi fink, did you progress any investigation on this?

I never got this to work, it still does not recognize the drop in connection.

**Comment by endel** [comment]
@finkton1 provided a sample of the issue here https://github.com/finkton1/test-colyseus
@kainguyenhuu also reported this recently on Discord

From what I've gathered so far, this seems to be happening on Android

**Comment by finkton1** [comment]
@endel is this something that is currently being researched?

**Comment by endel** [comment]
Hi @finkton1, afaik no one is having a look at this at the moment. Any help is appreciated! 🙏

**Comment by endel** [comment]
Hi @finkton1, we've tried and could not reproduce the issue. :/

@Elyx0 have you experienced this issue yourself as well? We've tried both a plain Colyseus app, and having it behind NGINX, and couldn't reproduce.
