### ISSUE TITLE
Invalid WebSocket frame on iOS (React Native)

### ISSUE THREAD

**Issue by serjek** [colyseus/colyseus#364]
## Steps to Reproduce (for bugs)
1. Use React Native client on iOS
2. Send some data to server
3. Sometimes following error occurs:
```js
Invalid WebSocket frame: invalid payload length 126
RangeError: Invalid WebSocket frame: invalid payload length 126
    at Receiver.getInfo (/Users/s/Projects/sp/server/node_modules/ws/lib/receiver.js:216:16)
    at Receiver.startLoop (/Users/s/Projects/sp/server/node_modules/ws/lib/receiver.js:127:22)
    at Receiver._write (/Users/s/Projects/sp/server/node_modules/ws/lib/receiver.js:74:10)
    at doWrite (_stream_writable.js:415:12)
    at writeOrBuffer (_stream_writable.js:399:5)
    at Receiver.Writable.write (_stream_writable.js:299:11)
    at Socket.socketOnData (/Users/s/Projects/sp/server/node_modules/ws/lib/websocket.js:875:35)
    at Socket.emit (events.js:193:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
```

## Context
This error then causes client to disconnect. 
This issue relates to some websocket internals and I found some of them in other server projects:
https://github.com/parse-community/parse-server/issues/6413
https://github.com/parse-community/parse-server/issues/6173

As for colyseus clients, we have this related ticket: https://github.com/colyseus/colyseus-hx/issues/33

## Your Environment
* Colyseus Version: 0.13.5
* Node.js Version: 11.14.0
* Operating System and version: Mac, FreeBSD
* Link to your project: none yet

**Comment by serjek** [comment]
Note that issue still persists if using latest ws@7.3.1. Could it be a ws misconfiguration on colyseus side so that ws does not accept relatively large payloads?

**Comment by vitalyrotari** [comment]
@serjek you use ReactNative?

**Comment by vitalyrotari** [comment]
@seiyria try to disable pings from server

```
const server = Colyseus.Server({
  pingInterval: 0,
})
```

**Comment by vitalyrotari** [comment]
also I report this again to RN Team 

old issue: https://github.com/facebook/react-native/issues/23825
new issue: https://github.com/facebook/react-native/issues/30020

**Comment by serjek** [comment]
Hey yes, it's RN with iOS only. Upvoted issue you referred, thanks! Perhaps this one can be closed then.

**Comment by endel** [comment]
Let's keep this issue open, maybe this will pop in the future...

**Comment by moneymc** [comment]
> Note that issue still persists if using latest ws@7.3.1. Could it be a ws misconfiguration on colyseus side so that ws does not accept relatively large payloads?

You sure about that? Looks like it was fixed in ws 7.2.3 (https://github.com/websockets/ws/commit/e54f08daeef64d4b78f10ec2d7258b429961dac2)

Colyseus uses 7.1.0

**Comment by vitalyrotari** [comment]
@moneymc this issue comes from ReactNative iOS RNSocket

**Comment by endel** [comment]
@vitalyrotari @serjek apparently this has been finally fixed on the react-native side! https://github.com/facebook/react-native/commit/86db62b7a8b28ac82dd0a0627a8b6c351875f682

**Comment by serjek** [comment]
> @vitalyrotari @serjek apparently this has been finally fixed on the react-native side! https://github.com/facebook/react-native/commit/86db62b7a8b28ac82dd0a0627a8b6c351875f682

yeah, i saw PR was merged, looking forward to try that out when they roll out new RN version!

**Comment by endel** [comment]
Seems to be fixed on the React Native side!
