### ISSUE TITLE
Basic Example Broken?

### ISSUE THREAD

**Issue by radiantone** [colyseus/colyseus#367]
Just trying the basic code on the Getting Started docs page, but always getting error.

```
import * as Colyseus from "colyseus.js";

console.log(Colyseus);

var client = new Colyseus.Client('ws://localhost:3003');

client.join("welcome").then(room => {
    console.log(room.sessionId, "joined", room.name);
}).catch(e => {
    console.log("JOIN ERROR", e);
});
```

var client = new Colyseus.Client('ws://localhost:3003');
             ^
TypeError: Colyseus.Client is not a constructor

**Comment by endel** [comment]
Hi @radiantone, what are you using as your build stack for the frontend? Could you provide a way I could reproduce it? Thanks!

**Comment by radiantone** [comment]
Here is steps to reproduce

$ cd colyseus-test 
$ npm init
$  npm install colyseus.js
$  npm install ws
$  vi client.js  (paste code from above)
$  vi package.json (add "type":"module")
$ node client.js 
var client = new Colyseus.Client('ws://localhost:3003');
             ^
TypeError: Colyseus.Client is not a constructor
    at file:///home/darren/temp/colyseus/client.js:5:14
    at ModuleJob.run (internal/modules/esm/module_job.js:140:23)
    at async Loader.import (internal/modules/esm/loader.js:162:24)

**Comment by endel** [comment]
Hi @radiantone, `colyseus.js` in general is not compatible with `"type":"module"` at the moment. 

You could use it in Node.js with commonjs, though (code below works)

```javascript
const Colyseus = require("colyseus.js")

const client = new Colyseus.Client('ws://localhost:3003');

client.join("welcome").then(room => {
    console.log(room.sessionId, "joined", room.name);
}).catch(e => {
    console.log("JOIN ERROR", e);
});
```
