### ISSUE TITLE
Better scalability options (replace @colyseus/proxy?)

### ISSUE THREAD

**Issue by endel** [colyseus/colyseus#370]
Currently, we need the [@colyseus/proxy](https://github.com/colyseus/proxy/) in order to scale while keeping the matchmaker aware of all nodes in the "cluster".

The problems the proxy has are:
- Single point of failure (all connections go through the proxy)
- If the proxy restarts, all connections are going to be lost and need to be re-established
- It seems that [`"node-http-proxy"` has a memory-leak](https://github.com/OptimalBits/redbird/issues/237#issuecomment-602708633) (`@colyseus/proxy` depends on `node-http-proxy`)

Ideally, Colyseus should allow better scalability options rather than heavily relying on `@colyseus/proxy`.

Previous discussion: https://github.com/colyseus/colyseus/issues/179

**Comment by vitalyrotari** [comment]
@endel I found interesting project base on C++, is a proxy server, you can take a look https://pushpin.org/. Maybe it can be integrated with Colyseus

**Comment by qinfanheaven** [comment]
@endel try [OpenResty](https://github.com/openresty/openresty)
I have achieved the same proxy capability as colyseus/proxy

**Comment by endel** [comment]
Hey @qinfanheaven, that's interesting! Would you mind sharing how you've approached replicating the functionality of `colyseus-proxy` with OpenResty?

**Comment by qinfanheaven** [comment]
@endel Here is my simple demo, it works fine to me.(before using this, OpenResty should be installed)
[openresty.zip](https://github.com/colyseus/colyseus/files/9285925/openresty.zip)

**Comment by qinfanheaven** [comment]
At the nginx worker init phase, I start a timer to keep watch the colyseus:nodes in redis.
The colyseus module mostly use lua-nginx-module to read or subscribe redis.
```
-- worker-initing

ngx.log(ngx.NOTICE, "init_worker")

local colyseus = require "conf.colyseus"

local function updateColyseusNodes()
    if colyseus.isReading() then
        -- avoid duplicate operation
        return
    end
    colyseus.updateNodes()
    colyseus.subscribe()
end

local function watchColyseusNodes()
    ngx.log(ngx.NOTICE, "watch colyseus:nodes start")
    -- keep watching
    while true do
        if ngx.worker.exiting() then
            ngx.log(ngx.NOTICE, "watch colyseus:nodes end")
            break
        end
        updateColyseusNodes()
    end
end

-- start watching colyseus:nodes
local hdl, err = ngx.timer.at(0, watchColyseusNodes)
if not hdl then
    ngx.log(ngx.CRIT, "watch colyseus:nodes err:", err)
end
```

And when request comes, at the access phase, parse the request_uri ( same as colyseus-proxy)
to decide which Node should be set in proxy_pass(saved as proxyNode in nxg.ctx)
```
local cjson = require "cjson"
local colyseus = require "conf.colyseus"

-- match the processId in uri
local captures = ngx.re.match(ngx.var.request_uri, [[\/([a-zA-Z0-9\-_]+)\/[a-zA-Z0-9\-_]+\?]], "jo")

if captures and #captures == 2 then
    -- proxy to the specific backend
    ngx.ctx.proxyNode = colyseus.getNodeByProcessId(captures[1])
else
    -- proxy to random backend
    ngx.ctx.proxyNode = colyseus.getRandomNode()
end

-- ngx.log(ngx.INFO, 'ngx.ctx.proxyNode: ', cjson.encode(ngx.ctx.proxyNode))

```

At the content phase, in balance_by_lua_file:
```
local balancer = require "ngx.balancer"

balancer.set_timeouts(0.5, 600, 600)
balancer.set_more_tries(2)

balancer.set_current_peer(ngx.ctx.proxyNode.host, ngx.ctx.proxyNode.port)
```

**Comment by smokeythebandit** [comment]
Hey Guys,

I'm currently deploying Colyseus in a Kubernetes cluster, and am running into issues with the proxy while stress testing.

I'd be able to implement the proxy in C++. To replicate the current functionality I think I can manage, but with regards to handeling reconnect in case a proxy crashes/connection drops I'm not sure how to deal with it.

Is this something you guys would be interested in?

**Comment by endel** [comment]
We can finally close this! 🚀 🚀 🚀 🚀  https://docs.colyseus.io/scalability/
