### ISSUE TITLE
Official API only provides 1 way to enable real-time listing

### ISSUE THREAD

**Issue by tonygiang** [colyseus/colyseus#374]
According to the [documentation](https://docs.colyseus.io/server/api/), the only way to enable real-time listing in lobby is to call `enableRealtimeListing` individually for each room created by the server (via `Server.define`).

There is no way to enable this when creating rooms from the client, or for each room schema. Please provide this ability.

**Comment by endel** [comment]
Hi @tonygiang, the client-side will never have this power directly. 

You can, however, manipulate the "realtime listing" manually through these methods:

```typescript
import { updateLobby,  subscribeLobby } from "colyseus";
```

- `updateLobby(room, remove?)` forces to include or remove a room instance on the realtime listing
- `subscribeLobby()` allows you to write your own version of the `LobbyRoom` if you'd like to

The source-code for both methods are here: https://github.com/colyseus/colyseus/blob/master/src/matchmaker/Lobby.ts

_(They should be documented in the future!)_

**Comment by tonygiang** [comment]
If enabling real-time listing can be done through a room schema, then it's as good as giving the ability to a client directly. I can have that function being called on receiving a client message. The real gripe with [enableRealtimeListing](url) is it can only be called before deploying the server, whereas having it in room schemas enables real-time listing on demand at runtime.
