### ISSUE TITLE
Join a room by custom identifier

### ISSUE THREAD

**Issue by BjoernRave** [colyseus/colyseus#376]
Inspired by Among Us, it would be cool if I could create a private room, where I set an easy string as identifier, like `CXFAWS`.

Then user who want to join the room could just provide this string and join the room.

Currently AFAIK the only way to join a private room is with the `joinById` function, which needs the roomId.

**Comment by endel** [comment]
Hi @BjoernRave! There are two ways you can achieve this:

- By overwriting `this.roomId` during `onCreate()` (you'd need to make sure the `roomId` in use is unique by yourself)
- Using matchmaking filters: https://discuss.colyseus.io/topic/345/is-it-possible-to-run-joinorcreatebyid/2

Hope this helps! Cheers!
