### ISSUE TITLE
Support `onMessage` parsing `Schema` messages sent from client to server

### ISSUE THREAD

**Issue by rnd256** [colyseus/colyseus#377]
The work @endel did for issue https://github.com/colyseus/colyseus/issues/315 is extremely useful for sharing `Schema`s between the client and server for messages that the server sends to the client, and it would be great to have that same functionality available when sending messages from the client to the server.

Currently, everyone needs to manually implement parsing JSON messages from the client, which is error-prone and a hassle. Additionally, implementing this would let us benefit from using schema-codegen to keep message schemas the same between the client and server.

It could look something like this, similar to what's listed in https://github.com/colyseus/colyseus/issues/315:

```ts
this.onMessage(MoveMessage, (client: Client, message: MoveMessage) => {
  // Handle schema-encoded MoveMessage, while benefitting from autocompletion.
});
```

**Comment by endel** [comment]
Hi @rnd256, what do you think of https://github.com/colyseus/schema/pull/68? 

Implementing the schema **encoder** on all clients would be a tremendous effort, the solution proposed on https://github.com/colyseus/schema/pull/68 is to define interfaces (containing a `Message` keyword: e.g. `interface MyMessage {}`) for the message types you'd like to have shared, and the `schema-codegen` will generate them.

If we could improve https://github.com/colyseus/schema/pull/68 somehow that'd be ideal, if you have any feedback to improve how it works currently would be great! Thanks!

**Comment by rnd256** [comment]
That looks perfect, thanks! Is the special handling of interfaces mentioning "Message" included in the docs anywhere? I couldn't find it when I was searching, which is why I ended up filing this issue.

**Comment by rnd256** [comment]
I think this is still relevant - ideally the docs would cover this helpful feature

**Comment by endel** [comment]
Hi @rnd256, thanks! I agree, let's use this issue to track the progress on the documentation https://github.com/colyseus/colyseus/issues/433
