### ISSUE TITLE
Lobby Room and Relay Room for clients other than Javascript

### ISSUE THREAD

**Issue by tonygiang** [colyseus/colyseus#378]
The [documentation](https://docs.colyseus.io/builtin-rooms/lobby/) for the built-in Lobby room shows how to join or create a Lobby room from a Javascript client, but it's not clear how to do this from other clients. Please clarify. The example code for Lobby room looks very different from other types of room since it does not require a schema, hence our method for other types of rooms does not apply.

Update: On Colyseus' .NET client, the following line of code would throw an `InvalidCastException`:
```
Colyseus.Client client = new Colyseus.Client(EndPoint);
Colyseus.Room<dynamic> room = await client.JoinOrCreate("lobby");
```
On the server, lobby is defined like this:
```
import { Server, LobbyRoom } from "colyseus";
gameServer.define("lobby", LobbyRoom);
```

Update: This is also an issue with [Relay Room](https://docs.colyseus.io/builtin-rooms/relay/).

**Comment by kitakun** [comment]
I suggest you have static syntax on the client-side instead of dynamics.
For example:
```
Colyseus.Client client = new Colyseus.Client(EndPoint);
CurrentRoom = await client.JoinOrCreate<GameState>("lobby");
```
That works for me perfectly.

**Comment by tonygiang** [comment]
> 
> 
> I suggest you have static syntax on the client-side instead of dynamics.
> For example:
> 
> ```
> Colyseus.Client client = new Colyseus.Client(EndPoint);
> CurrentRoom = await client.JoinOrCreate<GameState>("lobby");
> ```
> 
> That works for me perfectly.

This cannot be done with the built-in Lobby Room because there is no Lobby Room state provided by the Client.
