### ISSUE TITLE
how to create rooms with my own Room.id?

### ISSUE THREAD

**Issue by sunq0001** [colyseus/colyseus#379]
i found that all room id is generated automatically, such as  `"id":"pc_SOfe8u"`, and so as session id such as `"sessionId":"xYrMyDFdH"`,  and also websocket url:  `connection":{"url":"ws://localhost:2567/1O39f7sxi/pc_SOfe8u?sessionId=xYrMyDFdH"` .

it seems that i can't control or manage this information on my own.  if i want to issue  my own customized room.id, session.id or url,    how to do?

**Comment by endel** [comment]
Hi @sunq0001 👋 This has been answered recently here: https://github.com/colyseus/colyseus/issues/376#issuecomment-730273780
