### ISSUE TITLE
Retrieving room states without joining rooms

### ISSUE THREAD

**Issue by tonygiang** [colyseus/colyseus#380]
How do we retrieve the state of a room without joining it? In our game, we'd like to match players within a range of power level differences to each other. Since such information is saved in the custom room state that we define, we must be able to retrieve that information before we let players join.

Currently, there is no way to do this on client or server. Calling `Client.GetAvailableRooms` from a .NET client only returns the most basic information: number of clients, max clients, room name, room ID and process ID.

**Comment by endel** [comment]
The room's "metadata" is the only public information you can access during room listing https://docs.colyseus.io/server/room/#setmetadata-metadata

**Comment by tonygiang** [comment]
I have so many questions.
What are the rules for defining metadata class client-side? What data types are accepted? Do the class names for Metadata have to be that exactly down to the capitalization? How do we read room metadata from with the room itself? I see one `setMetadata` method in the documentation but no method or field to read it.
