### ISSUE TITLE
schema-codegen with --namespace parameter generates Exception during handshake on client

### ISSUE THREAD

**Issue by tonygiang** [colyseus/colyseus#382]
A schema generated by `schema-codegen` with optional namespace will throw an Exception with the following message:

`Local schema mismatch from server. Use "schema-codegen" to generate up-to-date local definitions.`

Schemas generated without namespace continue to work as expected. This issue was tested on a Unity client. I have not tested this on other clients.

Update: The command I used to generate a namespaced schema was: `npx schema-codegen src\rooms\schema\LobbyRoomState.ts --csharp --output src --namespace PvP`

**Comment by endel** [comment]
Hi @tonygiang, I've just created this to clarify and track the status of this issue https://github.com/colyseus/colyseus-unity3d/issues/131 

Is that what's happening to you? Cheers!

**Comment by tonygiang** [comment]
I'm not clear what's the relation between namespaced schemas and `Context`. I'll try it out to see if it produces a different outcome or not.

**Comment by endel** [comment]
Thanks for reporting, going to close here as this is related to the Unity client, and progress will continue on https://github.com/colyseus/colyseus-unity3d/issues/131
