### ISSUE TITLE
schema-codegen does not generate fields correctly when using an imported custom type decorator

### ISSUE THREAD

**Issue by tonygiang** [colyseus/colyseus#383]
Normally, `schema-codegen` works correctly with a schema like this:

```
import { Schema, type } from "@colyseus/schema";
export class CustomRoomState extends Schema {
  @type('string')
  AField: string;
}
```

This also works:

```
import { Schema, Context } from "@colyseus/schema";
const type = Context.create();
export class CustomRoomState extends Schema {
  @type('string')
  AField: string;
}
```

But when the custom type decorator created by Context is created in a different file and imported in, like this:

CustomNamespace.ts:

```
import { Context } from "@colyseus/schema";
const type = Context.create();
export { type };
```

CustomRoomState.ts:

```
import { Schema, Context } from "@colyseus/schema";
import * as CustomNamespace from "./CustomNamespace";
export class CustomRoomState extends Schema {
  @CustomNamespace.type('string')
  AField: string;
}
```

`schema-codegen` will generate an empty class with no field. However, the 3rd example to declare a schema here will not cause runtime issue, provided the schema that the client runs with still has the fields correctly (as if it was generated using the 1st or 2nd example). The issue is only with `schema-codegen` not being able to recognize imported custom type decorator.

**Comment by endel** [comment]
Hi @tonygiang, thanks for letting me know - this is probably not going to be fixed soon, but if you import the `type` directly (without wildcard) it should work fine:

```typescript
//  CustomNamespace.ts:
import { Context } from "@colyseus/schema";
export const type = Context.create();

//  CustomRoomState.ts:
import { type } from "./CustomNamespace";
...
```
