### ISSUE TITLE
Feature request: Official support for simulating onMessage events from a TypeScript server

### ISSUE THREAD

**Issue by tonygiang** [colyseus/colyseus#384]
For a lot of reasons, dev-test cycle included, we want to simulate the scenario of a client sending a message to a room without setting up an actual client. This can already be done in a TypeScript server via 2 workarounds:

1. Register a message type with a named function, put everything you need to do in that and invoke that. Example:

```
  onCreate(options: any) {
    this.onMessage('EndTurn', this.ProcessEndTurn);
  }
  ProcessEndTurn(client: Client, message: any): void { }
  SimulateEndTurn(): void { ProcessEndTurn(client, message); }
```

2. Map each message type to a Node's `EventEmitter`, add listeners to that and invoke that. Example:

```
import { EventEmitter } from "events";
[...]
  events = new EventEmitter();
  onCreate(options: any) {
    this.onMessage('EndTurn', (client: Client, message: any) => this.events.emit('EndTurn', client, message));
  }
  SimulateEndTurn(): void { this.events.emit('EndTurn', client, message); }
```

However, these workarounds have drawbacks: they don't have support for the `*` wildcard. Workaround 2 only supports messages of type `string`, messages of type `number` will not map to `EventEmitter`.

But more importantly, they create unnecessary boilerplate when compared to a plain JavaScript server, where this feature is already supported by calling `this.onMessageHandlers['EndTurn'](client, message)`.

`onMessageHandlers` is not a real private JavaScript field since it's not prefixed by `#`. Hence, the only thing standing in the way of this feature for TypeScript is the `private` declaration for this field in `Room`'s type declaration.

A working type declaration for `onMessageHandlers` can be:

```
onMessageHandlers: {
  [messageType: string]: (client: Client, message: T) => void,
  [messageType: number]: (client: Client, message: T) => void
}
```

**Comment by tonygiang** [comment]
I'm unfamiliar with the Command pattern myself so I don't have much to comment on it. 

The feature request I'm proposing is simply going for the least-boilerplate approach that's already possible in plain JavaScript. Having a simulated `Client` would help too, so that the actual callbacks for `onMessage` don't have to receive `null` as the first argument and perform null-check inside it.

**Comment by endel** [comment]
We now have a `@colyseus/testing` utility for testing! More info https://github.com/colyseus/colyseus/issues/229#issuecomment-883568485
