### ISSUE TITLE
Feature request: onBeforePatch callback for Room

### ISSUE THREAD

**Issue by tonygiang** [colyseus/colyseus#385]
I'm requesting an additional `onBeforePatch` callback that would be called right before each time the room state is sent to the clients in a room. This allows us to modify or read the room state before it is synchronized. Use case: error-correction, server-controlled AI behaviour, analytics logging, other automated processes that can be plugged in/out at will on runtime.

Implementation question: could this callback be `await`ed under the hood?

**Comment by endel** [comment]
Hi @tonygiang, 

Sounds like this could be helpful indeed! You are referring to the addition of `onBeforePatch` on the client-side, right?

Allowing to also `await` for `onBeforePatch` would complicate things - as we'd need to handle a queue of incoming messages internally while `onBeforePatch` hasn't finished.

I agree on having an `onBeforePatch` without the `await` lock

**Comment by tonygiang** [comment]
I'm referring to the addition of `onBeforePatch` on the server-side. State patching is server-authoritative, after all.
