### ISSUE TITLE
RedisPresence may cause memory leak

### ISSUE THREAD

**Issue by amit-gshe** [colyseus/colyseus#386]
When colyseus was used in scenes that have so many rooms created and disposed, the ipc created subscriptions in redis presence, when room get disposed, the relevant redis connections was unsubscribed but the `subscriptions` map entries were not deleted. this `subscriptions` map get increased gradually and the topic string object and empty array object get stuck in memory then finally caused memory leak. 

![image](https://user-images.githubusercontent.com/7383028/101312472-ccf43500-388e-11eb-8703-3aef1933ea6b.png)

**Comment by endel** [comment]
Thanks for taking the time to inspect and report @amit-gshe 🎉
