### ISSUE TITLE
Redis presence not lapsing over time - collects dead servers

### ISSUE THREAD

**Issue by lee-orr** [colyseus/colyseus#389]
When running my colyseus server on locally (on WSL), the IP address to reach it changes each time I restart my machine. However, the Redis server (running on docker) never loses the old registrations, making it hard for my API (running as a separate process) to know which servers are real and which aren't.

## Steps to Reproduce (for bugs)

1. Set up a project with `npm init colyseus`
2. Enable redis presence on a server
3. Run the project and then shut it down
4. Check the redis registrations, even a day or two later - you will still see that old registration there.

## Context
In my situation, I'm using a separate API to balance load between Colyseus servers. ATM (very early in dev), locally, there is only one server - but once I deploy to a staging environment there will be more. The main issue is that my API can't differentiate between active server addresses & in-active server addresses in the Redis presence, since they never expire, so I need to manually go and delete the registrations. Ideally, there would be a configurable expiry for these registrations, that would be included using the Redis built-in expiry mechanisms, and the Colyseus server would re-register slightly before expiration.

## Your Environment

* Colyseus Version: 0.14.2
* Node.js Version: 15.0.1
* Operating System and version: Ubuntu 20.04 running on WSL
* Link to your project:

**Comment by endel** [comment]
Hi @lee-orr, thanks for reporting.

I think this problem happens only on **ungraceful** process shutdowns, right?  When the process goes down, it _should_ unregister itself from both `roomcount` and `colyseus:nodes` keys (https://github.com/colyseus/colyseus/issues/318#issuecomment-608084651)

`roomcount` is a hashset, and `colyseus:nodes` is a set - these Redis structures do not support setting an expiration per value, so we can't use key expiration as an approach here. 

Maybe we can add more sanity checks when firing up new instances, to make sure they're all responding

**Comment by lee-orr** [comment]
Looks like you're correct...
Is there a way to add a timestamp w/ the last registration time to the string we use to register (along w/ process ID & ip)? If we did that it would at least allow for easy cleanup of old registrations.

**Comment by mramadhanrh** [comment]
Any update or workaround for now?

**Comment by endel** [comment]
Hi @mramadhanrh,

@mobyjames has created a pull request (https://github.com/colyseus/proxy/pull/10) to fix this some days ago https://github.com/colyseus/proxy/pull/10, which I've just merged and is now available on version 0.12.3 of the proxy! https://www.npmjs.com/package/@colyseus/proxy

If Redis has bad entries on it, his solution was to remove them "on the go" and try again. Please let us know if that works for you!

**Comment by mramadhanrh** [comment]
> Hi @mramadhanrh,
> 
> @mobyjames has created a pull request ([colyseus/proxy#10](https://github.com/colyseus/proxy/pull/10)) to fix this some days ago [colyseus/proxy#10](https://github.com/colyseus/proxy/pull/10), which I've just merged and is now available on version 0.12.3 of the proxy! https://www.npmjs.com/package/@colyseus/proxy
> 
> If Redis has bad entries on it, his solution was to remove them "on the go" and try again. Please let us know if that works for you!

Great, thank you, will try this
