### ISSUE TITLE
How to listen to state change on server side

### ISSUE THREAD

**Issue by FeoniX97** [colyseus/colyseus#391]
How do I listen to state change on server side? 
There seems does not have any documentation on this, I have tried the following in `constructor of Schema class` but does not work:
`
this.onChange = (changes: DataChange<any>[]) => {
      console.log("123");
    };
`

**Comment by endel** [comment]
Hi @FeoniX97, it is not possible to listen for mutations from the server-side. The server-side is the one performing the mutations, therefore if you need any additional tasks to be performed along with the mutation, you can execute them right away yourself, without callbacks. Cheers
