### ISSUE TITLE
split room to different node server 

### ISSUE THREAD

**Issue by 6wukong6** [colyseus/colyseus#393]
index1.ts:
```javascript
gameServer.define('my_room', MyRoom);
```
index2.ts:
```javascript
gameServer.define('ranked', RankedLobbyRoom);
```
pm2:
```javascript
/* PM2 config file */

module.exports = {
    apps: [
        {
            name: 'colyseus-app-1',
            script: 'index1.ts',
            exec_interpreter: "ts-node",
            watch: false,
            instances: 1,
            exec_mode: 'fork',
            port: 8080,
            env: {
                NODE_ENV: 'development',
                DEBUG: 'colyseus:errors,colyseus:matchmaking'
            },
        },
        /**
         * Colyseus processes
         */
        {
            name: 'colyseus-app-2',
            script: 'index2.ts',
            exec_interpreter: "ts-node",
            watch: false,
            instances: 1,
            exec_mode: 'fork',
            port: 8090,
            env: {
                NODE_ENV: 'development',
                DEBUG: 'colyseus:errors,colyseus:matchmaking'
            },
        },

        /**
         * Proxy process
         */
        {
            name: 'proxy',
            script: './node_modules/@colyseus/proxy/bin/proxy',
            instances: 1, // os.cpus().length,
            exec_mode: 'cluster',
            env: {
                // Required options:
                REDIS_URL: 'redis://:183a19e6b1e6e025@127.0.0.1:9030/0',

                // // SSL (optional)
                // SSL_KEY: "/Users/endel/.localhost-ssl/localhost.key",
                // SSL_CERT: "/Users/endel/.localhost-ssl/localhost.crt",
            }
        }],

};

```
when connected to proxy and call joinOrCreate(use colyseus.js) , it  report 
```javascript
Uncaught (in promise) Error: "ranked" not defined
```
but when i call create , it success , a little confused , why? thanks！

**Comment by 6wukong6** [comment]
The relevant code may be here：
```typescript
function getProxy (url: string) {
  let proxy: httpProxy | undefined;

  /**
   * Initialize proxy
   */
  const matchedProcessId = url.match(/\/([a-zA-Z0-9\-_]+)\/[a-zA-Z0-9\-_]+\?/);
  if (matchedProcessId && matchedProcessId[1]) {
    proxy = processIds[matchedProcessId[1]];
  }

  if (proxy) {
    console.debug("Room is at proxy", proxies.indexOf(proxy));
    return proxy;

  } else {
    currProxy = (currProxy + 1) % proxies.length;
    console.debug("Using proxy", currProxy, url);
    return proxies[currProxy];
  }
}
```

**Comment by endel** [comment]
Hi @6wukong6, this behavior you're expecting does not work out of the box with Colyseus. All rooms should be `.define()`'d, so the entire cluster is aware of them. The creation of new rooms happens on the process with the least amount of rooms when using proxy + Redis. Cheers!

**Comment by 6wukong6** [comment]
Hi @endel , thank you for your reply and created a great framework . My scenario is that a specific server runs a specific room . The room is pre-created and does not need to be created by the client . Is there any suitable way to allow me to extend it myself, such as a plug-in method, which I can contribute to the community.Cheers!

**Comment by 6wukong6** [comment]
I think I can refer to colyseus monitor to make a plug-in for room query and allocation, and then find a way to store information about the room type supported by the process in redis, and the plug-in requests the specific process to create a room based on this information, and returns the client with Process ID/room ID/session ID, this plug-in is available in all processes, and the proxy can also work normally.What do you think of this idea?

**Comment by 6wukong6** [comment]
![image](https://user-images.githubusercontent.com/75993529/103660066-bdf0c780-4f9f-11eb-8c11-2c7ce59f88ab.png)
I found this code, which confirmed what you said : "The creation of new rooms happens on the process with the least amount of rooms when using proxy + Redis". So I need bypass the built-in http request to create a room and direct call 
```javascript
async function handleCreateRoom(roomName: string, clientOptions: ClientOptions): Promise<RoomListingData>
```
but it's not export.

**Comment by endel** [comment]
Hi @6wukong6, I'm going to close this as the framework currently does not provide (and there are no current plans to) support different nodes/servers to respond to **specific** type of rooms only. I'd suggest having a different server set up, and have different clusters (a specific mongodb and redis instance) for each of the clusters, so they are isolated and can handle their specific list of rooms without conflicting with each other.

If you're just starting out I'd suggest not even stress too much about this, though. Each room is very lightweight and shouldn't consume many resources from the machine.
