### ISSUE TITLE
ESM Support breaks webpack builds

### ISSUE THREAD

**Issue by tobspr** [colyseus/colyseus#406]
Introduced with this commit:
<https://github.com/colyseus/colyseus/commit/c98ba40a6badaff72162b1f7aa1a665d12503538>

**Issue**
My build breaks. The issue for example is that you are importing `commonjs` modules from `esm` (mjs) modules:

https://github.com/colyseus/colyseus/blob/master/src/Room.ts#L6

Webpack will not properly handle this call, and thus throw an error in the following line:
https://github.com/colyseus/colyseus/blob/master/src/Room.ts#L54

```TypeError: _gamestdio_timer__WEBPACK_IMPORTED_MODULE_2__ is not a constructor```

**Fix**

I think shipping mjs modules was a bit too early. However, in case you want to keep them, the fix would be as simple as (haven't tested it yet):

```
import { default as Clock } from "@gamestdio/timer";
```

There will probably rise a lot of other problems due to mixing mjs and commonjs though.

**Comment by endel** [comment]
Hi @tobspr, I couldn't reproduce this issue - does it happen if you use [webpack-node-externals](https://www.npmjs.com/package/webpack-node-externals)? 

```javascript
module.exports = {
    ...
    target: 'node',
    externals: [nodeExternals()],
    ...
};
```

**Comment by tobspr** [comment]
Hi endel,

Unfortunately webpack-node-externals breaks my entire build. I've ended up just forking the repo and using the last non-esm version

**Comment by tobspr** [comment]
For future references, a possible workaround is specifying this in the webpack config:

```
resolve: {
        mainFields: ["main", "module"],
}        
 ```
