### ISSUE TITLE
TypeError: this.players.set is not a function

### ISSUE THREAD

**Issue by joe-shields-mccann** [colyseus/colyseus#409]
Im getting the following error when trying to add a player to a room ''TypeError: this.players.set is not a function"

I have the following  room (some code removed for convenience)

```typescript
export class Player extends Schema {
    @type("string") nickname: string = "";
    @type("string") sessionId: string = "";
    @type("number") score: number = 0;
    @type("boolean") hasAnswered!: boolean;
}

export class GameState extends Schema {
    @type("boolean") gameStart: boolean = false;
    @type("number") minPlayers: number = 0;
    @type("number") reqPlayers: number = 0;
    @type("number") curRound: number = 0;
    @type({ map: Player }) players = new MapSchema<Player>();
}

export class Game1 extends Room<GameState> {
    onCreate(options: any) {
        this.setState(new GameState());

        this.state.minPlayers = 1;
        this.state.reqPlayers = 1;

        this.onMessage("*", (client, data) => {
        });
    }

    onAuth(client: Client, options: any, request: http.IncomingMessage) {
        return true;
    }

    onJoin(client: Client, options: any) {
        let player = new Player();
        player.sessionId = client.sessionId;
        player.nickname = options.nickname;

        this.state.players.set(client.sessionId, player); // error happening on this line
    }
}
```

I have also tried the method in the following example where the addPlayer method is in the state class but the same error occurs.
https://github.com/colyseus/colyseus-examples/blob/master/src/rooms/02-state-handler.ts

The state object appears to be getting set as the custom method is called it's just the 'set' method that seems to fail.

Any ideas?

Environment
* Colyseus Version: 0.14.13
* Node.js Version: 12.8.0
* Operating System and version: macOS 10.15.7

**Comment by endel** [comment]
@joe-shields-mccann shared his sources privately and `npm init colyseus-app` had a dependency issue back when the project was created.

```
npm install @colyseus/loadtest@latest --save
```

It was using an outdated `@colyseus/loadtest` version, which was then requiring an outdated version of `@colyseus/schema` - that does not implement `MapSchema#set`, and would cause other problems as well. Upgrading solves the problem!

Feel free to report if you happen to find any other problems! Cheers!
