### ISSUE TITLE
How to receive arena.env and development.env vars

### ISSUE THREAD

**Issue by ScreamZ** [colyseus/colyseus#410]
Hello,

I've added variables to the .env file but I'm unable to access them in the code, maybe you could help me ?

Thanks

**Comment by endel** [comment]
Hi @ScreamZ, if you created an application through `npm init colyseus-app`, the `development.env` variables are loaded by default through [dotenv](https://www.npmjs.com/package/dotenv), and they should be accessible through `process.env.YOUR_ENV_NAME`

**Comment by ScreamZ** [comment]
Wasn't working at some point, now it's okay, thanks :-)
