### ISSUE TITLE
yarn init doesn't work to create colyseus app

### ISSUE THREAD

**Issue by himat** [colyseus/colyseus#418]
The instructions say that you can run this to create a new project:
`npm init colyseus-app ./my-colyseus-app`

I prefer using yarn though, so I tried
`yarn init colyseus-app ./my-colyseus-app` but this didn't work, it just generated a package.json only

Is it possible to use yarn?

**Comment by endel** [comment]
Hi @himat! 

I've just made an update to ensure compatibility with `yarn`! Yarn uses `create` rather than `init`, though:

```
yarn create colyseus-app ./my-colyseus-app
```
