### ISSUE TITLE
[uwebsockets-transport] uWebSockets throwing uncaughtException when readBody Buffer is empty

### ISSUE THREAD

**Issue by Vidski** [colyseus/colyseus#422]
## Context
It sometimes happens when connecting a Client. (I'm using Unity)
I'm using a modified Colyseus MMO demo, upped the Colyseus Version to 0.14.20 and switched the Transport layer to uWebSockets.

Console:
`[ERROR] 21:58:13 TypeError: Cannot perform %TypedArray%.prototype.set on a detached ArrayBuffer
[error] : 2021-07-24 21:58:13 :  uncaughtException: Cannot perform %TypedArray%.prototype.set on a detached ArrayBuffer
TypeError: Cannot perform %TypedArray%.prototype.set on a detached ArrayBuffer
    at Buffer.set (<anonymous>)
    at _copyActual (node:buffer:255:3)
    at Function.concat (node:buffer:563:12)
    at F:\UnityProjects\colyseus-learning-server\node_modules\uwebsockets-express\src\Request.ts:138:30
    at topLevelDomainCallback (node:domain:147:15)
    at callbackTrampoline (node:internal/async_hooks:130:14)
TypeError: Cannot perform %TypedArray%.prototype.set on a detached ArrayBuffer
    at Buffer.set (<anonymous>)
    at _copyActual (node:buffer:255:3)
    at Function.concat (node:buffer:563:12)
    at F:\UnityProjects\colyseus-learning-server\node_modules\uwebsockets-express\src\Request.ts:138:30
    at topLevelDomainCallback (node:domain:147:15)
    at callbackTrampoline (node:internal/async_hooks:130:14)
`

Debugger:
https://imgur.com/a/uYZbsGD

My workaroud:
`
        if (body.length === 0)
          return;
`

## Your Environment
* Colyseus Version: 0.14.20
* Node.js Version: 14.17.3 LTS
* Operating System and version: Windows 10
* Link to your project: Colyseus MMO Demo

**Comment by endel** [comment]
Hi @Vidski, thank you for reporting! I just tried uWebSockets.js in the MMO project again but failed to reproduce this issue.

By the error, it looks like uWebSockets.js is dropping the ArrayBuffer reference before it is used in `Buffer.concat()`.

I'm afraid your workaround may discard valid request bodies, as the `readBody()` is only called if the body has content https://github.com/endel/uWebSockets-express/blob/1dd11f2b7ee35509d7336cd6a2c4373395d6ccf7/src/index.ts#L159

Does the error happen on a specific request, and/or specific body contents sent in the request? E.g. only during "login", or only during "register" (Please do not share your password though 😅 )

If you can provide more details it would help, cheers!

**Comment by Vidski** [comment]
Hi @endel, I'm using `QuickSignIn()` https://github.com/colyseus/unity-demo-mmo/blob/master/ColyseusTechDemo-MMO/Assets/Scripts/Managers/MMOManager.cs#L85 just like that on `Start()`. I noticed that it only happens when doing it that way. I tried quickly leaving and reconnecting in `Update()` but it never happens there.  I also noticed, that it is calling `readBody()` twice with just 1 UnityWebRequest, but the first arrayBuffer is empty and `isLast = false`, and the package after this is with an arrayBuffer > 0 and `isLast = true`. 

If you are interested in a live debug, just DM me on discord.

**Comment by Vidski** [comment]
Hi @endel, made some tests to find out what exactly is happening. 
When sending an request with `arrayBuffer.length = 0` and `isLast = false`, the buffer (_body_) will be dropped in the next step where `isLast = true`. 

Current workaround:
```
if (body.length == 0) {
  body = Buffer.from(body);
}
body = body ? Buffer.concat([body, chunk]) : chunk; // body is actually an empty Buffer{} but somehow gets dropped when calling Buffer.concat
```

**Comment by endel** [comment]
Thanks for the PR here https://github.com/endel/uWebSockets-express/pull/10 @Vidski <3 

The latest version of `uwebsockets-express` also fixes https://github.com/endel/uWebSockets-express/issues/9 and potential errors due to client-side aborting the request.

Feel free to re-open if this persists! Cheers!
