### ISSUE TITLE
Match-maker: RoomListingData returns wrong number of clients after client reconnect

### ISSUE THREAD

**Issue by CookedApps** [colyseus/colyseus#423]
After implementing client reconnect, I noticed that the connections count in the Colyseus monitor is wrong after a client successfully reconnected to a room. For each successful reconnect, the connection count is decremented by one. Reconnecting multiple times can result in negative connection counts. Inspecting the room yields the correct connection count.

Digging through the code showed me that the endpoint simply displays the [match-maker query](https://github.com/colyseus/colyseus/blob/1cc243b63f3398d525c17260c3f013dd08b00451/packages/core/src/MatchMaker.ts#L132). So I suspect a bug in the match.-maker itself.

## Steps to Reproduce
1. Connect to a room and go to the Colyseus Monitor: "1 Connection" 
2. Client loses connection and successfully reconnects using `client.reconnect()`
3. Go to Colyseus Monitor again: "0 Connections" but the room still exists
4. Click on the room: "1 Connection" (which is correct)

![Colyseus Monitor](https://i.imgur.com/MX6BIqt.png)

## Context

Trying to implement client reconnect with the standard procedure as stated in the docs.

## Your Environment

* Colyseus Version: 0.14.20
* Colyseus.js Version: 0.14.13
* Colyseus Monitor Version: 0.14.20
* Node.js Version: 14.15.3
* Operating System and version: Linux Mint 20.2 (Kernel 5.8.0)

**Comment by endel** [comment]
Hi @CookedApps, 

Thanks for reporting, I couldn't reproduce locally, though. Can you share more details on how you approached testing?
- Are you using a specific matchmaking driver? (mongoose or redis?)
- Are you using the loadtest tool?

Cheers!

**Comment by CookedApps** [comment]
Hey @endel, 

I tested it running the Colyseus server (with the monitor) locally as well as the game's frontend. I then connected to the game via my laptop running on the same network and triggered a connection loss by disconnecting the Wi-Fi. The game client reconnects after the Wi-Fi is turned on again. After the reconnect, the connection count is incorrect.

Regarding your questions: Nope and nope.

**Comment by endel** [comment]
Hi @CookedApps, I've tried exactly as you described and still couldn't reproduce, unfortunately. 

If you can provide a reproducible scenario with source code it would be nice! Cheers!

**Comment by lpsandaruwan** [comment]
Hi @CookedApps and @endel,

I could not reproduce this issue. I tried with 2 external clients. Numbers were correct.

**Comment by CookedApps** [comment]
@endel We are still experiencing this issue, even on our live systems. So it's probably related to our implementation. Since I don't know what's causing the problem, I can offer to invite you to our GitLab group, and you take a look at the code yourself. Or give me a hint which parts of the code you would like to see, and I'll post it here.

**Comment by endel** [comment]
Hi @CookedApps, if you don't mind sharing, my username on GitLab is "endel"

**Comment by CookedApps** [comment]
@endel Alright. I'll invite you and send you a pm on Discord.

**Comment by lpsandaruwan** [comment]
Hi @endel and @CookedApps,
I found out that the way we use to resolve allowReconnect() in server effects on client number on monitoring dashboard.
i.e. If you do it like below reconnected connection is displaying wrong.
```
  onLeave (client: Client, consented: boolean) {
    if(!consented) {
      this.allowReconnection(client).then((r) => {
        console.log(r);
      }).catch((err:any) => {
        console.log(err);
      });
    }
  }
```
But when I use the allowReconnection like below, numbers are correct after reconnecting.
```
  async onLeave (client: Client, consented: boolean) {
    if(!consented) {
      await this.allowReconnection(client);
    }
  }
```
I will investigate for a possible fix.

**Comment by CookedApps** [comment]
@lpsandaruwan Interesting. We do it like in your first example. That explains it.

**Comment by lpsandaruwan** [comment]
Investigated few fixes on allowReconnect and could not succeeded :-( . For reproducing #423 and #348 I've created this repository, [https://github.com/lpsandaruwan/colyseus-bug-423-and-348-reproducing](https://github.com/lpsandaruwan/colyseus-bug-423-and-348-reproducing).

**Comment by endel** [comment]
Hi @CookedApps, is this still an issue?

**Comment by CookedApps** [comment]
@endel No, we switched to the aforementioned async / await syntax and that magically resolved the issue. 😄

**Comment by endel** [comment]
Yay, that's great! 🚀  Thank you!
