### ISSUE TITLE
Session expired issue when reconnect: Minimal test repository

### ISSUE THREAD

**Issue by arnaudgregoire** [colyseus/colyseus#424]
In my game, Im facing a reconnect issue :  Error: session expired: sessionId

When the user refresh my game page, i want to reconnect the user to the room he was previously connected to.
When i refresh the first time i get this error   Error: session expired: <sessionId>.
When i refresh a second time , i don't get the error anymore.

To reproduce it i created a js repo with https://github.com/colyseus/create-colyseus-app and the minimal modification to reproduce the behavior.

https://github.com/arnaudgregoire/testReconnect

Basically, i just added a index.html with this code:

```js
let client = new Colyseus.Client('ws://localhost:2567');
let room;
let roomId;
let sessionId;

async function connect(){
    try {
    room = await client.joinOrCreate("my_room", {/* options */});
  
  } catch (e) {
    console.error("join error", e);
  }
}

connect().then(e=>{
    roomId = room.id;
    sessionId = room.sessionId;

    client = new Colyseus.Client('ws://localhost:2567'); // simulate a new page (refresh)

    client.reconnect(roomId, sessionId) //  Error: session expired: <the session id>
    .then(room=>{
        console.log('reconnected');
    });
});
```

**Comment by endel** [comment]
Hi @arnaudgregoire, 

In order to perform a `client.reconnect()` the server-side need to reach `.allowReconnection()`. This will only happen when the connection has been closed. You can simulate a real browser closing the connection by adding this line, and you'll that the reconnection is going to work:

```typescript
connect().then(e=>{
    roomId = room.id;
    sessionId = room.sessionId;

    // 
    // HERE ->
    // force connection to close / simulate tab closing
    // 
    room.connection.close(); 

    client = new Colyseus.Client('ws://localhost:2567'); // simulate a new page (refresh)

    client.reconnect(roomId, sessionId) //  Error: session expired: <the session id>
    .then(room=>{
        console.log('reconnected');
    });
});
```

The `localStorage` may not be available in some deployment/environments, so maybe `IndexedDB` can be an alternative to cache the `room.id`/`sessionId` if you need one.

Cheers!

**Comment by arnaudgregoire** [comment]
Thanks, i understand my mistake now.
As the react router dom does not really change the page when Link/Redirect,  the connection of the previous Colyseus.Client  was not really closed.
