### ISSUE TITLE
Database Support

### ISSUE THREAD

**Issue by sain801028** [colyseus/colyseus#425]
List:
postgresql https://www.postgresql.org/
supabase  https://supabase.io/
rethinkdb https://github.com/rethinkdb/rethinkdb
yugabyte https://www.yugabyte.com/

**Comment by Vidski** [comment]
Hi @sain801028, to my understanding, Colyseus won't provide any database support, thats up to you what you want to use. All of the solutions you linked do have javascript examples on how to implement them. 

I'm currently using psql with https://mikro-orm.io/ for my project. The [Unity MMO example](https://github.com/colyseus/unity-demo-mmo/tree/master/Server/src) provides a good example on how to use it. 

Best Regards,
Vidski

**Comment by endel** [comment]
As @Vidski said, Colyseus is just a Node.js library. You can check for the documentation regarding a specific database module you'd like to use and plug into the same Node.js application.
