### ISSUE TITLE
GitHub Workflow: publishing changed packages to NPM registry

### ISSUE THREAD

**Issue by endel** [colyseus/colyseus#431]
Now that we're using a monorepo & Lerna (https://github.com/colyseus/colyseus/pull/419) to manage internal Colyseus' packages, we need to establish a way to auto-publish updated packages on NPM.

As we are using [independent mode](https://github.com/lerna/lerna#independent-mode), each package can evolve on its own versioning numbers. Every `0.14.x` version should be compatible with each other. Once we introduce a breaking change - the core and all its internal packages are going to be bumped to the next version (e.g. `0.15.x`)

---

Lerna built-in versioning and publishing tools seems to be centered around a "fixed" version number for every package, not really friendly with the "independent" mode.

- Because of that, I'm currently having to manually run `npm publish` for each package that has been changed
  - _(a GitHub Workflow could handle this)_
- I manually update the `"version"` number of `package.json` for that package, too. 
  - _(This step is fine, it gives us control)_

As you can see, the `colyseus` bundle package uses `^` for specifying the version number of its dependencies. So if an internal package gets updated, (e.g. `"@colyseus/ws-transport"` is bumped to `0.14.99`) - it is optional for consumers if they want to upgrade it or not.
https://github.com/colyseus/colyseus/blob/a404b0fe9113392ed4c1cae7918ccd79aedc0350/bundles/colyseus/package.json#L34-L37

---

This thread has some useful information on approaches to take for "independent" versioning and CI: https://github.com/lerna/lerna/issues/1286

**Comment by lpsandaruwan** [comment]
Hi @endel 
Having a GitHub Workflow, to get changed packages using `lerna changed` and publish the changed packages keeping the version change in package.json as the trigger, will this approach work for you?

**Comment by endel** [comment]
Hi @lpsandaruwan, thanks for having a look at this. From what I've read on various GitHub issue conversations, the built-in lerna commands don't play nicely with its `"independent"` mode. 

For example: right now, if you run `lerna changed`, lerna is going to output every package

```
lerna info Looking for changed packages since 0.14.16
colyseus
@colyseus/arena
@colyseus/core
@colyseus/loadtest
@colyseus/monitor
@colyseus/testing
@colyseus/mongoose-driver
@colyseus/redis-driver
@colyseus/redis-presence
@colyseus/fossil-delta-serializer
@colyseus/uwebsockets-transport
@colyseus/ws-transport
```

---

The approach I was thinking we could use would be to check if the `"version"` field on any `package.json` has changed, and run `npm publish` for that single package if positive. 

I have a fork of a GitHub action that does exactly that (https://github.com/endel/npm-publish-action), maybe we can adapt this to work with the monorepo structure. (This fork is [currently in use for `colyseus.js`](https://github.com/colyseus/colyseus.js/blob/411e2740b7d9aef8d82bb6fc39cfb53927ea7d76/.github/workflows/npm-publish.yml#L23-L32), where [`"bump x.x.x"` commits are published](https://github.com/colyseus/colyseus.js/commit/411e2740b7d9aef8d82bb6fc39cfb53927ea7d76))

**Comment by endel** [comment]
It works 🎉 https://github.com/colyseus/colyseus/commit/8dd5b6407122cdcab362f5f534bad68eef1dda82

Thank you @lpsandaruwan 👏
