### ISSUE TITLE
Cannot find module 'timers/promises' when run loadtest

### ISSUE THREAD

**Issue by HiPanda-dev** [colyseus/colyseus#434]
Hello i'm newbie I just started testing colyseus for my project
when i run loadtest there is an Error

> Error: Cannot find module 'timers/promises'
> Require stack:
> - /root/proxy/pm2-example/node_modules/@colyseus/loadtest/build/index.js
> - /root/proxy/pm2-example/node_modules/@colyseus/loadtest/bin.js
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:745:27)
>     at Module.require (internal/modules/cjs/loader.js:961:19)
>     at require (internal/modules/cjs/helpers.js:92:18)
>     at Object.<anonymous> (/root/proxy/pm2-example/node_modules/@colyseus/loadtest/build/index.js:6:13)
>     at Module._compile (internal/modules/cjs/loader.js:1072:14)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
>     at Module.load (internal/modules/cjs/loader.js:937:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
>     at Module.require (internal/modules/cjs/loader.js:961:19)

I using:
node version 16.7.0
colyseus: "^0.14.12",

please help me, Thanks you

**Comment by endel** [comment]
Hi @HiPanda-dev, can you upgrade your `@colyseus/loadtest` to version `0.14.7`? 

```
npm install @colyseus/loadtest@latest --save-dev
```

The `timers/promises` dependency has been removed from it, as it is available starting from Node.js v15+, and we are currently supporting Node.js v14+

Cheers!
