### ISSUE TITLE
@colyseus/command failed to work with error message: "command is not a constructor"

### ISSUE THREAD

**Issue by hunglsxx** [colyseus/colyseus#435]
Hi,
I using colyseus version 0.14.9 and colyseus/command version 0.1.7. 
I using common javascript. 
My code below: 
![Screenshot from 2021-08-24 17-04-52](https://user-images.githubusercontent.com/50700597/130598434-ef2c1e69-1931-42cf-a0d7-f4bf8a1ce72d.png)

![Screenshot from 2021-08-24 17-04-05](https://user-images.githubusercontent.com/50700597/130598546-d1b07a15-b62b-4118-b1c0-7ab67fe8e9d9.png)

![Screenshot from 2021-08-24 17-06-09](https://user-images.githubusercontent.com/50700597/130598564-31071786-6bb2-4d5e-873b-4cfec342d4a7.png)

But when i'm run it get error message below:
![Screenshot from 2021-08-24 17-09-07](https://user-images.githubusercontent.com/50700597/130598836-ba728eee-32f8-4e05-9f8a-4120d51772b2.png)

Please help!
Many thanks

**Comment by endel** [comment]
Hi @hunglsxx, can you share how you're importing the command? Perhaps you're not importing `OnJoinCommand` properly:

```typescript
const { OnJoinCommand } = require('./command_path');
```

**Comment by hunglsxx** [comment]
@endel yes. i just copy sample code from document and get error. 
Many thanks for your reply, it's work for me! 
![Screenshot from 2021-08-24 23-21-47](https://user-images.githubusercontent.com/50700597/130653406-8fe30d20-5dc9-4de4-b8f8-3077c42e435f.png)
