### ISSUE TITLE
client that allowed for reconnection dont send any data

### ISSUE THREAD

**Issue by mehmetresatdilbaz** [colyseus/colyseus#436]
async onLeave (client: Client, consented: boolean) {
      // flag client as inactive for other users
      this.state.players.get(client.sessionId).connected = false;
    
      try {
        if (consented) {
            throw new Error("consented leave");
        }
    
        // allow disconnected client to reconnect into this room until 20 seconds
        await this.allowReconnection(client, 20);
    
        // client returned! let's re-activate it.
        this.state.players.get(client.sessionId).connected = true;

        client.send("reconnected", {data : "test"});
      

         } catch (e) {
    
        // 20 seconds expired. let's remove the client.
        this.state.players.delete(client.sessionId);
      }
    }

in that snippet, "client.send" never sends data to the correct client.

**Comment by akroshteotia** [comment]
this is related to https://github.com/colyseus/colyseus/issues/525
