### ISSUE TITLE
Allow to customize Access-Control-Allow-Headers passed to matchmake endpoint

### ISSUE THREAD

**Issue by JCMais** [colyseus/colyseus#439]
The value is currently static here: https://github.com/colyseus/colyseus/blob/bdf43169e509e0fd2305cd4a3b3669e7bf733c76/packages/core/src/Server.ts#L236-L247

If you use an instrumentation library (such as newrelic) it may add new headers , right now this is broken

## Steps to Reproduce (for bugs)
1. Enable any instrumentation library that add new headers to allow for CORS tracing 
2. Matchmake does not work anymore as we requested more headers than what was returned

See screenshot:

![image](https://user-images.githubusercontent.com/1041647/131159981-d3766f39-78cc-45ec-b202-931418d7ca05.png)

Notice the requested headers (`Access-Control-Request-Headers`) and the ones returned in the response (`Access-Control-Allow-Headers`)

## Context

Trying to enable the NewRelic browser monitoring agent

## Your Environment

* Colyseus Version: v0.14.20
* Node.js Version: v14
* Operating System and version: Ubuntu

**Comment by endel** [comment]
Hi @JCMais, this has been taken care of on the upcoming 0.15 version 🤞  https://github.com/colyseus/colyseus/blob/3d6624239fa89e856aea2d1b82ac49d8647aedbb/packages/transport/uwebsockets-transport/src/uWebSocketsTransport.ts#L179
