### ISSUE TITLE
Custom logger support

### ISSUE THREAD

**Issue by endel** [colyseus/colyseus#442]
Original report by @MCArth:

>  what might be an interesting addition to the engine would be the ability to set logging levels of colyseus (and then there be an 'error only' level which excludes this/seat reservation expired that could be called warnings or something)
> but that's a lot of work and tbh I should just set up my own logging system haha

---

The disadvantage of using `console.log` directly inside the Colyseus' codebase (which we currently do) is that all internal logs are forcibly going to go to stdout, making it not possible to easily forward logs and errors to external services.

We can do exactly as the web framework [fastify](https://github.com/fastify/fastify): use a small [abstract-logging](https://www.npmjs.com/package/abstract-logging) library for logs, and default it to `console` to keep current functionality.

There are quite a few logging frameworks available for Node.js, such as [`winston`](https://www.npmjs.com/package/winston), [`bunyan`](https://www.npmjs.com/package/bunyan), [`pino`](https://www.npmjs.com/package/pino), etc. By using an abstract logger, end-users could provide whichever logging library they prefer:

**Example providing a `pino` logger:**

```typescript
import pino from "pino";
const transport = pino.transport({
  target: 'some-transport',
  options: { some: 'options for', the: 'transport' }
})
const logger = pino(transport);

const server = new Server({
  // provide the custom logger. 
  // default: console
  logger: logger,
});
```

**Comment by lpsandaruwan** [comment]
Hi @endel,

Thinking about adding a singleton class for this purpose. There users can set their custom logger by passing the instance to this singleton. If no logger instance provided by default it will print to stdout.
i.e.
Setting a custom logger,
```
import * as winston from 'winston';
import Logger from "@colyseus/core/Logger"

const logger: winston.Logger = winston.createLogger({
    format: winston.format.combine(
        winston.format.timestamp(),
        winston.format.json(),
    ),
    level: 'info',
    transports: [
        new winston.transports.File({ filename: 'error.log', level: 'error' }),
        new winston.transports.File({ filename: 'all.log' }),
    ],
});

Logger.setLogger(logger)
```

Using the logger,
```
import Logger from "@colyseus/core/Logger"

private log = Logger.getLogger();

const yourFunction = () => {
  log.info("your messages");
}
```
What do you think of this approach?

**Comment by endel** [comment]
Hi @lpsandaruwan, sounds good to me! Can we also have it optional in the `Server` constructor? Then all Colyseus configurations can be provided from a single place.

**Comment by lpsandaruwan** [comment]
Thank you. Will do it that way. :+1:
