### ISSUE TITLE
Allow mapped access to `this.clients` via their sessionId.

### ISSUE THREAD

**Issue by endel** [colyseus/colyseus#443]
A recurring and really helpful feature request is to allow to directly get a client reference by its `sessionId` property.

Currently, this is the implementation to retrieve a client by its `sessionId`:

```typescript
function getClientBySessionId(sessionId) {
  return this.clients.find(client => client.sessionId === sessionId);
}
```

It would be very handy if we allow accessing a client directly by their id using `this.clients[client.sessionId]`.

---

**Notes**

- We still need to store the client list as an array, as it is the fastest JavaScript structure we can [loop through](https://github.com/colyseus/colyseus/blob/8dd5b6407122cdcab362f5f534bad68eef1dda82/packages/core/src/Room.ts#L464-L471).
- We can experiment with having a custom `Array` implementation for `this.clients` that also holds its entries in a regular object key pair.

**Comment by vitalyrotari** [comment]
why not to use Map instead of Array? I think this will not have big impact to performance.
