### ISSUE TITLE
Register serializer for testing library

### ISSUE THREAD

**Issue by YoussefEgla** [colyseus/colyseus#446]
## Context

At my company we use a different serializer than `SchemaSerializer` because we have integration with a mobile app, everything works fine but we currently can't utilize the testing library because `registerSerializer` function isn't exported.

It will be really great if we can register a new serializer for the client used by the testing library

## Your Environment

* Colyseus Testing library Version: 0.14.22 
* Node.js Version: 14

**Comment by endel** [comment]
Hi @YoussefEgla, just replied to you on your pull request!

Your use case sound very interesting. Would you mind sharing with us what motivated you to write your own serializer, and how you approached it?

Cheers!

**Comment by YoussefEgla** [comment]
We decided to use different serializer because implementing SchemaSerializer would take more time in swift.

Our case is a mobile app with SwiftUI and Web and both have Unity integrations where colyseus is used as the matchmaking server and sync changes outside Unity builds
