### ISSUE TITLE
ReferenceError: room is not defined 

### ISSUE THREAD

**Issue by Raam124** [colyseus/colyseus#448]
I'm getting this error when trying the Javascript example in expressjs

ReferenceError: room is not defined 

Code I'm trying out is 

```
import * as Colyseus from "colyseus.js"; 

var client = new Colyseus.Client('ws://localhost:2567');

try {
  const room = await client.onCreate("game",{
    name:"raam"
  });
}
catch(e){
  console.log("cant join");
  console.log(e);
}
```

Colyseus Server is running  in  ws://localhost:2567 fine

**Comment by endel** [comment]
Hi @Raam124, I see two small problems on the code you shared:

- `client.onCreate` should be `client.joinOrCreate`
- The `const` (and `let`) keyword declares a variable tied to the scope of its declaration. This means that `room` is only available inside your `try` block.

Try this instead:

```typescript
import * as Colyseus from "colyseus.js"; 

var client = new Colyseus.Client('ws://localhost:2567');
var room;

try {
  room = await client.joinOrCreate("game",{
    name:"raam"
  });
}
catch(e){
  console.log("cant join");
  console.log(e);
}
```
