### ISSUE TITLE
ENOENT on player disconnect

### ISSUE THREAD

**Issue by hatala91** [colyseus/colyseus#449]
- [x] Your issue may already be reported! Please search on the [issue tracker](../) before creating one.

## Steps to Reproduce (for bugs)

1. Import `@geckos.io/phaser-on-nodejs` and `phaser` in server side room
2. In the `onCreate` function, create a new phaser game
3. Have a client `joinOrCreate`
4. Disconnect the client

## Context

Trying to run Phaser 3 as an authoritative server with arcade physics using geckos.io. Unfortunately, whenever a client disconnects the whole server breaks with this error:

```
Error: ENOENT: no such file or directory, open '.../node_modules/@geckos.io/phaser-on-nodejs/lib/node:internal/stream_base_commons'
```

I checked and both `onLeave` and (if it's the last player in the room) `onDispose` are called before this error occurs.

Also, while I did not find much info about this error during my research, the `node:internal/stream_base_commons` seems to be connected to websockets. I just do not understand how this relates to Phaser/ geckos.io.

## Your Environment

* Colyseus Version: 0.14.22
* Node.js Version: 16.6.2
* Operating System and version: macOS Big Sur 11.5.2

**Comment by endel** [comment]
Hi @hatala91!

By the error message, this seems to be coming from `@geckos.io/phaser-on-nodejs` package. Having a quick search of the error I found this thread, but I don't know what this error may be: https://github.com/nodejs/node/issues/23169

Can you share a repository where this error is reproducible? Cheers!

**Comment by hatala91** [comment]
Good evening!

Thanks for looking into this. I setup a repo to reproduce this: https://github.com/hatala91/lizard-arena
While doing so I figured that this only seems to happen when serving using `ts-node-dev` 🤦 

For completeness sake, here is the steps to reproduce:
1. `npm ci`
2. `npm run serve`
3. Browser Tab -> http://0.0.0.0:8080/
4. Close Browser Tab

Thanks 🙏
