### ISSUE TITLE
[Feature Requests] Support generics in schemas

### ISSUE THREAD

**Issue by rnd256** [colyseus/colyseus#450]
My goal would be, with the example code below, we'd be able to use `MyConcreteClass` or `MyGenericClass<MyData>` in the Schema, and have both the server and client able to access `myClass.myValue.text` without needing to manually cast the type or use the `any` type.

```ts
class MyGenericClass<T> extends Schema {
  @type(T)
  public readonly myValue: T;

  @type([T])
  public readonly myArray: ArraySchema<T>;

  @type({ map: T })
  public readonly myMap: MapSchema<T>;
}

class MyConcreteClass extends MyGenericClass<MyData> {}

class MyData extends Schema {
  @type(string)
  public readonly text: string;
}
```

**Comment by endel** [comment]
Hi @rnd256, 

Unfortunately it is not possible to share TypeScript types to the runtime this way. The `@type(T)` turns into actual JavaScript method call (a decorator), whereas `: ArraySchema<T>` is just visible during compile-time for TypeScript.

What you can do is define the schema fields of a base type, and use a concrete type extending from it. Using TypeScript you can actually force the compiler to accept the concrete type using generics (similar to what you're proposing here!), check this example:

```typescript
class BaseClass extends Schema {}
class ConcreteClass extends BaseClass {
  @type("string") customField: string;
}

class MyState<T extends BaseClass> extends Schema {
  @type(BaseClass)
  myValue: T;

  @type([BaseClass])
  myArray = new ArraySchema<T>();

  @type({ map: BaseClass })
  myMap = new MapSchema<T>();
}

const state = new MyState<ConcreteClass>();
state.myValue = new ConcreteClass();
state.myValue.customField = "hello world!"

state.myArray.push(new ConcreteClass().assign({customField: "one"}))
state.myMap.set("one", new ConcreteClass().assign({customField: "one"}));

// nN need to typecast here
console.log(state.myValue.customField);
console.log(state.myArray[0].customField);
console.log(state.myMap.get("one").customField);
```

From C# the typecasting would still be required, though. 🤔

**Comment by rnd256** [comment]
Thanks, that's an interesting approach. Since the schema C# code generator will still generate a file for `ConcreteClass`, maybe having to cast to that in C# isn't the worst. There are already other things that need to be casted/converted in C#, like enums that get transmitted as strings, so this could be handled similarly.

But will the Colyseus server actually send all the data from `ConcreteClass`, even though its type is only labelled as `BaseClass`? I had assumed that Colyseus would ignore sending `customField` in that case.

**Comment by endel** [comment]
> But will the Colyseus server actually send all the data from ConcreteClass, even though its type is only labelled as BaseClass? I had assumed that Colyseus would ignore sending customField in that case.

Yes, it will! When encoding ADD operations, the encoder tries to encode the internal `typeid` in case it differs from original type: https://github.com/colyseus/schema/blob/856cdb42d8c6098d66ceb4b22806d9db0341682f/src/Schema.ts#L612-L614

--- 

If you have any ideas on how to improve this somehow on the C# side just let me know! Otherwise I think we can close this 😇

**Comment by rnd256** [comment]
Awesome, thank you!

Yeah, that's tricky and I don't have a better idea right now. Luckily the casting workaround should work fine.
