### ISSUE TITLE
Reconnect with empty string as sessionId

### ISSUE THREAD

**Issue by Shadowlauch** [colyseus/colyseus#455]
(First of all thank you to all the contributers, I love working with colyseus!)

I found some behavior that surprised me, I'm not sure if this behavior is intended, but if I use reconnect with an empty string as the sessionId it will just join the server normally and not throw any errors.

**Comment by endel** [comment]
Hi @Shadowlauch, interesting, thanks for letting us know! 

I've moved this issue to the main server repo as this sounds more of a server problem

**Comment by endel** [comment]
Fixed on https://github.com/colyseus/colyseus/pull/478
