### ISSUE TITLE
Issue with scaling when using uWebSockets transport

### ISSUE THREAD

**Issue by proficientwizard** [colyseus/colyseus#458]
## Steps to Reproduce (for bugs)
Follow the scaling guide in official docs (https://docs.colyseus.io/colyseus/scalability/) but use `@colyseus/uwebsockets-transport` instead of `@colyseus/ws-transport`.

## Context
Colyseus instances do not register themselves into redis presence, thus proxy couldn't discover them.

I looked into the source code why this issue happens and it seems cause of the issues lies here:
https://github.com/colyseus/colyseus/blob/master/packages/core/src/Server.ts#L102-L105

Because `uwebsockets-transport` does not have `server` property so per the logic above and call to `registerProcessForDiscovery` will be skipped, which means colyseus instances do not register itself into redis server and proxy not able to discover them.

## Your Environment
* Colyseus Version: 0.14.23
* Node.js Version: Node v16
* Operating System and version: Windows 10

**Comment by endel** [comment]
Closing as fixed on 0.15
