### ISSUE TITLE
options.verifyClient

### ISSUE THREAD

**Issue by truongan2000pro** [colyseus/colyseus#469]
this is my server code 
`const gameServer = new Server({
  transport: new WebSocketTransport({
    server, // provide the custom server for `WebSocketTransport`
    verifyClient: (info?:object,next?:any) => {
      console.log(info);
      // next(false)
    },
  }),
});`

How can I catch the user info whenever they go to my Server using verifyClient? 
I have tested in client use client.auth.login but it went to route "/auth"   

Someone please show me how to get verifyClient info whenever they go to my server

**Comment by endel** [comment]
Hi @truongan2000pro, 

The `verifyClient` option is part of the default WebSocket server implementation. The `verifyClient` method is only triggered when establishing a WebSocket connection (during the "upgrade" phase), and not during regular HTTP routes.

(Please keep in mind that the `@colyseus/social` module is being deprecated, we're not going to bring updates for it as it currently is)

Maybe what you're looking for is the room's `onAuth` method https://docs.colyseus.io/colyseus/server/room/#onauth-client-options-request

Hope this helps, cheers!
