### ISSUE TITLE
export handleCreateRoom function to force create room for the current process

### ISSUE THREAD

**Issue by 04116** [colyseus/colyseus#481]
https://github.com/colyseus/colyseus/blob/0dc966f9f3e161c63a7929486beaa8a6e11a7e2d/packages/core/src/MatchMaker.ts#L255

Hi, @endel Thank you so much for your hard work,
Now I am using your framework to build an authorized game server
I need force to create room for the current process. I think it's still OK cause proxy pick process by round-robin algorithm.

**Comment by endel** [comment]
Hi @04116, thanks for your kind words. 

I think this is a reasonable feature request, I'm wondering if you could share a little bit of your use case, just out of curiosity? 

Cheers!

**Comment by 04116** [comment]
Hi @endel, thank you so much for the quick reply,
My case is I have a room tree, I need easier to check relationship, broadcast a message to them, so I need to put them into a process.
