### ISSUE TITLE
OnStateChange is not triggered after State changes on Serverside

### ISSUE THREAD

**Issue by Zoorack** [colyseus/colyseus#483]
After updating my dependencies on Server and Client no one Roomstate arrived to Client.

Other functions as send or broadcast work as exspected

I tryd with and without Schema Serializer, without Schema Serializer i take an TypeError: Bytes not iterateable
After setting up Schemaserializer complete connection from client to room succeed but nothing state changes arrived at client.

the handler onStateChange() calls once after first Connection to room and give an empty State {} (lobbyroom, has only 2 number fields in state)
In the Gameroom i received the base state structure but all empty... e.g. {players: {}, order: [] .....}

what can i do to solve that problem, i search through github, formus, discord etc...  but nothing helps.

ColyseusServer: 0.14.19
ColyseusJS: 0.14.13

thanks

**Comment by endel** [comment]
Hi @Zoorack, can you share a repository where we can reproduce the behavior you're seeing?

If you can provide more details like which browser are you testing against, front-end framework & build tools that could help figuring it out as well. Cheers!

**Comment by Zoorack** [comment]
Hi @endel, 

i used EXPO (41) as front-end framework with typescript. Issue across all devices that i try
On serverside i work also with typescript and use the default transport from colyseus.

Server dependencies:
```  "dependencies": {
    "colyseus": "~0.14.23",
    "cors": "^2.8.5",
    "crypto": "^1.0.1",
    "express": "^4.17.1",
    "express-async-handler": "^1.1.4",
    "express-session": "^1.17.0",
    "jsonwebtoken": "^8.5.1",
    "nodemailer": "6.6.3",
    "mysql2": "^1.7.0",
    "redis-server": "^1.2.2",
    "reflect-metadata": "^0.1.13",
    "typeorm": "^0.2.28",
    "@sentry/tracing": "6.10.0",
    "@sentry/node": "6.10.0",
    "expo-keep-awake": "9.3.0",
    "@colyseus/monitor": "0.14.22",
    "expo-server-sdk": "3.6.0"```

Client Dependencies:
```
"dependencies": {
    "@expo/vector-icons": "12.0.5",
    "@react-native-community/masked-view": "0.1.10",
    "@react-native-community/picker": "1.6.6",
    "@react-native-community/slider": "3.0.3",
    "@reduxjs/toolkit": "1.5.1",
    "buffer": "^5.6.0",
    "colyseus.js": "^0.14.13",
    "css-tree": "1.0.0-alpha.39",
    "expo": "^41.0.1",
    "expo-application": "~3.1.2",
    "expo-asset": "~8.3.1",
    "expo-av": "9.1.2",
    "expo-blur": "9.0.3",
    "expo-cli": "^4.4.8",
    "expo-constants": "~10.1.3",
    "expo-device": "3.2.0",
    "expo-font": "~9.1.0",
    "expo-keep-awake": "~9.1.2",
    "expo-linear-gradient": "10.0.1",
    "expo-linking": "2.4.2",
    "expo-notifications": "~0.11.6",
    "expo-screen-orientation": "~3.1.0",
    "expo-secure-store": "10.1.0",
    "expo-splash-screen": "~0.10.2",
    "expo-status-bar": "~1.0.4",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "0.63.4",
    "react-native-circular-progress": "^1.3.7",
    "react-native-gesture-handler": "~1.10.2",
    "react-native-keyboard-aware-scroll-view": "~0.9.2",
    "react-native-modal-selector": "^2.0.3",
    "react-native-reanimated": "~2.1.0",
    "react-native-responsive-fontsize": "0.5.0",
    "react-native-safe-area-context": "3.2.0",
    "react-native-screens": "~3.0.0",
    "react-native-svg": "12.1.0",
    "react-native-svg-charts": "5.4.0",
    "react-native-unimodules": "~0.13.3",
    "react-native-web": "~0.13.12",
    "react-native-webview": "11.2.3",
    "react-navigation": "^4.4.4",
    "react-navigation-stack": "^2.10.4",
    "react-redux": "7.2.3",
    "read-env": "2.0.0",
    "sentry-expo": "~3.1.4",
    "use-count-up": "3.0.1",
    "use-reducer-async": "2.0.1"
  },```


Example

State Example
```ts
import {type, Schema} from '@colyseus/schema';

export class TestState extends Schema  {
    @type('number')
    public onlinePlayers: number = 0;
    @type('number')
    public playersIngame: number = 0;
}
```

In onCreate() call once setState()


i try to build a small repo to reproduce maybe i found the issue ;)

**Comment by Zoorack** [comment]
I build a small repo with a server.
on building i try to see more with colyseus/monitor.. but on colyseus/monitor is the state also empty as on clients.

colyseus client goes through a own api not websocket and have the same issue... on the repo with server i can reproduce it.

Repo: https://git.stockklauser.eu/fstockkl/colyseus-test


Screenshots from monitor:

<img width="1207" alt="Bildschirmfoto 2021-11-23 um 10 23 57" src="https://user-images.githubusercontent.com/37815752/142999314-4bc6141a-3252-408b-94f5-b907b1b6e66f.png">

<img width="764" alt="Bildschirmfoto 2021-11-23 um 10 23 37" src="https://user-images.githubusercontent.com/37815752/142999322-3d6ea175-5e7b-41aa-8030-e76ecd44bc4f.png">

**Comment by Zoorack** [comment]
Hi @endel, i solved the Problem after reconfigure tsconfig.json.

I found a few difference to your colyseus-example problem and now the colyseus server log (DEBUG=colyseus:*) show me patches of state... before nothing patch log logged from colyseus-server

**Comment by endel** [comment]
I'm glad you've fixed it!

I'm curious what change you've made to your `tsconfig.json` that made this odd behaviour happen in the first place? Do you possibly have your old `tsconfig.json` to share here?

**Comment by Zoorack** [comment]
Hey @endel,

Sure, here my old and my new `tsconfig.json` file

OLD `tsconfig.json`
```json
{
  "compilerOptions": {
    "target": "ESNext", 
    "module": "commonjs",                     
    "sourceMap": true,                     
    "outDir": "./dist",                      
    "strict": true,       
    "esModuleInterop": true
    "inlineSourceMap": true,     
    "inlineSources": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true 
  }
}

```

  
NEW `tsconfig.json`
```json
{
  "compilerOptions": {
      "outDir": "./dist/",
      "rootDir": "./src/",
      "module": "commonjs",
      "lib": ["es6"],
      "target": "es2016",
      "declaration": true,
      "noImplicitAny": false,
      "experimentalDecorators": true,
      "emitDecoratorMetadata": true,
      "sourceMap": false,
      "esModuleInterop": true,
      "strict": true,
      "allowJs": false,
      "strictNullChecks": false,
      "skipLibCheck": true,
      "forceConsistentCasingInFileNames": true
  }
}
```
