### ISSUE TITLE
Need Client Support for AS3 - Adobe AIR SDK 

### ISSUE THREAD

**Issue by Shaunmax** [colyseus/colyseus#486]
Hello,

Could you please provide client support for AS3 - AIR SDK too.
If it requires any funding, please let us know, our AIR/Starling/Feathers community would definitely contribute. 

Thanks

**Comment by endel** [comment]
Hi @Shaunmax, 

I appreciate your interest but supporting an AS3 client would be a major effort for us, and there aren't many AS3 users to justify the efforts of developing and maintaining an SDK for it. 

You're encouraged to go ahead and make your own port from the TypeScript version to AS3, as the syntax is very similar.

---

We're open for discussion, though, feel free to reach out using this form to talk directly with the business people from the company: https://www.colyseus.io/contact

**Comment by pol2095** [comment]
[Shaunmax](https://github.com/Shaunmax) find a [workaround](https://forum.starling-framework.org/d/23733-colyseus-for-air/25) using Haxe.
