### ISSUE TITLE
Matchmaker: Malformed JSON causes server to crash

### ISSUE THREAD

**Issue by CookedApps** [colyseus/colyseus#494]
## Steps to Reproduce
1. Start the Colyseus game server as usual
2. Send a matchmake request with malformed body:  
`curl --location --request POST 'http://localhost:2567/matchmake/create/lobby' \
--header 'Content-Type: application/json' \
--data-raw '{u}'`
3. Server crashes

## Context
We noticed our server crashing with the following error:
```
SyntaxError: Unexpected token u in JSON at position 1
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (/Users/sandro/Projects/WebstormProjects/makeitmeme-server/node_modules/@colyseus/core/src/Server.ts:261:36)
    at IncomingMessage.emit (node:events:402:35)
    at IncomingMessage.emit (node:domain:475:12)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

## Expected behaviour
The server does not crash and responds with an HTTP status code 400 and respective error message.

## Your Environment
* Colyseus Version: 0.14.23
* Node.js Version: 16.13.2
* Operating System and version: Tested on Linux and OSX, but it won't matter
* Link to your project: Closed source sorry

**Comment by CookedApps** [comment]
**Suggested fix**: Moving the `JSON.parse` just one line down into the try/catch resolves the issue. 
https://github.com/colyseus/colyseus/blob/0dc966f9f3e161c63a7929486beaa8a6e11a7e2d/packages/core/src/Server.ts#L261

**Comment by endel** [comment]
Thanks for reporting @CookedApps, this has been fixed now at:
 - @colyseus/core@0.14.26
 - @colyseus/uwebsockets-transport@0.14.27

**Comment by CookedApps** [comment]
@endel Wow, thank you for that quick fix!
