### ISSUE TITLE
Sometimes this.send in colyseus 11 doesnt receive in client side

### ISSUE THREAD

**Issue by hdev72** [colyseus/colyseus#500]
Hello dear friends
I have a problem
Sometimes this.send in colyseus 11 doesnt receive in client side
Its not allways, without any change in codes some times message from server doesnt receive in client (android)
Is there any way to solve it?

**Comment by hdev72** [comment]
Maybe this problem only exists in version 11 and can be solved by migrating to 14?
The problem is that I can not upgrade the client side that is Android
  Is it possible that the server is version 14 and the client is version 11 and it works well?

**Comment by lpsandaruwan** [comment]
Hi @hdev72 

Can you please provide a code snippet or a repository to reproduce this? Thank you.

**Comment by hdev72** [comment]
Hello
I found problem and its not from colyseus , problem is in my android java repository.
