### ISSUE TITLE
Server does not sync state with clients on the latest version

### ISSUE THREAD

**Issue by jog1t** [colyseus/colyseus#510]
## Steps to Reproduce

Example CodesSandbox: https://codesandbox.io/s/dazzling-mountain-hwzfxh
1. Open CodeSandbox
2. Preview of HTML shows client's state (check console for more details).
3. Client sends `ping` message to server.
4. Server every 1s modifies the state.

## Context

Server receives `ping` messages, but client is not updated with the latest state. Checked with DevTools, server is not sending any message (sends only two at the beginning, I think they are schema types related).

Adding @colyseus/monitor, and inspecting room's state also shows empty state.

## Your Environment

* Colyseus Version: 0.14.23, ws-transport 0.14.21, schema: 1.0.34
* Node.js Version: v14.8.1
* Link to your project: https://codesandbox.io/s/dazzling-mountain-hwzfxh

**Comment by endel** [comment]
Hi @jog1t, 

Interesting find. It seems that [`defineTypes()`](https://github.com/colyseus/schema/blob/1ee5cca5fa2733b216ed3fbd6ad5a59e8820565c/src/annotations.ts#L348-L357) and defining plain JavaScript properties directly don't play nicely together:

```javascript
class State extends Schema {
  number = 0;
  property = "";
}
defineTypes(State, {
  property: "string",
  number: "number"
}); 
```

I've just tried commenting out the property initializer and then your example works: ([See sandbox link](https://codesandbox.io/s/gifted-sammet-qrku1c?))

```javascript
class State extends Schema {
  // number = 0;
  // property = "";
}
defineTypes(State, {
  property: "string",
  number: "number"
}); 
```

For TypeScript this is not an issue. We need to investigate why this is happening, if you have any clues, I highly appreciate it!

**Comment by jog1t** [comment]
@endel thanks for quick reply! 🙌🏻  Didn't have too much time today to look properly at this, but it looks like getters/setters are not set properly for properties with initial values. Will try to look at it in the following days.

**Comment by jog1t** [comment]
It's looks like TypeScript's `type` decorator also does not work 😢. I've tried also using different versions, but without any luck. Here's the same example from CodeSandbox, but uses `ts-node` or `vite-node` to run the sever - https://github.com/jog1t/colyseus-issue-510. 

🎉 What has worked for me is to define schema similar to this (see [working-solution branch](https://github.com/jog1t/colyseus-issue-510/tree/working-solution)):
```typescript
class State extends Schema {
  constructor() {
    super();
    this.property = "";
    this.number = 0;
  }
}

defineTypes(State, {
  property: "string",
  number: "number",
});

interface State extends Schema {
  property: string;
  number: number;
}
```

**Comment by WesleyClements** [comment]
This seems to only be a problem if you are compiling to or using javascript with ES Modules. [Public instance fields are added to instance using `Object.defineProperty` after `super()` in subclasses](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Public_class_fields#public_instance_fields) so the property defined in the `Schema` constructor is being overwritten.

**Comment by oyed** [comment]
> This seems to only be a problem for TypeScript if you are compiling to ES2022/ESNext

Just upgraded my entire stack to compile to ESM and this is the only major issue I've had so far. Would be great to have some movement on this!

**Comment by justin-m-lacy** [comment]
> This seems to only be a problem for TypeScript if you are compiling to ES2022/ESNext. [Public instance fields are added to subclass instances using `Object.defineProperty` immediately after the `super()` call returns](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Public_class_fields#public_instance_fields) so the property defined in the `Schema` constructor is being overwritten. I don't think there is an elegant solution to fix this currently. Could move the getters and setters definition to outside the constructor but that's kind of wonky.

If this is as you say would the solution be to abandon subclassing of schemas entirely; instead turning schemas into typed data containers?  const playerSchema = new Schema<PlayerType>({ ...playerData });

It feels similar to what Pinia does for reactive data stores.

**Comment by khoakomlem** [comment]
> It's looks like TypeScript's `type` decorator also does not work 😢. I've tried also using different versions, but without any luck. Here's the same example from CodeSandbox, but uses `ts-node` or `vite-node` to run the server - https://github.com/jog1t/colyseus-issue-510.
> 
> 🎉 What has worked for me is to define a schema class similar to this (see [working-solution branch](https://github.com/jog1t/colyseus-issue-510/tree/working-solution)):
> 
> ```ts
> class State extends Schema {
>   constructor() {
>     super();
>     this.property = "";
>     this.number = 0;
>   }
> }
> 
> defineTypes(State, {
>   property: "string",
>   number: "number",
> });
> 
> interface State extends Schema {
>   property: string;
>   number: number;
> }
> ```

 Any solution for using @decorators defining schema?

**Comment by endel** [comment]
Just found a workaround for this: setting `"useDefineForClassFields": false` on the `tsconfig.json` file: 

```typescript
  "compilerOptions": {
    "useDefineForClassFields": false,
    // ...
  }
```

This setting _may_ conflict with projects that rely on it being `true` (which is the new default for ES2022+ and the upcoming ECMA runtime behavior)

**More info:**
- [Documentation for `useDefineForClassFields`](https://www.typescriptlang.org/tsconfig#useDefineForClassFields)
- [More on the history of the decisions TypeScript made behind emitting class properties](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#the-usedefineforclassfields-flag-and-the-declare-property-modifier)

**Comment by SIGSTACKFAULT** [comment]
**works:**
```ts
export class MySchema extends Schema {
    constructor(){
        super();
        this.foo = 3;
    }
    @type("int32") foo: number;
}
```

**doesn't work:**
```ts
export class MySchema extends Schema {
    @type("int32") foo: number = 3;
}
```

**Comment by endel** [comment]
Closing this as it seems a non-issue for the moment. https://github.com/colyseus/colyseus/issues/510#issuecomment-1507828422
