### ISSUE TITLE
code:4213, error: Class constructor Room cannot be invoked without 'new'

### ISSUE THREAD

**Issue by hdev72** [colyseus/colyseus#519]
hello dear friends
my project working fine in ts but when i compile it to js in vs code im receiving following error when try to connect to room:
code:4213, error: Class constructor Room cannot be invoked without 'new'
i changed many time target of compilerOptions (es2015, 16 17 18 19 20) but problem not resolved
pls help me ❤️

**Comment by hdev72** [comment]
@endel hello dear, i have a question about this issue, Could the error be due to transpile from ts to js?

here you can see different of transpiled classes:

**Comment by hdev72** [comment]
i think error reason is this:
When your target option is set to something older than es6 (e.g. es5), TypeScript has to transpile your classes to functions, which could be problematic in some cases.

but i set target to es6

**Comment by hdev72** [comment]
resolvation:
changing target from tsconfig doesnt work for me
i used es6 in transpile command and worked :
tsc.cmd -t es6 index.ts      instead of      tsc.cmd index.ts

**Comment by hdev72** [comment]
Many friends suggested using es6 to fix this error, but using es6 causes many problems and errors and the entire JavaScript file must be edited and it is no longer possible to develop with typescript because after each time Transpile has to go through long steps again, it is better to solve this error (Class constructor Room cannot be invoked without 'new') in the same state of es5

**Comment by nmgwap** [comment]
I had the same problem as you. I created the class in js and the prompt "Error: Class constructor Room cannot be invoked without 'new'" was invoked.
