### ISSUE TITLE
return value in onAuth command execute

### ISSUE THREAD

**Issue by pauloreis7** [colyseus/colyseus#520]
I am having trouble returning a value from within a command used in the onAuth method

## Steps to Reproduce 
I have an onAuth method that uses a command
![image](https://user-images.githubusercontent.com/63323224/166565974-e860be3f-f73a-44e2-a48c-107fa2570592.png)

Within this command I perform some action on the database and return an error or void: 
![image](https://user-images.githubusercontent.com/63323224/166566355-9286f2f8-6160-44f4-9f87-bae81fbbe61d.png)

My problem is: I would like to be able to return a value from within this command to use in the onJoin method, but in doing so I get server errors.

## Context
I need to return a value from within the onAuth method to the onJoin method, but when returning this value from within the command I get an error.

When returning the value from inside the onAuth method without using the command everything works fine, but I would like to use the command patern in this case for good practice. 

I don't know if it is possible to return a value from inside the command the way I want or if I am doing something wrong.

## Your Environment

* Colyseus Version: ^0.14.2
* Node.js Version: 16.14
* Operating System and version: win 11

**Comment by endel** [comment]
Hi @pauloreis7, why don't you just use a function instead?

The command pattern is optional, and by design, they don't return any value. (You can read more about the pattern here https://gameprogrammingpatterns.com/command.html)

**Comment by pauloreis7** [comment]
Hi @endel, I am just starting out in game development, sorry for any problems, but I didn't think of using a function instead because I think that in a room we can only use commands.

In this case there would be no problem with good practice when using a JS function instead of a command?
