### ISSUE TITLE
Some questions about  “getAvailableRooms” ！

### ISSUE THREAD

**Issue by Deja-vuuu** [colyseus/colyseus#522]
I expect I can upload some custom information when I create the room and this  “getAvailableRooms”  method to return more custom content.
For example I want to show who created the room . like The game room list shows XXXX's room.

Do I have to deal with the logic myself？If so, I also need to maintain a mapping table for the RoomID

**Comment by endel** [comment]
Hi @Deja-vuuu, you can use `.setMetadata()` from the server-side to expose public room listing info: https://docs.colyseus.io/colyseus/server/room/#setmetadata-metadata
