### ISSUE TITLE
uWebSocketsTransport Have issue after reconnecting. ReadyState is not changing from 3 to 1. 

### ISSUE THREAD

**Issue by akroshteotia** [colyseus/colyseus#525]
## Steps to Reproduce (for bugs)
1. Connect to room.
2. Try reconnecting and then sending message just after reconnecting to client
3. It will throw error trying to send inactive client
4. While using Legacy its working perfectly.

### TransportCode
Currently i am using Legacy as not able to send messages after reconnect

        initializeTransport: (options) => {
        return new uWebSocketsTransport({});
        /**
         * Define your server transports as Legacy WS (legacy)
         * For local development with Legacy WS you will need to
         * provide the server option below, this is not required on Arena
         */
        //return new WebSocketTransport({
        //    ...options,
        //   pingInterval: 5000,
        //   pingMaxRetries: 3,
        //});
    },

### Server Side Reconnect Code
        

        async onLeave (client: Client, consented: boolean) 
        {
                this.state.networkedUsers.get(client.sessionId).connected = false;   
                logger.silly("*** User Leave - ${client.sessionId} ***");
      
        try {
            if (consented) {
                throw new Error("consented leave!");
            }

            logger.info("let's wait for reconnection for client: " + client.sessionId);
            await this.allowReconnection(client, 45);
            logger.info("reconnected! client: " + client.id);
            this.state.networkedUsers.get(client.sessionId).connected = true;
            logger.info("ReadyState: " + client.readyState);
            logger.info("State: " + client.state);
            client.send("onReconnect", this.state.networkedUsers.get(client.sessionId).toJSON());
            
        } catch (e) {
            logger.info("disconnected! client: " + client.id);
            logger.silly("*** Removing Networked User and Entity ${client.id} ***"");
            
            //remove user
            this.state.networkedUsers.delete(client.sessionId);

            //remove entites
            if(this.clientEntities.has(client.id)) {
                let allClientEntities = this.clientEntities.get(client.id);
                allClientEntities.forEach(element => {

                    this.state.networkedEntities.delete(element);
                });

                // remove the client from clientEntities
                this.clientEntities.delete(client.id);

                if(this.customMethodController != null)
                {
                    this.customMethodController.ProcessUserLeft(this);
                }
            } 
            else{
                logger.error("Can't remove entities for ${client.id} - No entry in Client Entities");
            }
        }
    }

## Your Environment
* Colyseus Version: 0.14.23
* Node.js Version: 8.5.0
* uWebSocketsTransport: 0.14.27
* Client : Unity

**Comment by endel** [comment]
Hi @akroshteotia, would it be possible to share your project with us? Or a minimal reproduction scenario? Thanks!

**Comment by akroshteotia** [comment]
this issue https://github.com/colyseus/colyseus/issues/436 is something related to this. After reconnect client dont send data because current state is 3 which means disconnected but to send data state need to 1 which means connected so its end up giving error `trying to send inactive client`

**Comment by endel** [comment]
Thanks for the details @akroshteotia, can you try `@colyseus/uwebsockets-transport` version `0.14.28` and see if that works?

```
npm install --save @colyseus/uwebsockets-transport@^0.14.28
```

**Comment by akroshteotia** [comment]
Let me try @endel 

> Thanks for the details @akroshteotia, can you try `@colyseus/uwebsockets-transport` version `0.14.28` and see if that works?
> 
> ```
> npm install --save @colyseus/uwebsockets-transport@^0.14.28
> ```

Let me try @endel
