### ISSUE TITLE
security issue with Redis dependency

### ISSUE THREAD

**Issue by amir-arad** [colyseus/colyseus#526]
I got [a security alert for a bad version of Redis](https://github.com/starwards/starwards/security/dependabot/1) due to my `colyseus@0.14.23` dependency.

Ideally I wouldn't even have a redis dependency as I don't use Redis in my project.

## Steps to Reproduce (for bugs)
run a security scan

## Your Environment
* Colyseus Version: 0.14.23
* Node.js Version: any
* Operating System and version: any
* Link to your project: https://github.com/starwards/starwards

**Comment by endel** [comment]
Thanks @amir-arad, `redis` has been replaced with `ioredis` on version 0.15.

```
❯ npm audit
found 0 vulnerabilities
```
