### ISSUE TITLE
Session expired on reconnecting after leave another room

### ISSUE THREAD

**Issue by baochungit** [colyseus/colyseus#531]
From my experiences, I see that if I leave the previous room after joined the new room, I will face the session expired issue when reconnecting (while using the new sessionId of the current room). Is it how colyseus working or just a bug?

BTW, I'm finding a way to check if a player can join a room before moving forward. Any good approach to deal with it?

Thank you for taking your time!

## Steps to Reproduce (for bugs)

1. Join a room A
2. Try to join room B (for me is to check if the room B can join)
3. Leave the room A
4. Refresh the app and use reconnect method with sessionId gotten from room B
5. Face "session expried" issue

## Your Environment

* Colyseus Version: ^0.14.0
* Node.js Version: v16.13.0
* Operating System and version: Windows 11
* Link to your project:

**Comment by CookedApps** [comment]
We have experienced the same issue, but when using colyseus-proxy. Are you using the proxy?

> BTW, I'm finding a way to check if a player can join a room before moving forward. Any good approach to deal with it?

You could use the [onAuth](https://docs.colyseus.io/colyseus/server/room/#onauth-client-options-request) method for that. Make your checks there and returning a negative result will cause the client not to connect to the room. You can even return custom status codes.

**Comment by baochungit** [comment]
> 

No, I'm not using colyseus-proxy for now.

About the onAuth method as you mentioned, is it possible to check if the room is not available to join (room disposed, reached maxClients value, ...) without actual joining? Because if I joined the room then I will face the session expired issue as talked above... Could you give a little more guide? Thanks!

**Comment by baochungit** [comment]
Actually this is related to the Presence subscribe function. It seems that the new subscription will not be registered if I don't unsubscribe the previous one?

I'm using the presence subscribe to tell the client to leave unconsented so that the reconnecting will work

**Comment by endel** [comment]
Hi @baochungit, can you share a minimal server code where we could reproduce the bad behavior you're experiencing? 

(e.g. forking [colyseus-examples](https://github.com/colyseus/colyseus-examples) and implementing room code + client-side to reproduce a "session expired" error)

It's hard for us to reproduce without having the exact environment and usage you have.

**Comment by baochungit** [comment]
Hi, after having a closer check, I found that it was my mistake :)
I'm using presence subscribe to a topic on each room but then call unsubscribe when the room disposed. I thought it will just unsubscribe the one in the current room but not, it unsubscribe all subscriptions having the same topic.

I don't know if you understand my case... but please close this one. Thanks!
