### ISSUE TITLE
Upgrade `mongoose` to v6

### ISSUE THREAD

**Issue by oyed** [colyseus/colyseus#542]
## Steps to Reproduce
Attempt to connect to MongoDB Atlas (serverless mongodb) using the Mongoose Colyseus Driver.

## Context
Due to a change in MongoDB Atlas, v6+ of the `mongoose` driver library is required.

## Your Environment
* Colyseus Version: `@colyseus/core@0.14.36` & `@colyseus/mongoose-driver@0.14.22`
* Node.js Version: v18.12.0
* Operating System and version: Arch Linux
* Link to your project: N/A

**Comment by endel** [comment]
Hi @oyed, we've been using the `@colyseus/redis-driver` on production instead of `@colyseus/mongoose-driver` for a while. From 0.15 onwards, the `@colyseus/redis-driver` is going to be the recommendation. Thanks for the PR, though!

**Comment by oyed** [comment]
Fair enough - does that mean the mongoose driver is being deprecated then? If not, it still makes sense to maintain the driver right?

Personally, using MongoDB Atlas as a database for Prisma, I can pull in client counts etc. natively without having to stitch one source to another, so it just made more sense to use it. I'm happy to create + maintain my own community driver for mongo though, should you want to fully deprecate this one :)
