### ISSUE TITLE
Error: provided room name "room_name" not defined

### ISSUE THREAD

**Issue by nmgwap** [colyseus/colyseus#544]
Hello ~
"Error: provided room name" room_name" not defined" Error: Provided room name" Room_name "not defined"
Version in use
"Node" : 16.10.0
"Colyseus" : 0.14.24
"Colyseus. Js" : 0.14.13
`<script>
import * as Colyseus from "colyseus.js"; // not necessary if included via <script> tag.

var client = new Colyseus.Client("ws://localhost:3300");
export default {
  name: "App",
  methods: {
    addRoom() {
      client
        .joinOrCreate("room_name")
        .then(room => {
          console.log(room.sessionId, "joined", room.name);
        })
        .catch(e => {
          console.log("JOIN ERROR", e);
        });
    }
  }
};
</script>`

Error message
JOIN ERROR Error: provided room name "room_name" not defined
    at new MatchMakeError (Client.ts?2544:12:1)
    at Client.eval (Client.ts?2544:105:1)
    at step (tslib.es6.js?b1de:102:1)
    at Object.eval [as next] (tslib.es6.js?b1de:83:1)
    at fulfilled (tslib.es6.js?b1de:73:1)

Excuse me, what is this situation？

thanks

**Comment by endel** [comment]
Hey @nmgwap, your server must `.define()` the room type, see here: https://docs.colyseus.io/colyseus/server/api/#define-roomname-string-room-room-options-any

**Comment by nmgwap** [comment]
Thank you for your reply, this problem has been solved, thank you!
