### ISSUE TITLE
Missing `processId` selection in `mongoose-driver` cause proxy failed

### ISSUE THREAD

**Issue by xVanTuring** [colyseus/colyseus#546]
Your issue may already be reported!
Please search on the [issue tracker](../) before creating one.

## Steps to Reproduce (for bugs)
>
The following will cause @colyseus/proxy unable to work,because the colyseus.js client will
build the wrong url for requesing proxy like `/undefined/....` 
The matchMaker.query will not contain `processId` when the `reserveSeatFor` will the a seat without it, the seat will be send to client for `consumeSeatReservation` and build wrong url
it will need at least two server node

0. a proxy and at least 2 server node 
1. `reserveSeatFor` from existing room (from `query`)
2. client connect to the seat (it will fail, the proxy just randomly proxy the request)

https://github.com/colyseus/colyseus/blob/91bf2cb492d33c314c2ccb90ee8d3c7dfad7ad58/packages/drivers/mongoose-driver/src/index.ts#L48-L59 
 
https://github.com/colyseus/colyseus.js/blob/fb6be05546c68b596316ef43ed7fcc19929389ba/src/Client.ts#L115-L126
``` ts
   // ...
   return `${this.endpoint}/${room.processId}/${room.roomId}?${params.join('&')}`;
```
https://github.com/colyseus/colyseus/blob/1d6b2d2486731b03c013714c9e4fd8d31b6f1084/packages/core/src/MatchMaker.ts#L132-L134
https://github.com/colyseus/colyseus/blob/1d6b2d2486731b03c013714c9e4fd8d31b6f1084/packages/core/src/MatchMaker.ts#L355-L378
## Your Environment

* Colyseus Version: 0.14.24
* Node.js Version: 
* Operating System and version: 
* Link to your project:

**Comment by xVanTuring** [comment]
fix https://github.com/colyseus/colyseus/pull/547#issue-1510109519

**Comment by naive17** [comment]
Gonna test this in a day
