### ISSUE TITLE
Add publicAddress to Colyseus monitor

### ISSUE THREAD

**Issue by CookedApps** [colyseus/colyseus#548]
## Context
Colyseus 0.15 introduces the option to host multiple server instances under a unique domain ([here](https://deploy-preview-120--colyseus-docs.netlify.app/colyseus/scalability/#alternative-2-without-the-proxy)). Colyseus monitor should reflect this feature and display the corresponding `publicAddress` for each room. This field shows the instance the room is running on. As of right now, this field is not allowed in the column options when defining the monitor.

## Your Environment

* Colyseus Version: 0.15.0-preview.6
* Colyseus Monitor Version: 0.15.0-preview.1
* Node.js Version: v16.15.1

**Comment by endel** [comment]
Hey @CookedApps, I've just published version `@colyseus/monitor@0.15.0-preview.2` which covers this, although the version you're currently using you extend the columns this way:

```typescript
app.use("/colyseus", monitor({
  columns: [
    'roomId',
    'name',
    'clients',
    'publicAddress',
    'maxClients',
    'locked',
    'elapsedTime',
  ]
));
```

Let me know if that works for you. Cheers!

**Comment by CookedApps** [comment]
Hey @endel thanks for the quick update! 
It shows up, but **there is a bug:** On every auto refresh, a new column appears. So after like 30 seconds it looks like this: 
![screenshot](https://i.imgur.com/WZmZSNA.png)

**Comment by endel** [comment]
@CookedApps oops, you're right - just updated again to only auto-append that if the `columns` customization wasn't provided! (latest `@colyseus/monitor@0.15.0-preview.3`)

**Comment by CookedApps** [comment]
Works! Thank you @endel!
