### ISSUE TITLE
Unregister/undefine a room type?

### ISSUE THREAD

**Issue by JackJohansson** [colyseus/colyseus#554]
We're implementing Colyseus in our online gaming platform, and so far it's great. We're trying to allow the rooms to be defined remotely, and then be registered/unregistered on demand. 

For registering, there's a `server.define()` method that does that. However, I can't find a away to unregister a room.

It appears that there's a `removeRoomType()` function included in `MatchMaker.js` and exported, but it's not exposed via server API. 

So, is there any way to do this? Thank you for your amazing work by the way.

**Comment by endel** [comment]
Hey @JackJohansson, glad it's working well so far for you!

Have you checked the `.filterBy()` method? https://docs.colyseus.io/colyseus/server/api/#filterbyoptions
Ideally, you shouldn't need to register and un-register rooms once the server is running, but differentiate the different types based on the filter.

Let me know if you have any question

**Comment by JackJohansson** [comment]
Thanks @endel 

The reason is that rooms are dynamically created by game developers. We have different games published by different developers, that require rooms with different logic, so we let them create/delete the rooms and then we register/remove them. 

Right now we can register them on demand with no problem, but I just wish the `removeRoomType` was also exposed for developers to use.

**Comment by JackJohansson** [comment]
@endel Oh wow. I see you've added this to the milestone. Much appreciated!
