### ISSUE TITLE
Zombie Rooms with multiple servers w/ RedisDriver

### ISSUE THREAD

**Issue by hunkydoryrepair** [colyseus/colyseus#555]
I've tracked down a bug in Colyseus that will occasionally leave a room in a Zombie state. This state is pretty bad when we have unique rooms with only a single instance of each room, and requires restarting the node.js instance to remove it.

The pattern is something like this:
- dispose a room (either autodispose or calling dispose directly)
- use asynchronous onDispose method
- a player tries to join that room soon after `dispose` is called that goes through a different node.js instance

Result:
- The room never fully disposes. It cannot be joined again, but colyseus continues to think it is around so it also cannot be disposed.

This might be specific to the RedisDriver for matchmaking. This is what I tracked down:

- we call disconnect() on the room (server)
 - this immediately deletes the roomId from REDIS
 - some asynchronous activity in onDispose causes us to await. In our case, it is updating the database.
 - a _reserveSeat call comes in from another server, which calls _incrementClientCount. Likely initiated before our disconnect() call, but it is processed only when we await in the onDispose. It may even start to execute as soon as await room.listing.remove() is run in the driver itself.
 - _incrementClientCount does not check the state to see if it is disconnecting, and calls updateOne on the RoomData, which PUTS THE ROOMID BACK IN REDIS.
 - onDispose finishes, and the 'disconnect' trigger is fired.
 
i think _incrementClientCount or _reserveSeat needs a check for this.internalState === RoomInternalState.DISCONNECTING  to prevent adding the room back to redis.  Or, perhaps, RoomData should track when it has been removed, and ignore save and updateOne calls afterwards.

**Comment by hunkydoryrepair** [comment]
FYI, we have worked around this issue by setting the room to "private" and then waiting a few seconds before we call "dispose". This creates a very brief window when the room is not joinable, which isn't a big deal, at least we don't get zombie rooms.

**Comment by hunkydoryrepair** [comment]
for us, this was rather rare. We shut down our rooms when they have been empty for 10 minutes. 
But, every once in a while, someone would join at the perfectly wrong time.  In our case, this was about once a week it would happen to one of our 5000 rooms.

**Comment by endel** [comment]
Thank you so much for the detailed report!
