### ISSUE TITLE
Need typing support for userData

### ISSUE THREAD

**Issue by khoakomlem** [colyseus/colyseus#563]
Everytime I want to use typed userData from Client, I need to assert its type using "as" keyword:
![image](https://user-images.githubusercontent.com/46867018/234564729-5e5ee814-4637-4a82-ba0e-c978eeb01b50.png)
<br>
I need help about typing for userData, can we use generic and pass UserData type to Room & Client class, so both Client and Client inside Room have UserData type?

**Comment by endel** [comment]
Hi @khoakomlem,

Version 0.15 allows customizing this via:

```typescript
import { ClientArray, Room } from "colyseus";

interface UserData {
    userId: string;
}

export class MyRoom extends Room {
    clients: ClientArray<UserData>
}
```

It may not be considered a best practice overriding a property type like this, but I'm open to suggestions to improve this!
