### ISSUE TITLE
LibGDX

### ISSUE THREAD

**Issue by customautosys** [colyseus/colyseus#569]
Any possibility of supporting? Someone did a library at https://github.com/doorbash/colyseus-kotlin but I don't think it can support 0.15

**Comment by endel** [comment]
Hi @customautosys, thanks for your interest - unfortunately, it is very time-consuming to maintain and keep yet another SDK up-to-date, so no plans to support it at this time, hopefully in the future!

You're encouraged to make your own though, as there are a few community-made SDKs here, but most of them are out-of-date :( https://docs.colyseus.io/community/#sdks-made-by-the-community

**Comment by endel** [comment]
Although I'm keen on Kotlin support because of https://korge.org 👀
