### ISSUE TITLE
Will the "Colyseus_Godot_SDK" be provided in the future?

### ISSUE THREAD

**Issue by 316902108** [colyseus/colyseus#580]
### Context & Description

Will the "Colyseus_Godot_SDK" be provided in the future?

### Use cases

Colyseus_Godot_SDK

### Proposed API

Godot 4.x

**Comment by endel** [comment]
Hi, supporting new client-side SDKs is out of scope at the moment, please see https://github.com/colyseus/colyseus/issues/581

There is a high-quality community-made Godot SDK compatible with previous version of the server here https://github.com/gsioteam/godot-colyseus
