### ISSUE TITLE
[Bug]: State sync doesn't work

### ISSUE THREAD

**Issue by TheMetaverseEngineer** [colyseus/colyseus#596]
### Context

State Synchronization

### Bug description

Hi. I don't know if this is a bug, but state sync doesn't work for me. Here is a gif of Colyseus playground:

![Peek 2023-06-27 13-55](https://github.com/colyseus/colyseus/assets/51158588/69346fa4-e9c9-42df-90ad-92e396407113)

as you can see there is no state sync!!!

### Steps to reproduce

1. create server like this:
```ts
new Server({
      transport: new WebSocketTransport({ server: http.createServer(express()) }),
    });
```
2. just use this link [Room example](https://docs.colyseus.io/server/room/#example-room)
3. use `@colyseus/playground` package for test

### Environment & Versions

Colyseus: ^0.15.0
Node: v18.16.0
Typescript: ^5.1.3
OS: Ubuntu 22.04.2 LTS
express: ^4.18.2

**Comment by endel** [comment]
Hi @TheMetaverseEngineer, you are probably missing the `"useDefineForClassFields"` config in tsconfig: https://github.com/colyseus/colyseus/issues/510#issuecomment-1507828422

When creating the server using `npm create colyseus-app ./your-app` these configs come by default.

_(If that doesn't fix I'll need you to share a full reproduction scenario)_

Cheers

**Comment by TheMetaverseEngineer** [comment]
> Hi @TheMetaverseEngineer, you are probably missing the `"useDefineForClassFields"` config in tsconfig: [#510 (comment)](https://github.com/colyseus/colyseus/issues/510#issuecomment-1507828422)
> 
> When creating the server using `npm create colyseus-app ./your-app` these configs come by default.
> 
> _(If that doesn't fix I'll need you to share a full reproduction scenario)_
> 
> Cheers

Thank u. that was exactly the problem.
