### ISSUE TITLE
[Bug]: Cannot use redis URL with RedisDriver

### ISSUE THREAD

**Issue by hunkydoryrepair** [colyseus/colyseus#598]
### Context

We have tried upgrading to Colyseus 0.15 and have hit a snag with RedisDriver and RedisPresense.
The options seem to have changed. We initialize with the url option.

```
new RedisDriver({
      url: process.env.REDIS_URL,
    }),
 ```   
 
 But the url option is ignored as of 0.15. 
 I see it is using ioredis, which can accept the url as `new Redis(url)`, but it doesn't seem to have an option in the RedisOptions to set the full url (like `redis://host:port`)
 
 I suppose our option is to parse the URL ourselves and send as port and host?

### Bug description

Initializeing RedisDriver and RedisPresense with a URL results in attempting to connect only to localhost:

127.0.0.1:6329

which of course fails.

### Steps to reproduce

1. initialize RedisDriver with {url: "redis:/remote-ip:port"}
2. create server
3.  wait for it to crash

### Environment & Versions

0.15.0 for colyseus and redisdriver.

**Comment by hunkydoryrepair** [comment]
Have fixed by changing to this. I think could be added to the breaking changes list for 0.15

```
 new RedisDriver(process.env.REDIS_URL);
 new RedisPresence(process.env.REDIS_URL);
 ```

**Comment by endel** [comment]
Thanks @hunkydoryrepair
