### ISSUE TITLE
[Bug]: onChange callback lists changes for other objects inside an ArraySchema 

### ISSUE THREAD

**Issue by natewilcox** [colyseus/colyseus#599]
### Context

export class ServerObjectState extends Schema {
  
  @type('string')
  id: string;

  @type('number')
  x: number;

  @type('number')
  y: number;

  
  constructor(id: string, x: number, y: number) {
    super();
    
    this.id = id;
    this.x = x;
    this.y = y;
  }
}

export class RoomState extends Schema {

    @type([ServerObjectState])
    serverObjects = new ArraySchema<ServerObjectState>();
}

### Bug description

When using onChange callback on individual instances inside an arrayschema property as objects are added using onAdd, each callback contains a list of changes for each item in the collection opposed to only the changes for the specific instance.

### Steps to reproduce

1. Create a schema type OBJECT_A with an x and y variable
2. Create a room state type with an ArraySchema<OBJECT_A>
3. Register a client side onChange() callback for each instance when added using onAdd()
4. When the state is synch'd from the server, onChange() lists changes for all objects in the collection instead of the specific object registered with the onChange()

### Environment & Versions

Colyseus: 0.15.5
OS: Windows 11
Typescript: 5.0.4
node: 18.13.0

**Comment by endel** [comment]
Hi @natewilcox, on version 0.15, the object's full changelist is no longer available during `onChange`. You can use `.listen()` to listen for individual properties.

(I need to update the TypeScript to remove the `changes` argument)

**Comment by natewilcox** [comment]
Thanks for the info

**Comment by natewilcox** [comment]
Clarification was made
