### ISSUE TITLE
Virtual environment  Using Purts

### ISSUE THREAD

**Issue by 2064976193** [colyseus/colyseus#606]
### Context

We used the purts library in unity and wanted to use it in js, but we got an error

### Bug description

unhandledRejection ReferenceError: FormData is not defined ReferenceError: FormData is not defined
    at Function.send (D:\workApps\unity\unityWorkSpace\domino_danmu\project\Assets\StreamingAssets\scripts\webpack:\node_modules\colyseus.js\dist\colyseus.js:124:1)

### Steps to reproduce

1.new Colyseus.Client
2.Client.joinOrCreate(err)

### Environment & Versions

"colyseus.js": "^0.15.10"
node:v16.15.1
"typescript": "^4.5.3"

**Comment by endel** [comment]
Hi @2064976193, the client SDK hasn't been thoroughly tested via [Puerts](https://github.com/Tencent/puerts).

I'd suggest adding a dummy `FormData` to the global scope to mitigate this problem:

```typescript
// define FormData (we don't actually use it inside the SDK, but there are)
class FormData {}

// expose it globally
Object.assign(globalThis, { FormData: FormData });
```

(I'm not sure `globalThis` is the correct way to expose global definitions via Puerts. It might also be `global`, or something else.)

Let me know if you find any other issues running via Puerts.

**Comment by 2064976193** [comment]
```
function send(method, uri, opts)
if (tmp instanceof FormData（here）) ; else if (tmp && typeof tmp == 'object') {
    		opts.headers['content-type'] = 'application/json';
    		opts.body = JSON.stringify(tmp);
    	}
```
   I used global, but I still got an error，using unity's sdk is not convenient。So said
