### ISSUE TITLE
[Bug]: Room api missing some methods like waitForNextMessage

### ISSUE THREAD

**Issue by Maus3rSR** [colyseus/colyseus#607]
### Bug description

Checking the documentation on the unit testing page it said that we can wait the next message to arrive with `waitForNextMessage` method but there is no such method in the implementation after some research in the codebase.

The documentation is not up to date with the codebase ?

### Steps to reproduce

Just use `await room.waitForNextMessage();` inside a test file.

### Environment & Versions

Colyseus 0.15.0
Node 18.13.0
Typescript 5.0.4
Windows 11

**Comment by endel** [comment]
Hi @Maus3rSR, 

When importing the test package (`@colyseus/testing`), a few methods are "injected" in the base room's implementation, one of them is `waitForNextMessage()`, you can see the source code for them here:

https://github.com/colyseus/colyseus/blob/ef7f93c9abcb0877180a43369ca9cfacb1716d30/packages/testing/src/Room.ext.ts#L36-L39

---

I've just tried the following and it works as expected: (inside a [test case from the template](https://github.com/colyseus/create-colyseus-app/blob/master/templates/typescript/test/MyRoom_test.ts#L16-L30))

**Room code**

```typescript
  onCreate (options: any) {
    // ...
    this.onMessage("*", (client, type, message) => {
      console.log("received message", type);
    });
    // ...
  }
```

**Test case**

```typescript
const client1 = await colyseus.connectTo(room);
client1.send("hello");
await room.waitForNextMessage();
console.log("Done.");
```

**Output log**

```typescript
received message hello
Done
```

(Without the `await room.waitForNextMessage()` call, you'd see `"Done"` before the `"received message"`)

---

Let me know if you have any feedback about these APIs. Writing tests is not something most people do, so if we can provide more helpful utility methods it would be nice.

**Comment by Maus3rSR** [comment]
Hello !

Thank you for your answer.

I just test again and it seems the method is existing. I think I maybe missed the import of colyseus testing, I don't know.
I really had "waitForNextMessage" is not a function.

However, I still have some issues I don't really understand:
```ts
    client1.send(EmpireSelectedEvent.toString(), client1EmpireMessage);
    await client1.waitForNextMessage();
```

It failed by triggering the timeout.

As a workaround I used `waitForNextPatch` that making the tests passed.

---

I have some another weird issue (I can create another ticket if you want)

```ts
  it("should receive 400 error when empire is already selected", async () => {
    room = await colyseus.createRoom<BattleRoomState>(BATTLE_ROOM_NAME.toString());

    const client1 = await colyseus.connectTo(room);
    const client1EmpireMessage: EmpireSelectedMessage = {
      emperor: "ZogZog",
      race: "ORC",
    };

    const client2 = await colyseus.connectTo(room);
    const client2EmpireMessage: EmpireSelectedMessage = {
      emperor: "Akila",
      race: "ORC",
    };

    client1.send(EmpireSelectedEvent.toString(), client1EmpireMessage);
    await client1.waitForNextMessage();

    client2.send(EmpireSelectedEvent.toString(), client2EmpireMessage);

    assert.deepStrictEqual(Array.from(room.state.players.values()), [
      new Player().assign({
        empire: new Empire().assign({
          emperor: client1EmpireMessage.emperor,
          race: client1EmpireMessage.race,
        }),
      }),
    ]);

    // I don't know how to fail the test if there is no error from the room.
    // If you get some WebSocketConnection error with the "Error: seat reservation expired" error
    // you can assume that the onError was not called.
    // You can check the log during the test to see if you got the expected error.
    return new Promise((resolve) => {
      client2.onError((code, message) => {
        assert.equal(code, 400);
        resolve();
      });
    });
  });
```

When I use the `waitForNextPatch` or `waitForNextMessage` I got an error with the reservedSeat expiration. But it's not about that a reservation expired, it's because somehow it try to retrieve a room with some ID I do not understand where it find it and nowhere I try to connect to a new room or equivalent...

I can give you access to the project if you can help me figure out what's happen.

Colyseus looks so awesome. We came from a gamejam (React JAM) using Rune SDK and unfortunately it's not mature enough and then we find Colyseus and we are rewriting and decoupling the game logic and use Colyseus as an adapter for the multiplayer feature.

Best regards,
Kevin

**Comment by Maus3rSR** [comment]
I don't why but I really don't get the `waitForNextMessage` method :/

```ts
import "mocha";
import assert from "assert";

import { Room } from "colyseus";
import { ColyseusTestServer, boot } from "@colyseus/testing";

import { BATTLE_ROOM_NAME } from "./GameRoom";
import { colyseusConfig } from "../../../../config";
import { GameState, EmpireSelectedPayload, EMPIRE_SELECTED_EVENT, PlayerEntity, EmpireEntity, PLAYER_IS_READY_EVENT } from "../../../colyseus";

describe("Feature: Starting Game", () => {
  let colyseus: ColyseusTestServer;
  let room: Room<GameState>;

  before(async () => (colyseus = await boot(colyseusConfig)));
  after(async () => colyseus.shutdown());
  beforeEach(async () => await colyseus.cleanup());
  afterEach(async () => room.setState(new GameState()));

  it("should start a game when everyone is ready", async () => {
    room = await colyseus.createRoom<GameState>(BATTLE_ROOM_NAME.toString());

    const client1 = await colyseus.connectTo(room);
    const client1EmpireMessage: EmpireSelectedPayload = {
      emperor: "ZogZog",
      race: "ORC",
    };

    const client2 = await colyseus.connectTo(room);
    const client2EmpireMessage: EmpireSelectedPayload = {
      emperor: "Elrond",
      race: "ELF",
    };

    const client3 = await colyseus.connectTo(room);
    const client3EmpireMessage: EmpireSelectedPayload = {
      emperor: "Eldric",
      race: "HUMAN",
    };

    const client4 = await colyseus.connectTo(room);
    const client4EmpireMessage: EmpireSelectedPayload = {
      emperor: "Casper",
      race: "UNDEAD",
    };

    client1.send(EMPIRE_SELECTED_EVENT.toString(), client1EmpireMessage);
    client1.send(PLAYER_IS_READY_EVENT.toString(), client1EmpireMessage);

    client2.send(EMPIRE_SELECTED_EVENT.toString(), client2EmpireMessage);
    client2.send(PLAYER_IS_READY_EVENT.toString(), client1EmpireMessage);

    client3.send(EMPIRE_SELECTED_EVENT.toString(), client3EmpireMessage);
    client3.send(PLAYER_IS_READY_EVENT.toString(), client1EmpireMessage);

    client4.send(EMPIRE_SELECTED_EVENT.toString(), client4EmpireMessage);
    client4.send(PLAYER_IS_READY_EVENT.toString(), client1EmpireMessage);

    await Promise.all([client1.waitForNextPatch(), client2.waitForNextPatch(), client3.waitForNextPatch(), client4.waitForNextPatch()]);

    client1.send(PLAYER_IS_READY_EVENT.toString(), client1EmpireMessage);

    await room.waitForNextMessage();

    assert.equal("GAME_STARTED", room.state.status);
  });
});

  ```
  
  ```sh
  server:test:int:   1) Feature: Starting Game
server:test:int:        should start a game when everyone is ready:
server:test:int:      TypeError: room.waitForNextMessage is not a function
server:test:int:       at Context.<anonymous> (c:\Projects\Web\FarmFightFaith\apps\server\src\game\adapters\primary\colyseus\GameRoomStartingGame.int.spec.ts:63:16)
```

**Comment by endel** [comment]
Hi @Maus3rSR, can you push this on the private repo you've shared with me? I'll take a look over the weekend!

**Comment by Maus3rSR** [comment]
It's just pushed :-) You just need to to use the method to see it fail.
I think it's not big issue but Im not conformtable enought with typescript module extension to keep a look. Sorry to let you watch.

Im really excited to test out everything with colyseus!

**Comment by endel** [comment]
Hi @Maus3rSR, strange, I don't seem to be able to reproduce... I've installed all dependencies from root using pnpm and then run `npm test` under `apps/server`, the test is failing but `room.waitForNextMessage` is calling properly, see video:

https://github.com/colyseus/colyseus/assets/130494/bd591974-df4e-47cc-9ab7-e11d944fca48

**Comment by Maus3rSR** [comment]
Oh... it's really my bad then. I switched on another PC and I can work with it. I do not know what's is going on... I run everything with pnpm, maybe some dependencies version mismatch with node, pnpm or whatever...
