### ISSUE TITLE
[Bug]: Type Error with RedisDriver (again)

### ISSUE THREAD

**Issue by hunkydoryrepair** [colyseus/colyseus#616]
### Context

New behavior with RedisDriver 0.15.3
Initializing with a URL

### Bug description

`ioredis` accepts a string, representing the URL, to be passed to the `Redis` constructor.

However, `string` is not a type option on the RedisDriver (or RedisPresense) constructors. In fact, the `Redis` has a number of constructors it supports:
```
constructor(port: number, host: string, options: RedisOptions);
  constructor(path: string, options: RedisOptions);
  constructor(port: number, options: RedisOptions);
  constructor(port: number, host: string);
  constructor(options: RedisOptions);
  constructor(port: number);
  constructor(path: string);
  ```
Unfortunately, `RedisOptions` does not allow a `url` for any of its many, many options. (it does have host, port, username and password all sepaerately, but that would require we parse the URL, strip off the schema, get username and password from the parameters, etc.)

I believe the only change necessary would be to add `| string` to the `options?` parameter on RedisDriver and RedisPresense constructors.

In previous version of `ioredis` RedisOptions was just defined as `any`. 

For now, casting the url string to `any` seems to work, but we want to avoid that as much as possible.

### Steps to reproduce

1. Try to initialize Redis w/ URL, `new RedisDriver('redis://hostname:1234?username=xxxx&password=xxxxx')`

### Environment & Versions

Colyseus: 0.15.3

**Comment by endel** [comment]
Hi @hunkydoryrepair, sorry for the inconvenience and thank you for the detailed report! This is now fixed on latest versions 🙏
