### ISSUE TITLE
[Bug]: Changing room to private doesn't update realtime listing

### ISSUE THREAD

**Issue by raassh-23** [colyseus/colyseus#617]
### Context

I'm trying to use realtime listing on my game and i want to allow player to set a room to be private or public after joining the room. 

### Bug description

When a room is changed to public, all the clients connected to the lobby will get `+` message and the listing is updated normally. But when changing it back to private, there is no message at all to the clients so the listing doesn't get updated. Calling `updateLobby` also doesn't work.

The current workaround is:
```js
this.setPrivate(newPrivate).then(() => {
	this.presence.publish("$lobby", `${this.roomId},${newPrivate ? 1 : 0}`); // 1 = removed, 0 = added
});
```

### Steps to reproduce

1. Create a server with lobby room
2. Connect a client to lobby
3. Create a public room in that lobby
4. Set that room to private 

### Environment & Versions

Colyseus Version: 0.15.5
Node.js Version: 18.16.0
Operating System: Windows 10

**Comment by afrokick** [comment]
Should be fixed in #668
