### ISSUE TITLE
[Bug]: @colyseus/tools Enabling multithreading in pm2 takes up multiple ports

### ISSUE THREAD

**Issue by 925999193** [colyseus/colyseus#619]
### Context

I started the colyseus service using PM2 and ran into problems when I wanted to implement multithreading

### Bug description

When launching the building results using PM2, starting multiple instances causes each instance to occupy a separate port

I read the source code 
`const processNumber = Number(process.env.NODE_APP_INSTANCE || "0");
 port += processNumber;
`
I don't know. Why is it here

### Steps to reproduce

1.npm create colyseus-app my-server
2.cd my-server
3.npm install
4.npm run build
5. cd build && pm2 start ./index.js --instances max --name Server
6. show log

### Environment & Versions

Colyseus：0.14.23
Node：v16.14.2
OS：MacOS 13.5
Env：product

**Comment by 925999193** [comment]
I upgraded the version and it doesn't work
Colyseus：0.15.0
Node：v18.13.0
OS：MacOS 13.5
Env：product

**Comment by endel** [comment]
Hi @925999193, that is the expected behavior. As each Node.js process is capable of handling incoming connections, they need to be bound to a port. It is not possible to use "cluster" mode when scaling with Colyseus - you must use PM2's "fork" mode.
