### ISSUE TITLE
[Bug]:use JoinById("roomid") returen seat reservation expired.

### ISSUE THREAD

**Issue by 925999193** [colyseus/colyseus#622]
### Context

Multiple server clusters
Can't join the same room

### Bug description

I deployed Colyseus service on two servers respectively and connected to the same RedisPresence. User A connected to server A and created a room, while user B connected to server B. Using getAvailableRooms api, user B could get the room created by user A. But a seat reservation expired error was thrown at call JoinbyId

If the framework does not support this, why is it possible to view the room created on server A after linking to server B

### Reproduction

[dist.zip](https://github.com/colyseus/colyseus/files/12496898/dist.zip)

### Steps to reproduce

1.Start the service on server A
2.Start the service on server B
3 Client A connects to server A
4.Client B connects to server B
5 Client A createorjoin room 
6. ClientB joinByid room

### Environment & Versions

"colyseus": "^0.15.0",
node:v18.13.0

**Comment by 925999193** [comment]
In redis, the server address obtained in the value of colyseus:nodes is RqwfbOwjx/null:2567

**Comment by endel** [comment]
Hi @925999193, are you setting up the `RedisDriver` as well? https://docs.colyseus.io/scalability/#step-1-use-a-shared-presence-and-driver

**Comment by 925999193** [comment]
yes.It runs the same code

**Comment by endel** [comment]
I couldn't reproduce the issue on @925999193 example. If you are still experiencing this issue, please open a new issue with an up-to-date fully reproducible example.
