### ISSUE TITLE
Bun support

### ISSUE THREAD

**Issue by Nezteb** [colyseus/colyseus#630]
### Context & Description

https://bun.sh/docs/runtime/nodejs-apis

https://blog.logrocket.com/migrating-typescript-app-node-js-bun/

### Use cases

Bun is a Zig-based alternative runtime to Node, with some performance and usability benefits: https://dev.hexagon.56k.guru/posts/deno-vs-bun-vs-node/

**Comment by endel** [comment]
Bun support has been added this week https://github.com/orgs/colyseus/discussions/628

**Comment by Nezteb** [comment]
Ah shoot I had searched the repo's GitHub issues and saw nothing related to Bun. I didn't check discussions. 🤦‍♂️

Awesome work, thanks!
