### ISSUE TITLE
[Bug]: onLeave called before onJoin

### ISSUE THREAD

**Issue by hunkydoryrepair** [colyseus/colyseus#633]
### Context

we have an async onAuth for the room, and an onLeave.

client disconnects before onAuth completes.

### Bug description

The onLeave is being called before onAuth even completes, which is well before onJoin is called.
This did not seem to be the case with 0.14, but is new with 0.15.

Not only that, but after onAuth completes, onJoin is called AFTER the onLeave.

It creates a number of issues that are pretty difficult to handle. There doesn't seem to be a publicly accessible flag on the client object to even determine this happened. I'm considering adding something to userData, but we would be required to check after every `await` in our onAuth and maybe even the `onJoin` 

Expectation is that onLeave would be called only after onJoin. If socket is disconnect during the onAuth/onJoin process, it should delay the call to onLeave until after these are complete. 

As it is, we create state for players that are not connected, and we also prevent them from logging in again.

### Steps to reproduce

1. use async onAsync
2. Disconnect client while onAsync is awaiting network call

### Environment & Versions

0.15

**Comment by hunkydoryrepair** [comment]
I've workaround using userData on the client object, which works, but does require checking it in about 14 places and adding some code to reverse our database changes if we have to abort (normally, our onLeave handles it, but since that gets called BEFORE, and does not get called again later, we are forced to simulate the onLeave in some edge cases)

**Comment by endel** [comment]
Thank you for reporting @hunkydoryrepair. 

This issue was introduced https://github.com/colyseus/colyseus/commit/5b69715e1796bce8a4374ae4f0dcd2b8c2ffcc65, now we have tests to cover this.

Please let me know if the latest version fixes it for you. Cheers!

**Comment by hunkydoryrepair** [comment]
Amazing work, endel! Will test this.

**Comment by hunkydoryrepair** [comment]
In previous tests, onLeave would also be called during the async onJoin sometimes (less often for us, as we do less async work in that case). Looking at the fix, I'm not sure it addresses onLeave while awaiting onJoin as well as the onAuth issue.

**Comment by hunkydoryrepair** [comment]
This also changes the behavior of the `clients` array during onAuth.  I don't think it impacts us, but I can see that being a breaking change.

And, it looks like we can still get onLeave DURING onJoin now. So we have this problem:
 - in onJoin, record in our db that player is in game, verify using db they are not already in game elsewhere, then add to room state
 - onLeave received while updating db. Player not in room state, so onLeave does basically nothing.
 - onLeave not called again after onJoin returns
 - RESULT: player left in room state and showing as logged in on db, but they have actually disconnected.

**Comment by hunkydoryrepair** [comment]
if we could expose the client.readyState, we could avoid this in our code I think. For now, will have to keep the userData approach.
Postponing adding client to the clients array until after onAuth probably prevents the onLeave from being called during onAuth, but seems too breaking, and would definitely be breaking if it didn't happen until after onJoin.

**Comment by hunkydoryrepair** [comment]
I believe this is expected behavior:

- onLeave only called if onJoin has completed successfully. BROKEN
- if onJoin throws error, onLeave is not called. BROKEN
- if onJoin returns successfully, onLeave will be called afterward if player disconnects BROKEN


This seems to be complicated to fix. We need the onLeave handling to ensure that onJoin completed, but also, once onJoin does complete, it needs to check if player disconnected and then process the onLeave.

Issues around this are causing negative _ccu counters and violently incorrect room counts.
