### ISSUE TITLE
[Feature]: Callback for new room creation: create new rooms based on total players, not # of rooms.

### ISSUE THREAD

**Issue by hunkydoryrepair** [colyseus/colyseus#634]
### Context & Description

Our "rooms" have very varied number of players, from 1 to 500. 
A single node.js instance can handle a couple thousand players, at least, but sometimes that is just a couple rooms.
While a server with more rooms but a lot fewer players is underutilized.

Tracking # of players per room, and spawning new rooms in server with fewest players would be a benefit to us.

A more generalized feature that exposes an API or callback that lets us apply our own room distribution logic.
For a room creation callback, controlling the target server, as well as being able to reject the room, or change the options on the room could be useful.

For example, we often have a mode where we shut down all rooms or certain rooms. There is no current way to prevent their creation, so the rooms get created and we just have to deny entry to everybody. That works fine, but it means we have a room instance running that we don't really want.

We also have no way to validate the filters. We have 100,000 valid options for the room filters, but no way to detect a bogus room creation until it is already being created. 

### Use cases

goals and philosophy of the project...This is a heavy question, but I think contirubting to the smooth operation of a multiplayer game platform would apply to a lot of projects. Any project where the rooms can vary with # of players greatly could benefit.

### Proposed API

Have not thought this through, but a callback on the server for onRoomCreate(), perhaps, the exposes the list of servers and the available room information, and can return with a definition of where to create it, and probably an opportunity to thrown an error or prevent room creation.

`server.onRoomCreate = (serverInfo) => roomDisposition`

**Comment by hunkydoryrepair** [comment]
I have a branch that gives the option during Colyseus setup to use player count (CCU) vs room count in balancing.
I can do a PR if we might want to just have that, since doing a callback to allow that seems pretty challenging. 
I set it up to only update player counts once per second when using players to balance load.

**Comment by endel** [comment]
Hi @hunkydoryrepair, thank you for sharing the detailed use-case. This would be really great to have - if you can share I'd love to see what you envision for this!

**Comment by endel** [comment]
Addressed on https://github.com/colyseus/colyseus/pull/654 🙌
