### ISSUE TITLE
[Feature]: Implementation of Redis Presence 

### ISSUE THREAD

**Issue by vineet1947** [colyseus/colyseus#642]
### Context & Description

I  went to this : https://docs.colyseus.io/server/presence/#redispresence-clientopts 

* here i was looking for a working example for redis persence  
* can't find anything using which i can scale to many rooms 
* all the rooms have to be stateful so i can sync all the data in all the rooms 
* running on same server or different server

### Use cases

--> want to sync all the data of room R1 to R2 , R3 .... Rn , running on the same sever using redis  
--> need more clarity on this feature  
--> how is the presence actually working with colyseus 
--> how is redis working with colyseus in scaling

**Comment by vineet1947** [comment]
@endel pls do reply ...

**Comment by endel** [comment]
HI @vineet1947, this issue tracker is to track status of bugs and features on the framework itself. For questions please go to [Discord](https://discord.com/invite/RY8rRS7) or [GitHub Discussions](https://github.com/orgs/colyseus/discussions). BTW there is plenty of info about Presence in both places, just give it a search. Cheers
