### ISSUE TITLE
[Bug]: Websocket closed after client reconnection

### ISSUE THREAD

**Issue by siqueirarenan** [colyseus/colyseus#644]
### Context

I currently have a Colyseus server for a game and on my trials, many users are being disconnected from the room. I want to set-up automatic reconnection. The players should never be disconnected from the server. If they go offline, they should reconnect immediately after they get online again.

### Bug description

First, I configured the "onLeave" method of the room as following, allowing a long time for the player to reconnect:
```javascript
async onLeave(client: Client, consented: boolean) {
    const playerId = client.sessionId;

    console.log(playerId, "disconnected!");
    this.dispatcher.dispatch<OnConnectionCommand>(new OnConnectionCommand(), {
      playerId,
      isConnected: false,
    });

    try {
      if (consented) {
        throw new Error("Consented leave");
      }
      await this.allowReconnection(client, 60 * 60 * 6);
      console.log(playerId, "reconnected!");
      this.dispatcher.dispatch<OnConnectionCommand>(new OnConnectionCommand(), {
        playerId,
        isConnected: true,
      });
    } catch (e) {
      console.log(client.sessionId, "left forever!");
      this.dispatcher.dispatch<OnLeaveCommand>(new OnLeaveCommand(), {
        playerId,
      });
    }
  }
```

I want the users to always be able to reconnect if they lose internet. Therefore, on my client app, I configured a retry function with exponential back-off in the "onLeave" method if the user leaves the room involuntarily.  The minimal version would be:

```typescript
const room: Room<RoomState> = await this.client.create('room', { name  });
room.onLeave(async (code: number) => {
         await this.client.reconnect(room.id, room.sessionId)
      }
    })
```

Everything goes as expected and the client gets reconnected successfully, but on the first `room.send(message)` I get the following error in the console, and the user is forced to reload the page to get reconnected properly.

‼️**WebSocket is already in CLOSING or CLOSED state.**

Why is the Websocket closed if the reconnect was successful? How can I reconnect to the websocket without reloading the page?

### Reproduction

[colyseus-bug.zip](https://github.com/colyseus/colyseus/files/12937938/colyseus-bug.zip)

### Steps to reproduce

1. Go to the folder "colyseus" and run `npm install`
2. Run colyseus with `npm start`
3. Go to the folder "client" and run `yarn install` and `yarn add react`
4. Run the client app with `yarn start`
5. In the browser, go to "localhost:3000" and open the developer console
6. You will see the room and session created. You can "send message" successfully and nothing will be displayed. Websocket works.
7. Then, click the button "unconsented leave" to simulate an unconsented leave. You will see in the console that the client gets immediatly reconnected back to the room, without error.
8. Lastly, try to click "send message" again and will see that the websocket connection was closed.

### Environment & Versions

Colyseus: 0.14.20
Node: 18.14.0
React: 18.2.0
Colyseus.js: 0.14.13
OS: Windows 10 Pro

**Comment by siqueirarenan** [comment]
[Update] I updated the colyseus and colyseus client to the latest versions (0.15), but I still get the same "Websocket CLOSED" message.
I understood that this reconnection should happen automatically, but I get this error either if I use the onLeave-reconnect logic or not.

**Comment by evgenyatlas** [comment]
> [Update] I updated the colyseus and colyseus client to the latest versions (0.15), but I still get the same "Websocket CLOSED" message. I understood that this reconnection should happen automatically, but I get this error either if I use the onLeave-reconnect logic or not.

Update Colyseus to version 0.15.x on the server side.

Based on the code you provided, I recommend recreating the server using the command `npm create colyseus-app@latest`. After that, transfer your `CozyRoom` to this new setup.

On the client side, make use of `room.reconnectionToken` as the parameter for `room.reconnect()`.

So, replace your current code on client:

```javascript
const newRoom = await client.reconnect(room.id, room.sessionId)
```

With:

```javascript
const newRoom = await client.reconnect(room.reconnectionToken)
```

I hope this helps!

**Comment by siqueirarenan** [comment]
> > [Update] I updated the colyseus and colyseus client to the latest versions (0.15), but I still get the same "Websocket CLOSED" message. I understood that this reconnection should happen automatically, but I get this error either if I use the onLeave-reconnect logic or not...

Thank you for the answer. I did as you said and updated the server and client to the latest version, but the behavior is still the same. Here is the updated reproduction: 
[colyseus-bug.zip](https://github.com/colyseus/colyseus/files/13256495/colyseus-bug.zip)

**Comment by evgenyatlas** [comment]
> Thank you for the answer. I did as you said and updated the server and client to the latest version, but the behavior is still the same. I also changed it to use reconnectionToken. Here is the updated reproduction:

I checked your example and everything works for me, i.e. the reconnect is successful. Silly, but still, maybe you should clean up node_modules and reinstall the dependencies again
<img width="332" alt="Снимок экрана 2023-11-04 в 17 33 18" src="https://github.com/colyseus/colyseus/assets/22558878/f5e0781a-85cc-453e-88c3-ca7b881afa06">

**Comment by siqueirarenan** [comment]
Humm, I did that as well, but still no success. 
In my case I also get reconnected. 
The problem is when I try to send a new message from the client after the reconnection, I get the "Websocket closed error".

**Comment by evgenyatlas** [comment]
> I did that as well, but still no success. In my case I also get reconnected. The problem is when I try to send a new message from the client after the reconnection, I get the "Websocket closed error".

If you are referring to your example, it won't work correctly because you are using .send() for the old "room" instance.

You need to replace the code in app.tsx:
```javascript
console.log("reconnecting")
const newRoom = await client.reconnect(room.reconnectionToken)
console.log("reconnected", newRoom)
```
With:
```javascript
console.log("reconnecting")
const newRoom = await client.reconnect(room.reconnectionToken)
setRoom(newRoom) //That's the important thing
console.log("reconnected", newRoom)
```

And I also recommend that you take the client creation from the component renderer to a higher level
```javascript
...
const client = new Client("ws://localhost:2567");

export const App = () => {
//old version const client = new Client("ws://localhost:2567");
const [room, setRoom] = useState<any>()
...
```

**Comment by siqueirarenan** [comment]
This was exactly the piece of information I was missing! All I had to do was update the room instance. 
Now it works as expected and it reconnects automatically.
Thank you!!

**Comment by siqueirarenan** [comment]
Resolved
