### ISSUE TITLE
[Bug]: RelayRoom.ts  public name:boolean

### ISSUE THREAD

**Issue by yty** [colyseus/colyseus#665]
### Context

```
https://github.com/colyseus/colyseus/blob/master/packages/core/src/rooms/RelayRoom.ts

class Player extends Schema { // tslint:disable-line
  public connected: boolean;
  public name: boolean;
  public sessionId: string;
}
```

### Bug description

public name: boolean; //=> public name: string;

### Steps to reproduce

This should be an oversight.

### Environment & Versions

Colyseus 0.15.13

**Comment by afrokick** [comment]
Thanks for the report!

Fixed in #667
