### ISSUE TITLE
[Bug]: Broken/invalid Schema examples

### ISSUE THREAD

**Issue by psociety** [colyseus/colyseus#670]
### Bug description

On https://0-10-x.docs.colyseus.io/state/schema/

There are types like `@type("x")` which i guess they should be `@type("number")`.
Classes like `Block` (https://0-10-x.docs.colyseus.io/state/schema/#array-of-custom-data-type) or `Player`  (https://0-10-x.docs.colyseus.io/state/schema/#map-of-custom-data-type) don't extend from schema, so they show up as invalid too in Typescript.

Quite confusing :s

### Steps to reproduce

1. Go to https://0-10-x.docs.colyseus.io/state/schema/
2. Try to follow any example in Typescript.

### Environment & Versions

```json
{
  "devDependencies": {
    "@colyseus/loadtest": "^0.15.0",
    "@colyseus/testing": "^0.15.0",
    "@types/express": "^4.17.1",
    "@types/mocha": "^10.0.1",
    "mocha": "^10.2.0",
    "rimraf": "^5.0.0",
    "tsx": "^3.12.6",
    "typescript": "^5.0.4"
  },
  "dependencies": {
    "@colyseus/monitor": "^0.15.0",
    "@colyseus/playground": "^0.15.3",
    "@colyseus/tools": "^0.15.0",
    "colyseus": "^0.15.0",
    "express": "^4.18.2"
  }
}
```

**Comment by endel** [comment]
Hi @psociety, the docs page you linked is from old version (0.10), please go to https://docs.colyseus.io for latest version (schemas page is https://docs.colyseus.io/state/schema/)
