### ISSUE TITLE
[Feature]: validate Room Options/Availability

### ISSUE THREAD

**Issue by hunkydoryrepair** [colyseus/colyseus#673]
### Context & Description

Our game design requires that we make certain rooms, or all rooms, unavailable to certain players or at certain times.
We also have a lot of bots and hackers attempting to send invalid data.

We only use a small number of room types, because there are over 200,000 different valid room options. We cannot define/register that many room types. However, we need to ensure we don't create invalid rooms. We also want to prevent duplicate rooms and prevent creating rooms when we are doing temporary maintenance.

PROBLEM: There isn't a good mechanism for denying a room creation or returning an error to the caller (client, typically) for creating the room. If we throw an error during `onCreate`, which is what we currently do, the SERVER is removed! The server is treated as dead and removed from roomcount on REDIS!

Workarounds for this are a bit difficult. If we cannot get an error back to the caller the clients will run into a different set of errors. Instead of throwing errors, we could create a "disabled" room, set it to private, and immediate destroy it. 

### Use cases

Limiting times certain rooms are available
Allowing server maintenance while process is running.
Allowing only valid room configurations to be created.
Allowing singularity rooms (rooms with only a single instance allowed).

### Proposed API

Simplest solution: don't invalidate the server just because it throws an error during `onCreate`! This seems unnecessary, and should only happen if it is a timeout. I think if there is an error thrown creating a room on any server, expect it to happen on all servers and return the error to the caller.

Alternative solution: onPreCreate to check the viability of creating the room, similar to onAuth before onJoin. Problem with this approach is it doesn't support the singularity rooms, or can cause other timing/synchronization issues. 

Being able to reject room creation within onCreate (maybe a specific exception type?) is really pretty much required.

**Comment by hunkydoryrepair** [comment]
This seems to be a new issue we encountered. I think the latest release is more aggressive at killing servers, which causes some serious problems when the servers have no active users, because they don't recover quickly at all to restore their entry into `roomcount`

**Comment by endel** [comment]
Hi @hunkydoryrepair, thanks for the detailed report as always - I think we've been missing a very obvious scenario that you just described:

If the "create room" request has been forwarded to a different process, and an error is thrown on that process, it is currently being treated as if the process fails to respond (`"ipc_timeout"`), and the "create room" request is retried at the original node. I just created a pull-request to only perform the retry in the specific case of `"ipc_timeout"` - other errors types are re-thrown: https://github.com/colyseus/colyseus/pull/674

Let me know if that looks good to you, then I'll merge and release a new version. 🙏 

(This behaviour has been the same even before your latest contribution)

**Comment by hunkydoryrepair** [comment]
Yeah, I think in my custom branch, I may have changed that in a similar way, so we only encountered this when we went back to the official release version. This would be good update.

**Comment by endel** [comment]
Awesome, thank you! I hope this fixes the issues you were having, please let me know if you have any other issues!
