### ISSUE TITLE
[Bug]: Token is undefined in static async onAuth in Defold client

### ISSUE THREAD

**Issue by bedryck** [colyseus/colyseus#679]
### Bug description

How I set the token in Defold

![image](https://github.com/colyseus/colyseus/assets/22659468/8bd88caf-60ec-4e9b-8290-abc4c123d19f)

And the token is undefined on the backend side 

### Steps to reproduce

Run latest colyseus and defold-colyseus libraries

### Environment & Versions

 "colyseus": "0.15.15"
colyseus-defold: 0.15.3

**Comment by endel** [comment]
Hi @bedryck 👋 Thanks for trying out the new auth system, currently only the JavaScript SDK is implementing it, though - I'm working on porting it to the other SDKs this week, will update here once it lands on Defold 🙏

**Comment by bedryck** [comment]
Thank you for your reply, I am looking forward to updates to this great library)

**Comment by endel** [comment]
Hi @bedryck, can you check if the latest version of the Defold SDK works for you? 🙏  Cheers!

**Comment by bedryck** [comment]
Sorry for the delay with the reply. 
I tested my game with the latest updates. However, the token is still `undefined `on the server side.
I set the token in the Defold like -  
```

 local client = ColyseusClient.new(ws_api_url)
 client.auth.token = 'some token';
 
```
I referred to https://docs.colyseus.io/authentication/#__tabbed_1_1
Can I make a mistake somewhere?

**Comment by bedryck** [comment]
Also I have a lot of such logs - 
![image](https://github.com/colyseus/colyseus/assets/22659468/6a39b17e-0081-45dd-a677-e36ba0241600)
I saw that you removed this, but didn't release it. 
https://github.com/colyseus/colyseus-defold/commit/7c5ef058c8b3110b5a92841611b5839a43963bc2

**Comment by endel** [comment]
Hi @bedryck, thanks for the feedback - just released version [0.15.6](https://github.com/colyseus/colyseus-defold/releases/tag/0.15.6).

Turns out forwarding the token on the HTTP module needed a fix too, now this test is passing 🙌  https://github.com/colyseus/colyseus-defold/blob/435f878ea79b48099c5086df28624e0563d79c81/test/auth.lua#L35-L41

**Comment by bedryck** [comment]
In 0.15.6 works as expected. 
I close a bug. Thank you!
Good luck with the development!

**Comment by endel** [comment]
Thank you @bedryck 💙
