### ISSUE TITLE
[Bug]: OnChange doesn't trigger on the client in the Unity sample

### ISSUE THREAD

**Issue by Alaadel** [colyseus/colyseus#680]
### Context

The [Unity tutorial](https://docs.colyseus.io/getting-started/unity-sdk/)

### Bug description

The message is received on the server, which runs those lines:

```
player.x = position.x;
player.y = position.y;
```

but OnChange is not called on the client (PlayerMovement.cs, line 25).
`state.OnChange` is not working. `players.OnChange` is not working either.

### Reproduction

(the included samples of the Unity package)

### Steps to reproduce

1. Add a debug message inside OnChange callback.
2. Run the included unity samples

### Environment & Versions

Colyseus: 0.15
Windows 10

**Comment by endel** [comment]
Hi @Alaadel!

The schema callbacks are only triggered within their own structures, so this would work: ([Modified from L32-35](https://github.com/colyseus/colyseus-unity-sdk/blob/405d7d8d924ac3e7545af1133ecdecebe902988b/Assets/Colyseus/Runtime/Example~/Scripts/PlayerMovement.cs#L32-L35))

```csharp
        _networkManager.GameRoom.State.players.OnAdd((key, player) =>
        {
            Debug.Log($"Player {key} has joined the Game!");
            player.position.OnChange(() => 
            {
                Debug.Log("position changed" + player.position.x + ", " + player.position.y);
            });
        });
```

(I know you're used to how the Construct 3 SDK works with "global" on change handlers, but that only applies to the exposed methods there, the same principles explained here are applied internally in the C3 SDK to allow the "global" handlers)
