### ISSUE TITLE
[Bug]: disconnect() during onCreate()

### ISSUE THREAD

**Issue by superdiazzz** [colyseus/colyseus#681]
### Context

I wrote my game code in vue 3 project with javascript and i use colyseus v 0.15.0

### Bug description

i white my code as follows:

```
<template>
    <div v-if="!isPlay">
        <AICWaitingRoom @onnickname="handleNickname" @onquit="handleQuit"/>
    </div>
    <div v-else class="mt-16">
        GAME DISINI
        <button @click="test" class="button">Count down</button>
    </div>
</template>
<script setup>
import { ref, defineAsyncComponent, provide } from 'vue'

// init server game
import * as Colyseus from 'colyseus.js'

const nickname = ref('')
const isPlay = ref(false)

const client = ref(null)
let gameRoom = null

client.value = new Colyseus.Client('ws://localhost:2568')
console.log('client ', client.value);

provide('client', client)


const AICWaitingRoom = defineAsyncComponent(() => import('../../components/aicrossword/AICWaitingRoom.vue'))



const handleNickname = async(nickname)=> {

    try {
        gameRoom = await client.value.joinOrCreate('176370', { nickname })
        console.log('berhasil join room ', gameRoom);

        // Handle state updates
        gameRoom.onStateChange(changes => {
            console.log('Room state changed:', changes);
        });

        // Handle custom messages
        // gameRoom.value.onMessage((message) => {
        //     console.log('Received message:', message);
        // });

        isPlay.value = true

    } catch (error) {
        console.log('error join ', error);
    }

}

const test = async() => {

    if(!gameRoom){
        console.log('no room');
        return
    }

    await gameRoom.send('decrement', {number: 1})
    
}
</script>
```
AICWaitingRoom is just component UI it doesn't do any controlling. It just emit the action to this main control. My `join` method is working. the only problem is `onStateChange`. It is only called once. When i join the room. I try to test by clicking `test` method to update state in room. In Colyseus monitor the state has successfully changed. But this `onStateChange` never triggered.

i added my room code here and my schema.

```
import { Room, Client, ClientArray } from "@colyseus/core";
import { TTSRoomState } from "./schema/TTSRoomState";
import { Player } from "./schema/Player";
import { Dispatcher } from "@colyseus/command"
import NicknameCommand from "../commands/tts/NicknameCommand";


export class TTSRoom extends Room<TTSRoomState> {

    private dispatcher = new Dispatcher(this)

    onCreate(options: any){
        this.setState(new TTSRoomState())
        console.log('create called', options.roomId);

        const t = options.timer
        const title = options.title
        const ownerId = options.ownerId

        this.state.timer = t
        this.state.title = title

        if(options.roomId === undefined){
            console.log('user di disconnect!');
            this.disconnect()
        }

        this.onMessage('updateNickname', (client, message) => {
            this.dispatcher.dispatch(new NicknameCommand(), { client, nickname: message.nickname})
        })

        // for test only
        this.onMessage('decrement', (client, message)=> {
            this.state.timer -= message.number
            this.state.players = this.state.players.clone()
        })

    }
    

    onJoin(client: Client, options: { nickname: string }){
        console.log(client.sessionId, "joined! ", options);
        this.state.players.set(client.sessionId, new Player(client.sessionId, options.nickname))
    }
    

    onLeave(client: Client){
        console.log(client.sessionId, "left!");
        if(this.state.players.has(client.sessionId)){
            this.state.players.delete(client.sessionId)
        }
    }

    onDispose(){
        console.log("room", this.roomId, "disposing...");
    }
}
```
TTSRoomState
```
import { Schema, ArraySchema, MapSchema, type } from "@colyseus/schema";
import { Player } from "./Player";


export class TTSRoomState extends Schema {
    
    @type("string") title: string = "Belum ada nama";
    @type({ map: Player} ) players = new MapSchema<Player>()
    @type("boolean") start: boolean = false
    @type("number") timer: number = 300
}
```

 

### Steps to reproduce

Joining into Room is success, but the method onStateChange is never called when state change. By using my code, the steps issue as follows:
1. User trigger `handleNickname` method.
2. Joining room is success and onStateChange triggered for first time
3. User click `test` method to update state.
4. onStateChange never tiggered :(

### Environment & Versions

Colyseus.js: 0.15.15 (client side)
Colyseus 0.15.0 (server side)
Nodejs: 20.10.0
typescript (server): 5.0.4
Vue(client): 3.2.31
@vue/compiler-sfc": "^3.0.0
vite": "^5.0.10"

**Comment by endel** [comment]
Hi @superdiazzz, please check your `tsconfig.json` in your server - there's a known config issue documented here: https://github.com/colyseus/colyseus/issues/510#issuecomment-1507828422

**Comment by superdiazzz** [comment]
Thank you for responding me @endel , but my  useDefineForClassFields is `false` as default

**Comment by superdiazzz** [comment]
Sure, i will provide to you later

**Comment by endel** [comment]
Thanks for the reproduction scenario. This is indeed an interesting case, as it seems the room remains active and accepting connections even after the `this.disconnect()` call here: https://github.com/superdiazzz/Checking/blob/aac5509d795ddaf62632bfad018e91e87bfabed8/server/src/rooms/TTSRoom.ts#L23-L27

If you remove that `disconnect()` call it works. The correct behaviour would be to not allow the client to establish the connection, and dispose the room as the `disconnect()` method has been called, but it seems the user is able to connect anyway due to its valid seat reservation. I'm going to investigate this soon.

**Comment by superdiazzz** [comment]
Yes, you are right. Silly me, forgot to remove the old part code. Thank you so much @endel

**Comment by endel** [comment]
No worries, let's keep this open as the current behaviour is a bit confusing.

**Comment by hunkydoryrepair** [comment]
disconnecting during onCreate is possibly not a case that needs to be supported since the `throw` during onCreate is supported now.
