### ISSUE TITLE
[Bug]: Colyseus throws an exception when a client tries to reconnect after leaving

### ISSUE THREAD

**Issue by Alaadel** [colyseus/colyseus#682]
### Bug description

Colyseus throws an exception when a client tries to reconnect after leaving.

```
Error: seat reservation expired.
    at WebSocketServer.onConnection (...\Server\node_modules\@colyseus\ws-transport\build\WebSocketTransport.js:102:15)
    at WebSocketServer.emit (node:events:513:28)
    at WebSocketServer.emit (node:domain:489:12)
    at WebSocketServer.completeUpgrade (...\Server\node_modules\ws\lib\websocket-server.js:358:5)
    at WebSocketServer.handleUpgrade (...\Server\node_modules\ws\lib\websocket-server.js:271:10)
    at Server.upgrade (...\Server\node_modules\ws\lib\websocket-server.js:107:16)
    at Server.emit (node:events:513:28)
    at Server.emit (node:domain:489:12)
    at onParserExecuteCommon (node:_http_server:880:14)
    at onParserExecute (node:_http_server:790:3)
```

### Steps to reproduce

1. server send "end" message
2. server calls `this.disconnect()`
3. client (Unity) calls LeaveRoom
4. client shows debug messages:
5.  `Websocket closed! Code:4000`
6. `[Colyseus devMode]: Re-establishing connection with room id g7rKUuDvV`
7. `MyClient OnError 0:seat reservation expired.`
8. `Websocket closed! Code:4002`
9. `[Colyseus devMode]: Re-establishing connection with room id g7rKUuDvV`
10. `MyClient OnError 0:seat reservation expired.`
11. `[Colyseus devMode]: retrying... (2 out of 8)`
12. keeps repeating from step 8.

I assume the clients keep trying to reconnect (for some reason?!) but the server can't handle the requests because the room is not valid, and keep throwing exceptions.

It keeps happening even after I restart the server and exit play mode on clients! I had to close all Unity instances.

But if instead of step 1, I `Ctrl+S` in VSCode and the server restarts, players leave normally and the infinite loop doesn't happen.

### Environment & Versions

Colyseus: 0.15

**Comment by endel** [comment]
Hi @Alaadel, this log message comes from the ["dev mode" feature](https://docs.colyseus.io/devmode/): `[Colyseus devMode]: Re-establishing connection with room id g7rKUuDvV`. 

It sounds like the Unity SDK is trying to reconnect when it shouldn't. Thanks for reporting, will investigate!

**Comment by icegriffinguru** [comment]
The same issue still happens to my server deployed on Colyseus Cloud.
I tried to disable devMode but still go the same error.

**Comment by endel** [comment]
Hi @icegriffinguru, I'm curious if I can help you out. Can you send me your Application Id from Colyseus Cloud via Discord or email endel[at]colyseus.io?

**Comment by icegriffinguru** [comment]
> Hi [@icegriffinguru](https://github.com/icegriffinguru), I'm curious if I can help you out. Can you send me your Application Id from Colyseus Cloud via Discord or email endel[at]colyseus.io?

Sure. Thank you for your help.
