### ISSUE TITLE
[Feature]: UDP

### ISSUE THREAD

**Issue by ZGltYQ** [colyseus/colyseus#701]
### Context & Description

Are you planning to add UDP support ?

### Use cases

Now we have webgpu and ability to make more complex games based on web technologies, would be nice to create multiplayer with low latency.

**Comment by ScreamZ** [comment]
The only way to support UDP is through WebRTC, Websocket doesn't allows it.

One framework is actually doing this, but using WebRTC make you use Peer-To-Peer which is not suitable for authoritative servers.

https://docs.joinplayroom.com/

**Comment by endel** [comment]
There are plans to support WebTransport (HTTP/3) this year. HTTP/3 runs on top of QUIC, which is UDP-based. WebTransport has support for datagrams.

Node.js currently does not have an official QUIC implementation yet, so we're relying on this community package: https://github.com/fails-components/webtransport

I've been experimenting with it on the branch `webtransport` both [server-side](https://github.com/colyseus/colyseus/tree/webtransport) and [client-side](https://github.com/colyseus/colyseus.js/tree/webtransport).

**Comment by ScreamZ** [comment]
@endel Woah, what a world, didn't even know that this was in the project. But it's HTTP3, even HTTP2 is not well implemented everywhere for now, waiting to see this
