### ISSUE TITLE
[Bug]: Module '"net"' has no exported member 'ServerOpts'.

### ISSUE THREAD

**Issue by Miniontoby** [colyseus/colyseus#705]
### Context

When running dev it is all fine, but when building I get the error.

And I did upgrade some packages:
```
These packages will be updated:

  @colyseus/monitor       ^0.15.4   →    ^0.15.6
  @colyseus/playground   ^0.15.11   →   ^0.15.12
  express                 ^4.18.2   →    ^4.18.3
  typescript               ^5.3.3   →     ^5.4.2

? Update package.json? Yes
```

### Bug description

My code doesn't want to build anymore:

```
> multiplayer_server@1.0.0 build
> tsc

node_modules/@colyseus/core/build/utils/Utils.d.ts:4:10 - error TS2305: Module '"net"' has no exported member 'ServerOpts'.

4 import { ServerOpts, Socket } from "net";
           ~~~~~~~~~~


Found 1 error in node_modules/@colyseus/core/build/utils/Utils.d.ts:4
```

### Steps to reproduce

I do not know how to reproduce it exactly, but perhaps you should get the same environment like me and then it possibly will already give the error...

If needed, I would be able to make a smaller version of my code and then upload it. But again, only if needed.

### Environment & Versions

Colyseus version: 0.15.15
Node.js version: 18.19.0
Typescript version: 5.4.2
Operating system: Windows 10 Pro

**Comment by endel** [comment]
Hi @Miniontoby, thanks for reporting, I'll check this soon - in the meantime, can you check if adding `skipLibCheck` to your `tsconfig.json` fixes this?

```json
  "compilerOptions": {
    // ...
    "skipLibCheck": true,
    // ...
  }
```

**Comment by Miniontoby** [comment]
Yes it does fix it.

Anyhow, I will be happy to help test any solution that you will make to fix the problem without the need of `skipLibCheck` as well...
Mostly for when you are unable to reproduce the error...
