### ISSUE TITLE
Server doesn't restart after 0.15 upgrade

### ISSUE THREAD

**Issue by yemi** [colyseus/colyseus#708]
### Context

I'm running colyseus using https://nx.dev and it all went well until I upgraded to 0.15 where the server stopped restarting on file changes. If I downgrade to 0.14 it starts working again, suggesting that there is something here preventing it from restarting.

### Bug description

When I change a file, nx automatically rebuilds the colyseus server and _usually_ restarts it, but it doesn't since 0.15.

### Steps to reproduce

Upgrade to 0.15

### Environment & Versions

The only relevant pieces seems to upgrade from 0.14 to 0.15
I'm on Node 20+

**Comment by endel** [comment]
Hi @yemi, thanks for reporting, I'm not familiar with `nx`, can you provide a small repository reproducing this issue please? 🙏

**Comment by yemi** [comment]
Sure I can put one together. I just tried again and it seems the `@nx/node` `serve` executor doesn't wait for the server to shutdown before reloading and therefore fails because the port is already being used by the previous server. 

Again, works fine as soon as I downgrade to 0.14. In case it's faster than setting up a repo, could you point me to any potential code change that might be relevant so that I can fiddle around myself, getting a feel for the code as a bonus?

**Comment by yemi** [comment]
After a big refactor this now sees to work, I have no clue what could've solved it though, closing this for now.
