### ISSUE TITLE
[Bug]: Matchmaker Player Stats can be inaccurate

### ISSUE THREAD

**Issue by hunkydoryrepair** [colyseus/colyseus#717]
### Context

We are seeing our PlayerStats steadily vary from the actual client count over time. There is always an instantaneous difference that is unavoidable (from propagation/update delays and a difference in how joining players are counted).
I've observed the biggest difference come when we dispose rooms, and especially if disposing a room that has players in it.

### Bug description

While I suspect there are other areas, I can see definite potential to both overcount and undercount players when disposing rooms.
```
if (client.state !== ClientState.RECONNECTED) {
      // try to dispose immediately if client reconnection isn't set up.
      const willDispose = await this._decrementClientCount();

      this._events.emit('leave', client, willDispose);
    }
```

When `_decrementClientCount` is called on the last player, with `autoDispose` (which is true when disposing room), the event listeners are all turned off, so the final `leave` event is not processed. Thus, it leaves an extra +1 on the player stats.

As for the undercount, I believe this is also possible if players are in `onJoin` at the time the room is disposed. `leave` will be emitted as it disconnects the player, and then when `onJoin` completes, `leave` is emitted a second time. The room `onLeave` is only called once, however. (In this case, the onLeave is actually called on room before the onJoin completes).

In general, we don't dispose rooms with players in them, but in some cases we may get players that join while disposing that trigger these problems. We see the counts are off in an extreme way whenever we initiate a shutdown which disposes all rooms even with players.

### Steps to reproduce

1. Dispose room while players in room
2. Obverse player stats from matchmaker.

### Environment & Versions

Colyseus Version: 0.15.27

**Comment by endel** [comment]
Hi @hunkydoryrepair, version of `0.15.30` of `@colyseus/core` have been just released with this https://github.com/colyseus/colyseus/pull/719 🙌  When you can, let me know if your stats are more accurate with this 🙏
