### ISSUE TITLE
[Bug]: Simultaneous joins fails due to halfway zombie seat reservation

### ISSUE THREAD

**Issue by yemi** [colyseus/colyseus#726]
### Context

Room conf:
`maxClients: 2`

### Bug description

When two clients join simultaneously, one of them will get "room is already full error" since client 1's seat reservation is still present when client 2 joins, causing `hasReachedMaxClients` to be true.

I have two questions for how this could be solved.

1. Can I provide an `authData` when calling `matchMaker.joinById` (therefore skipping async `onAuth` in `_onJoin` _and_  patch `_onJoin` so that it removes the seat reservation before async `onJoin` is called?
2. Can I patch `hasReachedMaxClients` so that it takes into account already consumed seat reservations (`[..., ..., true]`)?

Of course, if this can be solved without patching/downgrading/waiting for 1.0, I would prefer that.

### Steps to reproduce

1. User joins a room
2. _While `_onJoin` is running but before their seat reservation is deleted, another person joins_
3. This person can't join since `hasReachedMaxClients` returns `true` (client + consumed but existing seat reservation === 2)

### Environment & Versions

@colyseus/core: 0.15.27
Node: 20.11.1
Typescript: 5.5
OS: Linux

**Comment by endel** [comment]
Hi @yemi, thank you for the detailed report, I can reproduce it here! 

This is a regression introduced recently. Patching `hasReachedMaxClients` at your room level can be a good workaround while this isn't fixed on `master`. 

I'll add tests for this and see if I can release a patch today.

**Comment by endel** [comment]
Hi @yemi, I've added a test for this and just published `@colyseus/core@0.15.37` 🙌
