### ISSUE TITLE
[Bug]: room.state in client is undefined

### ISSUE THREAD

**Issue by neizzz** [colyseus/colyseus#739]
### Bug description

In the room object returned by `Client.create` method, state field is undefined.
But, in server, the room.state is no problem.

### Steps to reproduce

``` javascript
import { Client } from 'colyseus.js';
import { createBrowserRouter } from 'react-router-dom';

const client = new Client(...);

createBrowserRouter([
  {
    path: '/room/create',
    loader: async (): Promise => {
        return {
          room: await client
            .create(...)
            .then(room => {
              // this room.state is undefined!!
              return room;
            }),
        };
      }
    },
    Component: WaitingRoomPage,
  },
]);
```

### Environment & Versions

Colyseus: v0.15.0
Node.js: v20.14
OS: ubuntu 22.04

**Comment by endel** [comment]
Hi @neizzz, please check if this configuration is missing on your server-side: https://github.com/colyseus/colyseus/issues/510#issuecomment-1507828422

Also, the state is received asynchronously once the client connects with the server. You'll need to attach client-side callbacks to your structures: https://docs.colyseus.io/state/schema-callbacks/

If this doesn't help you, please share your entire sources as there might be something else going on. Cheers

**Comment by neizzz** [comment]
@endel thank you for very quick reply!
(please understanding I'm not native english..)

* below is my tsconfig. already `"useDefineForClassFields": false,` option set.
```json
// tsconfig.json
{
  "compilerOptions": {
    "target": "ES2020",
    "module": "ES2020",
    "moduleResolution": "Bundler",
    "resolveJsonModule": false,
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "useDefineForClassFields": false,
    "allowImportingTsExtensions": false,
    "noEmit": false,
    "paths": {
      "@utils/*": ["./src/utils/*"],
      "@constants": ["./src/constants.ts"]
    }
  },
  "include": ["src"],
  "exclude": ["node_modules"]
}
```

* can i attach callback?? (although room.state is undefined)

* you can see my [repo](https://github.com/neizzz/hmz)
above code is in 
https://github.com/neizzz/hmz/blob/master/packages/apps/fe/src/App.tsx

**Comment by neizzz** [comment]
Additionally,

This bug does not reproduce when running locally, but occurs when deployed in the environment(my small web server..) mentioned above.

**Comment by endel** [comment]
I was going to mention I can't reproduce locally. I'm afraid I can't help with this limited information. It's likely an issue in your deployed environment. Can you share the public URL of your project where we can see the issue?

**Comment by neizzz** [comment]
you can enter cchsv.iptime.org

and, 
1. input nick name
2. click `Quick Room` button

**Comment by neizzz** [comment]
@endel 

<img width="1009" alt="image" src="https://github.com/colyseus/colyseus/assets/97387461/957f81a2-a8a2-463e-b405-cc5cc5c9c9a8">

this debug log is yours

**Comment by neizzz** [comment]
@endel 

<img width="1012" alt="image" src="https://github.com/colyseus/colyseus/assets/97387461/e99d9af5-f5ee-4f53-82e3-261d3f804895">

**Comment by neizzz** [comment]
@endel 

<img width="1012" alt="image" src="https://github.com/colyseus/colyseus/assets/97387461/f3d9fc46-db25-49fe-813b-04f850f2395d">

**Comment by neizzz** [comment]
> I'm trying to understand why you're getting this error. This should not be happening.
> 
> <img alt="image" width="702" src="https://private-user-images.githubusercontent.com/130494/338776803-efb39018-7a7c-408c-9c0c-44ee53b596ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNTAxOTIsIm5iZiI6MTcxODE0OTg5MiwicGF0aCI6Ii8xMzA0OTQvMzM4Nzc2ODAzLWVmYjM5MDE4LTdhN2MtNDA4Yy05YzBjLTQ0ZWU1M2I1OTZmZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMVQyMzUxMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MDA0ZGM3ZDhhZGJjMDE0NzIyYTQ2Njg4ZmM2YTU5YWE0Y2RjYjBiNTI1NmJiOGJkNDA1ZDE3Y2QyNzJjNWZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CaSmD3ZIe0-AejnNHdSaV8Nhbuby2VROippuvLWt1ds">


This error seems to occur because room.state is undefined.

**Comment by endel** [comment]
For some strange reason the server is not sending the handshake bytes. The very first message the client receive from the server is the `Protocol.JOIN_ROOM` containing the handshake. This is used to initialize the state, but `this.serializer.handshake()` is not being called there. 

<img width="425" alt="image" src="https://github.com/colyseus/colyseus/assets/130494/2bc88b6e-1850-46f1-a0e4-8bc20dbcbc87">

<img width="179" alt="image" src="https://github.com/colyseus/colyseus/assets/130494/84248f0f-8202-48d7-8fef-680e2f039ae2">

I'd suggest debugging in your server why `handshakeCache` might be empty here. This may have some relation to the `@shared/types` package. Let me know what you find with this!
 https://github.com/colyseus/colyseus/blob/8d71af565813d36450671db65aa039e535de547d/packages/core/src/serializer/SchemaSerializer.ts#L111

**Comment by neizzz** [comment]
@endel 

where is below code?
![image](https://github.com/colyseus/colyseus/assets/97387461/e14a6737-cc13-440e-be00-480657dde7f0)

**Comment by endel** [comment]
That's on `Room.js` from the SDK: https://github.com/colyseus/colyseus.js/blob/1f1736bc6301811d9bc713ddcf6be6b7b1de8534/src/Room.ts#L205-L207

**Comment by neizzz** [comment]
@endel 

(At the code receiving `Protocol.JOIN_ROOM` in Room.ts)
When I running locally, bytes length was 488.
but in this issue reproduce environment, bytes length was 18 only containing `reconnectionToken`, and `serializerId`.

is this means that the client receive only 18 bytes from websocket?
Shouldn't we be debugging server side?

**Comment by neizzz** [comment]
@endel 

I tried debugging the server side.

I put `console.log` in the @colyseus/schema package, just before the return statement of the Schema::encode method.
(https://github.com/colyseus/schema/blob/bcb67b03d1f655d5fe1deae09f7629dcda9cebe3/src/Schema.ts#L651-L655)

``` typescript
encode(encodeAll = false, bytes, useFilters) {
        // ...
        console.log('encode', bytes);
        return bytes;
}
```

when running locally, log was below.
<img width="323" alt="image" src="https://github.com/colyseus/colyseus/assets/97387461/44420b9b-cab2-471c-bde3-45f372c73bdf">

but, on this issue environment, log was below.
<img width="333" alt="image" src="https://github.com/colyseus/colyseus/assets/97387461/383278a7-d0c7-4052-9487-6c2c76a9753f">


On this issue environment, first encoded data is empty array..
I hope this is a hint for you.

**Comment by neizzz** [comment]
@endel 

I did the build output.

Now in my repo `test` branch, you can run the server by `npm run start` in project root. then, enter `localhost:8080`.

Additionally, I found out while preparing for `test` branch, This issue can be reproduced by running the build output. (not running the dev server that meaning 
 previously said _run locally_)

**Comment by endel** [comment]
Thanks for sharing. I'm trying to understand the cause of this, very intriguing.

**Comment by endel** [comment]
It turns out the ESM build from `@colyseus/schema` was not using the `"useDefineForClassFields"` config. I've just fixed this on the latest `@colyseus/schema` version. 

The cause was because the Reflection types to be compiled as follows:

```typescript
class ReflectionField extends Schema {
    name;
    type;
    referencedType;
}
```

Whereas they should've been like this, so we can inject our own property descriptors in order to detect changes and encode them:

```typescript
class ReflectionField extends Schema {
}
```

Let me know if you have any other issues! Thanks for reporting again.
