### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by simpsonphile** [colyseus/colyseus#793]
### Context

I migrated my code form common to es6 and now creation of room is not working

### Bug description

this is my code of one of rooms check comments and console.log on onCreate - this is the place problem arises

```
import { Room } from "colyseus.js";
import { SERVER_MESSAGES, CLIENT_MESSAGES } from "../messageTypes.js";
import ChatState from "../states/ChatState.js";

class ChatRoom extends Room {
  onCreate(options) {
    console.log("this in onCreate:", this); // Check what `this` is here
    if (this) {
      console.log("we are inside if"); // yep
      this.setState(new ChatState()); // not working  Cannot read properties of undefined (reading 'setState')
    } else {
      console.error("this is undefined in onCreate!"); // nope we don't get here
    }

    this.onMessage(CLIENT_MESSAGES.MESSAGE, (client, message) => {
      this.state.addMessage(client.sessionId, message);

      if (!message.value) return;

      this.broadcast(SERVER_MESSAGES.NEW_MESSAGE, this.state.getLastMessage());
    });
  }

  // When a player joins, add them to the state
  onJoin(client, options) {
    this.state.addUser(client.sessionId, options.nickname);
    this.state.addJoinMessage(client.sessionId);
    this.broadcast(SERVER_MESSAGES.NEW_MESSAGE, this.state.getLastMessage(), {
      except: client,
    });
  }

  // When a player leaves, remove them from the state
  onLeave(client, consented) {
    this.state.removeUser(client.sessionId);
  }

  // Clean up on dispose
  onDispose() {
    console.log("ChatRoom disposed.");
  }
}

export default ChatRoom;
```

### Reproduction

[Server.zip](https://github.com/user-attachments/files/17686503/Server.zip)

### Steps to reproduce

install express 4.21.1 and colysesus 0.15.17
unzip Server.zip
run node ./Server

### Environment & Versions

Colyseus version: 0.15.17
node: 16.17.0
no typescript 
operating system: macOs 14.6.1

**Comment by endel** [comment]
Hi @simpsonphile, the issue is likely the import from `colyseus.js` in the first line:

```
import { Room } from "colyseus.js";
```

The `colyseus.js` module is the JavaScript SDK (client-side). For the server-side module you'd want to use `colyseus` instead of `colyseus.js`

**Comment by endel** [comment]
I've been wanting to rename the `colyseus.js` to `@colyseus/sdk` for clarity... May do this once next version `0.16` comes out!

**Comment by simpsonphile** [comment]
oh thanks! :)
