### ISSUE TITLE
[Bug]: Health check failed: Process not available

### ISSUE THREAD

**Issue by khanghdc98** [colyseus/colyseus#799]
### Context

I create a Colyseus Server with RedisDriver, RedisPresence and Express server. When I call the API endpoints of the Express, it succeeds and when I create room on the playground dashboard, it succeeds to. This indicates that the server is working just right.

### Bug description

The problem occurs when calling any methods relevant to `join` that needs to search for available rooms including Join or Create, or Join. The colyseus server will continuously `Performing health-check against processId: 'rgkt237Sr'...` but always fails: `Process 'rgkt237Sr' failed to respond. Cleaning it up. removing stale rooms by processId: rgkt237Sr (0 rooms found)`. It will return a message to a client, which is `Error: process rgkt237Sr is not available.`

I also notice that there are rooms which were created previously but did not get disposed. I know that when the server shuts down, all rooms would be disposed already. Why do these rooms still exist?

Could you please provide me information on wher the room information are stored since those stale rooms are not removed even when I restart my computer? Also, how do colyseus perform the health check?

### Steps to reproduce

Sorry for not providing the source code but this is my enterprise project that should not be disclosed on any circumstances.

### Environment & Versions

```
"devDependencies": {
    "@biomejs/biome": "1.9.3",
    "@colyseus/loadtest": "^0.15.0",
    "@colyseus/testing": "^0.15.0",
    "@types/express": "^4.17.1",
    "@types/jest": "^29.5.13",
    "@types/mocha": "^10.0.8",
    "rimraf": "^5.0.0",
    "tsx": "^4.10.2",
    "typescript": "^5.4.5"
  },
  "dependencies": {
    "@colyseus/auth": "^0.15.10",
    "@colyseus/command": "^0.3.1",
    "@colyseus/monitor": "^0.15.0",
    "@colyseus/playground": "^0.15.3",
    "@colyseus/redis-driver": "^0.15.6",
    "@colyseus/redis-presence": "^0.15.5",
    "@colyseus/schema": "^2.0.35",
    "@colyseus/tools": "^0.15.0",
    "@types/jsonwebtoken": "^9.0.7",
    "axios": "^1.7.7",
    "colyseus": "^0.15.17",
    "dotenv": "^16.4.5",
    "express": "^4.21.0",
    "express-basic-auth": "^1.2.1",
    "ioredis": "^5.4.1",
    "jsonwebtoken": "^9.0.2"
  }
```
OS: MacOS 14.5 (23F79)

**Comment by endel** [comment]
Hi @khanghdc98, I'd suggest to upgrade to latest versions of `@colyseus/core` and `@colyseus/redis-driver`. At the time of this writing these are the latest versions:

- `@colyseus/core` (`^0.15.55`)
- `@colyseus/redis-driver` (`^0.15.6`)

The `colyseus` module is simply a bundle of `@colyseus/core` and other modules, so if you installed it a few months from now, your `package-lock.json` may have locked a bad version of `@colyseus/core`.

Hope this helps! Let me know if that fixes for you. Cheers
