### ISSUE TITLE
[Bug]: onAuth failed but room is locked because having that client

### ISSUE THREAD

**Issue by khanghdc98** [colyseus/colyseus#800]
### Context

I create a Colyseus Server with RedisDriver, RedisPresence and Express server. I am also implementing the password protection for the rooms as follows (minimalize):

```
  onCreate(options: any) {
    if (options.password) {
      this.protectPassword = options.password
    }
  //...
  }

```

```
async onAuth(client: Client, options: any) {
    try {
      if (this.protectPassword && this.protectPassword !== options.password) {
        throw new Error('Password not matching')
      }
    /...
      return true
    } catch (error: any) {
      if (this.state.players.has(client.sessionId)) {
        this.state.players.delete(client.sessionId)
        console.log('delete player')
      }
      console.log('clients', this.clients, this.locked)
      throw new ServerError(401, error.message)
    }
  }
```

### Bug description

Provided in the `onAuth` method, when the password is not matching, an Error is thrown and prevent the user from joining the room. The problem occurs when the user enters the correct password. It says `Error: room "..." is locked`.

I have inspected on the Colyseus Dashboard. The main list shows that there are 2 clients in the room
![Screenshot 2024-11-21 at 5 03 14 PM](https://github.com/user-attachments/assets/aade184b-89d7-4a65-8308-f7e0bb0aa1f2)

However, inside the room (click on Inspect), there is only 1 client.
![Screenshot 2024-11-21 at 5 04 12 PM](https://github.com/user-attachments/assets/5c266cc3-9d31-4f15-95ff-b2dc38a80112)

The console.log in the `catch` shows a list of 1 client and the room.locked is true. Isn't this a bit contradictory?

### Reproduction

Repo link: [here](https://github.com/khanghdc98/colyseus-test)

### Steps to reproduce
0. Get to the playground by navigate to `localhost:<PORT>`
1. Create a room with password. Sample join options:
```
{
  "roomType": "SKILL",
  "roomMode": "PVP",
  "password": "13"
}
```
3. Another client joins by ID with the wrong password. Sample join options:
```
{
  "roomType": "SKILL",
  "roomMode": "PVP",
  "password": "123"
}
```
This must yeild the error message `"protectPassword not matching"`
5. That client joins again by ID with the correct password. Sample join options:
```
{
  "roomType": "SKILL",
  "roomMode": "PVP",
  "password": "13"
}
```
This must yeild the error message `"room <RoomID> is locked"`

### Environment & Versions

"devDependencies": {
    "@biomejs/biome": "1.9.3",
    "@colyseus/loadtest": "^0.15.0",
    "@colyseus/testing": "^0.15.0",
    "@types/express": "^4.17.1",
    "@types/jest": "^29.5.13",
    "@types/mocha": "^10.0.8",
    "rimraf": "^5.0.0",
    "tsx": "^4.10.2",
    "typescript": "^5.4.5"
  },
  "dependencies": {
    "@colyseus/auth": "^0.15.10",
    "@colyseus/command": "^0.3.1",
    "@colyseus/monitor": "^0.15.0",
    "@colyseus/playground": "^0.15.3",
    "@colyseus/redis-driver": "^0.15.6",
    "@colyseus/redis-presence": "^0.15.5",
    "@colyseus/schema": "^2.0.35",
    "@colyseus/tools": "^0.15.0",
    "@types/jsonwebtoken": "^9.0.7",
    "axios": "^1.7.7",
    "colyseus": "^0.15.17",
    "dotenv": "^16.4.5",
    "express": "^4.21.0",
    "express-basic-auth": "^1.2.1",
    "ioredis": "^5.4.1",
    "jsonwebtoken": "^9.0.2"
  }

**Comment by khanghdc98** [comment]
is there any updates on this issue? @endel

**Comment by endel** [comment]
Hi @khanghdc98, can you provide a repository where the issue is reproducible via the “playground” URL? 🙏

**Comment by khanghdc98** [comment]
Hi @endel, I have a testing repo following this [link](https://github.com/khanghdc98/colyseus-test). I have also updated the Reproduction section in the above issue description.

**Comment by khanghdc98** [comment]
Hi @endel, is there any updates about this issue?

**Comment by endel** [comment]
Hi @khanghdc98, thank you so much for providing the reproduction repository! 🙏  This issue seems related to https://github.com/colyseus/colyseus/issues/803, which was a regression introduced recently... Version `0.15.57` have been released today fixing it. Can you try it out please? https://github.com/colyseus/colyseus/releases/tag/0.15.57

**Comment by khanghdc98** [comment]
Great, it is working now. Thank you for your devotion.
